# Generated by Django 5.2.9 on 2026-01-27 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الاجتماع"),
                ),
                ("date", models.DateTimeField(verbose_name="تاريخ ووقت الاجتماع")),
                ("topic", models.TextField(verbose_name="موضوع الاجتماع")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الاجتماع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ الاجتماع",
                    ),
                ),
            ],
            options={
                "verbose_name": "اجتماع",
                "verbose_name_plural": "الاجتماعات",
                "permissions": [
                    ("view_meetingtask", "Can view meeting tasks"),
                    ("add_meetingtask", "Can add meeting tasks"),
                    ("change_meetingtask", "Can change meeting tasks"),
                    ("delete_meetingtask", "Can delete meeting tasks"),
                    ("view_meetingreport", "Can view meeting reports"),
                    ("export_meetingreport", "Can export meeting reports"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MeetingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف المهمة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("in_progress", "قيد التنفيذ"),
                            ("completed", "مكتملة"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء المتوقع"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم تعيينها لـ",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_tasks",
                        to="meetings.meeting",
                        verbose_name="الاجتماع",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة اجتماع",
                "verbose_name_plural": "مهام الاجتماعات",
            },
        ),
        migrations.CreateModel(
            name="MeetingTaskStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف الخطوة")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="مكتملة"),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإنجاز"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_meeting_task_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "meeting_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="meetings.meetingtask",
                        verbose_name="مهمة الاجتماع",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطوة مهمة اجتماع",
                "verbose_name_plural": "خطوات مهام الاجتماعات",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="meetings.meeting",
                        verbose_name="الاجتماع",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور",
                "verbose_name_plural": "الحضور",
                "unique_together": {("meeting", "user")},
            },
        ),
    ]
