# Generated by Django 5.0.14 on 2025-07-23 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_login_new_groups_and_more'),
        ('meetings', '0004_meetingtaskstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='accounts.users_login_new', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.users_login_new', verbose_name='منشئ الاجتماع'),
        ),
        migrations.AlterField(
            model_name='meetingtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_tasks', to='accounts.users_login_new', verbose_name='تم تعيينها لـ'),
        ),
        migrations.AlterField(
            model_name='meetingtaskstep',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_task_steps', to='accounts.users_login_new', verbose_name='تم الإنشاء بواسطة'),
        ),
    ]
