# Generated by Django 4.2.7 on 2025-08-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('run_id', models.AutoField(db_column='RunID', primary_key=True, serialize=False)),
                ('run_date', models.DateField(blank=True, db_column='RunDate', null=True)),
                ('month_year', models.CharField(db_column='MonthYear', max_length=7)),
                ('status', models.CharField(db_column='Status', default='Draft', max_length=30)),
                ('confirmed_by', models.IntegerField(blank=True, db_column='ConfirmedBy', null=True)),
            ],
            options={
                'verbose_name': 'تشغيل راتب',
                'verbose_name_plural': 'تشغيلات الرواتب',
                'db_table': 'PayrollRuns',
            },
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('payroll_detail_id', models.AutoField(db_column='PayrollDetailID', primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(blank=True, db_column='BasicSalary', decimal_places=2, max_digits=18, null=True)),
                ('housing', models.DecimalField(blank=True, db_column='Housing', decimal_places=2, max_digits=18, null=True)),
                ('transport', models.DecimalField(blank=True, db_column='Transport', decimal_places=2, max_digits=18, null=True)),
                ('overtime', models.DecimalField(blank=True, db_column='Overtime', decimal_places=2, max_digits=18, null=True)),
                ('gosi', models.DecimalField(blank=True, db_column='GOSI', decimal_places=2, max_digits=18, null=True)),
                ('tax', models.DecimalField(blank=True, db_column='Tax', decimal_places=2, max_digits=18, null=True)),
                ('loan_deduction', models.DecimalField(blank=True, db_column='LoanDeduction', decimal_places=2, max_digits=18, null=True)),
                ('net_salary', models.DecimalField(blank=True, db_column='NetSalary', decimal_places=2, max_digits=18, null=True)),
                ('paid_date', models.DateField(blank=True, db_column='PaidDate', null=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('run', models.ForeignKey(db_column='RunID', on_delete=django.db.models.deletion.CASCADE, to='payrolls.payrollrun')),
            ],
            options={
                'verbose_name': 'تفصيل راتب',
                'verbose_name_plural': 'تفاصيل الرواتب',
                'db_table': 'PayrollDetails',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('salary_id', models.AutoField(db_column='SalaryID', primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(blank=True, db_column='BasicSalary', decimal_places=2, max_digits=18, null=True)),
                ('housing_allow', models.DecimalField(blank=True, db_column='HousingAllow', decimal_places=2, max_digits=18, null=True)),
                ('transport', models.DecimalField(blank=True, db_column='Transport', decimal_places=2, max_digits=18, null=True)),
                ('other_allow', models.DecimalField(blank=True, db_column='OtherAllow', decimal_places=2, max_digits=18, null=True)),
                ('gosi_deduction', models.DecimalField(blank=True, db_column='GosiDeduction', decimal_places=2, max_digits=18, null=True)),
                ('tax_deduction', models.DecimalField(blank=True, db_column='TaxDeduction', decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(db_column='Currency', default='SAR', max_length=3)),
                ('effective_date', models.DateField(blank=True, db_column='EffectiveDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('is_current', models.BooleanField(db_column='IsCurrent', default=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'راتب موظف',
                'verbose_name_plural': 'رواتب الموظفين',
                'db_table': 'EmployeeSalaries',
            },
        ),
    ]
