# Generated by Django 4.2.22 on 2025-08-29 02:11

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employeebankaccount_bank_id_and_more'),
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCalculationRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100, verbose_name='اسم القاعدة')),
                ('rule_type', models.CharField(choices=[('overtime', 'وقت إضافي'), ('deduction', 'خصم'), ('bonus', 'مكافأة'), ('tax', 'ضريبة')], max_length=20, verbose_name='نوع القاعدة')),
                ('formula', models.TextField(verbose_name='معادلة الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قاعدة حساب راتب',
                'verbose_name_plural': 'قواعد حساب الرواتب',
            },
        ),
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'ordering': ['-effective_date'], 'verbose_name': 'راتب موظف', 'verbose_name_plural': 'رواتب الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='payrolldetail',
            options={'ordering': ['emp__emp_code'], 'verbose_name': 'تفصيل راتب', 'verbose_name_plural': 'تفاصيل الرواتب'},
        ),
        migrations.AlterModelOptions(
            name='payrollrun',
            options={'ordering': ['-run_date', '-created_at'], 'verbose_name': 'تشغيل راتب', 'verbose_name_plural': 'تشغيلات الرواتب'},
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='transport',
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salaries', to='employees.employee', verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='deduct_absent_days',
            field=models.BooleanField(default=True, verbose_name='خصم أيام الغياب'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='deduct_late_minutes',
            field=models.BooleanField(default=True, verbose_name='خصم دقائق التأخير'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='deduct_unpaid_leave',
            field=models.BooleanField(default=True, verbose_name='خصم الإجازات غير مدفوعة الأجر'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='food_allow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='بدل الطعام'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='holiday_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=5, verbose_name='معدل عمل العطل'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='insurance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='خصم التأمين الطبي'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='mobile_allow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='بدل الهاتف'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='خصومات أخرى'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=5, verbose_name='معدل الوقت الإضافي'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('hourly', 'بالساعة'), ('daily', 'يومي'), ('project', 'مشروع')], default='monthly', max_length=20, verbose_name='نوع الراتب'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='transport_allow',
            field=models.DecimalField(db_column='Transport', decimal_places=2, default=0, max_digits=18, verbose_name='بدل المواصلات'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='weekend_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.0'), max_digits=5, verbose_name='معدل عمل نهاية الأسبوع'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='absence_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='خصم الغياب'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='أيام الغياب'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مكافآت'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='calculation_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الحساب'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='عمولة'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='food_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='بدل الطعام'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='gosi_deduction',
            field=models.DecimalField(db_column='GOSI', decimal_places=2, default=0, max_digits=18, verbose_name='خصم التأمينات'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الراتب'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='housing_allowance',
            field=models.DecimalField(db_column='Housing', decimal_places=2, default=0, max_digits=18, verbose_name='بدل السكن'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='insurance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='خصم التأمين الطبي'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='تم المعالجة'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='late_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='خصم التأخير'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='late_minutes',
            field=models.IntegerField(default=0, verbose_name='دقائق التأخير'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='أيام الإجازة'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='mobile_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='بدل الهاتف'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='بدلات أخرى'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='خصومات أخرى'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='overtime_amount',
            field=models.DecimalField(db_column='Overtime', decimal_places=2, default=0, max_digits=18, verbose_name='مبلغ الوقت الإضافي'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ساعات إضافية'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='payment_method',
            field=models.CharField(default='bank_transfer', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='tax_deduction',
            field=models.DecimalField(db_column='Tax', decimal_places=2, default=0, max_digits=18, verbose_name='خصم الضرائب'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي البدلات'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الخصومات'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='transport_allowance',
            field=models.DecimalField(db_column='Transport', decimal_places=2, default=0, max_digits=18, verbose_name='بدل المواصلات'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='worked_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='أيام العمل'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to='employees.employee', verbose_name='معتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='calculation_method',
            field=models.CharField(default='attendance_based', max_length=50, verbose_name='طريقة الحساب'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to='employees.employee', verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='include_bonuses',
            field=models.BooleanField(default=True, verbose_name='تضمين المكافآت'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='include_deductions',
            field=models.BooleanField(default=True, verbose_name='تضمين الخصومات'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='include_overtime',
            field=models.BooleanField(default=True, verbose_name='تضمين الوقت الإضافي'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='payroll_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('bi_weekly', 'نصف شهري'), ('weekly', 'أسبوعي'), ('bonus', 'مكافآت'), ('final_settlement', 'تصفية نهائية')], default='monthly', max_length=20, verbose_name='نوع الراتب'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='period_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='نهاية الفترة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='period_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='بداية الفترة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='processed_employees',
            field=models.IntegerField(default=0, verbose_name='الموظفين المعالجين'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='processing_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المعالجة'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='run_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='رقم التشغيل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='إجمالي الخصومات'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_employees',
            field=models.IntegerField(default=0, verbose_name='إجمالي الموظفين'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='إجمالي المبلغ الإجمالي'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='إجمالي المبلغ الصافي'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='basic_salary',
            field=models.DecimalField(db_column='BasicSalary', decimal_places=2, default=django.utils.timezone.now, max_digits=18, verbose_name='الراتب الأساسي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='currency',
            field=models.CharField(db_column='Currency', default='SAR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='effective_date',
            field=models.DateField(db_column='EffectiveDate', default=django.utils.timezone.now, verbose_name='تاريخ السريان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='emp',
            field=models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='end_date',
            field=models.DateField(blank=True, db_column='EndDate', null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='gosi_deduction',
            field=models.DecimalField(db_column='GosiDeduction', decimal_places=2, default=0, max_digits=18, verbose_name='خصم التأمينات'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='housing_allow',
            field=models.DecimalField(db_column='HousingAllow', decimal_places=2, default=0, max_digits=18, verbose_name='بدل السكن'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='is_current',
            field=models.BooleanField(db_column='IsCurrent', default=True, verbose_name='ساري حالياً'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='other_allow',
            field=models.DecimalField(db_column='OtherAllow', decimal_places=2, default=0, max_digits=18, verbose_name='بدلات أخرى'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='tax_deduction',
            field=models.DecimalField(db_column='TaxDeduction', decimal_places=2, default=0, max_digits=18, verbose_name='خصم الضرائب'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='basic_salary',
            field=models.DecimalField(db_column='BasicSalary', decimal_places=2, default=django.utils.timezone.now, max_digits=18, verbose_name='الراتب الأساسي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='emp',
            field=models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='loan_deduction',
            field=models.DecimalField(db_column='LoanDeduction', decimal_places=2, default=0, max_digits=18, verbose_name='خصم القروض'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='net_salary',
            field=models.DecimalField(db_column='NetSalary', decimal_places=2, default=0, max_digits=18, verbose_name='صافي الراتب'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='paid_date',
            field=models.DateField(blank=True, db_column='PaidDate', null=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='run',
            field=models.ForeignKey(db_column='RunID', on_delete=django.db.models.deletion.CASCADE, related_name='payroll_details', to='payrolls.payrollrun', verbose_name='تشغيل الراتب'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, db_column='ConfirmedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payrolls', to='employees.employee', verbose_name='مؤكد بواسطة'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='month_year',
            field=models.CharField(db_column='MonthYear', max_length=7, verbose_name='الشهر والسنة'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='run_date',
            field=models.DateField(db_column='RunDate', default=datetime.date.today, verbose_name='تاريخ التشغيل'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('calculating', 'جاري الحساب'), ('review', 'قيد المراجعة'), ('approved', 'معتمد'), ('paid', 'مدفوع'), ('cancelled', 'ملغى')], db_column='Status', default='draft', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterUniqueTogether(
            name='payrolldetail',
            unique_together={('run', 'emp')},
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('deduction_id', models.AutoField(primary_key=True, serialize=False)),
                ('deduction_type', models.CharField(choices=[('disciplinary', 'خصم تأديبي'), ('loan', 'خصم قرض'), ('advance', 'خصم سلفة'), ('insurance', 'خصم تأمين'), ('other', 'خصم آخر')], max_length=20, verbose_name='نوع الخصم')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('effective_date', models.DateField(verbose_name='تاريخ السريان')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='متكرر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deductions', to='employees.employee', verbose_name='معتمد بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'خصم موظف',
                'verbose_name_plural': 'خصومات الموظفين',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollBonus',
            fields=[
                ('bonus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bonus_type', models.CharField(choices=[('performance', 'مكافأة أداء'), ('annual', 'مكافأة سنوية'), ('project', 'مكافأة مشروع'), ('attendance', 'مكافأة حضور'), ('special', 'مكافأة خاصة')], max_length=20, verbose_name='نوع المكافأة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('effective_date', models.DateField(verbose_name='تاريخ السريان')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='متكررة')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='خاضعة للضريبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bonuses', to='employees.employee', verbose_name='معتمد بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مكافأة موظف',
                'verbose_name_plural': 'مكافآت الموظفين',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='gosi',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='housing',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='overtime',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='transport',
        ),
    ]
