from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from dateutil.relativedelta import relativedelta

# ================================================================
# 1) جدول الشركات والفروع
# ================================================================
class SetupCompany(models.Model):
    # Company_ID is auto-generated by Django
    company_code = models.CharField(_('كود الشركة'), max_length=10, unique=True)
    company_name_ar = models.CharField(_('اسم الشركة (عربي)'), max_length=100)
    company_name_en = models.CharField(_('اسم الشركة (إنجليزي)'), max_length=100, null=True, blank=True)
    commercial_record = models.CharField(_('السجل التجاري'), max_length=50, null=True, blank=True)
    tax_number = models.CharField(_('الرقم الضريبي'), max_length=30, null=True, blank=True)
    phone1 = models.CharField(_('هاتف 1'), max_length=20, null=True, blank=True)
    phone2 = models.CharField(_('هاتف 2'), max_length=20, null=True, blank=True)
    email = models.EmailField(_('البريد الإلكتروني'), max_length=100, null=True, blank=True)
    website = models.URLField(_('الموقع الإلكتروني'), max_length=100, null=True, blank=True)
    country = models.CharField(_('الدولة'), max_length=50, null=True, blank=True)
    governorate = models.CharField(_('المحافظة'), max_length=50, null=True, blank=True)
    city = models.CharField(_('المدينة'), max_length=50, null=True, blank=True)
    district = models.CharField(_('الحي'), max_length=50, null=True, blank=True)
    street = models.CharField(_('الشارع'), max_length=100, null=True, blank=True)
    building_no = models.CharField(_('رقم المبنى'), max_length=20, null=True, blank=True)
    logo = models.ImageField(_('الشعار'), upload_to='company_logos/', null=True, blank=True) # Changed VARBINARY(MAX) to ImageField
    is_active = models.BooleanField(_('نشط'), default=True)
    
    # Tracking fields (Using Django's built-in User for Created_By/Modified_By)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='companies_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='companies_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('شركة')
        verbose_name_plural = _('الشركات')
        db_table = 'Setup_Company'

    def __str__(self):
        return self.company_name_ar

# ================================================================
# 4) جدول الموظفين الأساسي (مقدم على الأقسام والوظائف لحل مشكلة التبعية الدائرية)
# ================================================================
class HREmployee(models.Model):
    GENDER_CHOICES = [
        ('M', _('ذكر')),
        ('F', _('أنثى')),
    ]
    MARITAL_STATUS_CHOICES = [
        ('Single', _('أعزب')),
        ('Married', _('متزوج')),
        ('Divorced', _('مطلق')),
        ('Widowed', _('أرمل')),
    ]

    emp_code = models.CharField(_('كود الموظف'), max_length=20, unique=True)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_('حساب المستخدم')) # Linking to Django User
    
    # Arabic Names
    first_name_ar = models.CharField(_('الاسم الأول (عربي)'), max_length=50)
    second_name_ar = models.CharField(_('الاسم الثاني (عربي)'), max_length=50)
    third_name_ar = models.CharField(_('الاسم الثالث (عربي)'), max_length=50, null=True, blank=True)
    last_name_ar = models.CharField(_('الاسم الأخير (عربي)'), max_length=50)

    # English Names
    first_name_en = models.CharField(_('الاسم الأول (إنجليزي)'), max_length=50, null=True, blank=True)
    second_name_en = models.CharField(_('الاسم الثاني (إنجليزي)'), max_length=50, null=True, blank=True)
    third_name_en = models.CharField(_('الاسم الثالث (إنجليزي)'), max_length=50, null=True, blank=True)
    last_name_en = models.CharField(_('الاسم الأخير (إنجليزي)'), max_length=50, null=True, blank=True)

    date_birth = models.DateField(_('تاريخ الميلاد'), null=True, blank=True)
    gender = models.CharField(_('النوع'), max_length=1, choices=GENDER_CHOICES, null=True, blank=True)
    nationality = models.CharField(_('الجنسية'), max_length=50, null=True, blank=True)
    national_id = models.CharField(_('الرقم القومي'), max_length=14, null=True, blank=True, db_index=True) # Added db_index for IX_Emp_NationalID
    personal_id_expiry = models.DateField(_('تاريخ انتهاء الهوية'), null=True, blank=True)
    marital_status = models.CharField(_('الحالة الاجتماعية'), max_length=30, choices=MARITAL_STATUS_CHOICES, null=True, blank=True)
    military_status = models.CharField(_('الحالة العسكرية'), max_length=30, null=True, blank=True)
    
    # Contact Info
    phone1 = models.CharField(_('هاتف 1'), max_length=20, null=True, blank=True)
    phone2 = models.CharField(_('هاتف 2'), max_length=20, null=True, blank=True)
    email_personal = models.EmailField(_('البريد الشخصي'), max_length=100, null=True, blank=True)
    email_official = models.EmailField(_('البريد الرسمي'), max_length=100, null=True, blank=True)
    
    # Address
    address_country = models.CharField(_('دولة العنوان'), max_length=50, null=True, blank=True)
    address_governorate = models.CharField(_('محافظة العنوان'), max_length=50, null=True, blank=True)
    address_city = models.CharField(_('مدينة العنوان'), max_length=50, null=True, blank=True)
    address_street = models.CharField(_('شارع العنوان'), max_length=200, null=True, blank=True)
    
    # Emergency
    emergency_contact = models.CharField(_('جهة اتصال للطوارئ'), max_length=100, null=True, blank=True)
    emergency_phone = models.CharField(_('هاتف الطوارئ'), max_length=20, null=True, blank=True)
    
    has_special_needs = models.BooleanField(_('ذوي الاحتياجات الخاصة'), default=False)
    notes = models.TextField(_('ملاحظات'), max_length=500, null=True, blank=True)
    is_active = models.BooleanField(_('نشط'), default=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='employees_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='employees_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('موظف')
        verbose_name_plural = _('الموظفين')
        db_table = 'HR_Employee'

    @property
    def full_name_ar(self):
        # Computed column logic
        name = f"{self.first_name_ar} {self.second_name_ar}"
        if self.third_name_ar:
            name += f" {self.third_name_ar}"
        name += f" {self.last_name_ar}"
        return name.strip()

    @property
    def full_name_en(self):
        # Computed column logic
        name = f"{self.first_name_en or ''} {self.second_name_en or ''}"
        if self.third_name_en:
            name += f" {self.third_name_en}"
        name += f" {self.last_name_en or ''}"
        return name.strip()

    def __str__(self):
        return f"{self.emp_code} - {self.full_name_ar}"

# ================================================================
# 2) جدول الأقسام الرئيسية والفرعية
# ================================================================
class SetupDepartment(models.Model):
    company = models.ForeignKey(SetupCompany, on_delete=models.CASCADE, verbose_name=_('الشركة'))
    parent_dept = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_('القسم الرئيسي'))
    dept_code = models.CharField(_('كود القسم'), max_length=20)
    dept_name_ar = models.CharField(_('اسم القسم (عربي)'), max_length=100)
    dept_name_en = models.CharField(_('اسم القسم (إنجليزي)'), max_length=100, null=True, blank=True)
    manager_emp = models.ForeignKey(HREmployee, on_delete=models.SET_NULL, null=True, blank=True, related_name='managed_department', verbose_name=_('مدير القسم'))
    is_active = models.BooleanField(_('نشط'), default=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='departments_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='departments_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('قسم')
        verbose_name_plural = _('الأقسام')
        unique_together = ('company', 'dept_code')
        db_table = 'Setup_Department'

    def __str__(self):
        return f"{self.dept_name_ar} ({self.company.company_name_ar})"

# ================================================================
# 3) جدول الوظائف
# ================================================================
class SetupJob(models.Model):
    company = models.ForeignKey(SetupCompany, on_delete=models.CASCADE, verbose_name=_('الشركة'))
    job_code = models.CharField(_('كود الوظيفة'), max_length=20)
    job_name_ar = models.CharField(_('اسم الوظيفة (عربي)'), max_length=100)
    job_name_en = models.CharField(_('اسم الوظيفة (إنجليزي)'), max_length=100, null=True, blank=True)
    job_description = models.TextField(_('الوصف الوظيفي'), max_length=500, null=True, blank=True)
    min_salary = models.DecimalField(_('الحد الأدنى للراتب'), max_digits=18, decimal_places=2, null=True, blank=True)
    max_salary = models.DecimalField(_('الحد الأقصى للراتب'), max_digits=18, decimal_places=2, null=True, blank=True)
    is_active = models.BooleanField(_('نشط'), default=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='jobs_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='jobs_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('وظيفة')
        verbose_name_plural = _('الوظائف')
        unique_together = ('company', 'job_code')
        db_table = 'Setup_Job'

    def __str__(self):
        return self.job_name_ar

# ================================================================
# 5) جدول تعيينات الموظفين (تاريخي)
# ================================================================
class HREmployeeAssignment(models.Model):
    EMPLOYMENT_TYPE_CHOICES = [
        ('Permanent', _('دائم')),
        ('Temporary', _('مؤقت')),
        ('Contract', _('عقد')),
        ('Internship', _('تدريب')),
        ('PartTime', _('دوام جزئي')),
    ]

    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    company = models.ForeignKey(SetupCompany, on_delete=models.PROTECT, verbose_name=_('الشركة'))
    dept = models.ForeignKey(SetupDepartment, on_delete=models.PROTECT, verbose_name=_('القسم'))
    job = models.ForeignKey(SetupJob, on_delete=models.PROTECT, verbose_name=_('الوظيفة'))
    direct_manager = models.ForeignKey(HREmployee, on_delete=models.SET_NULL, null=True, blank=True, related_name='subordinates', verbose_name=_('المدير المباشر'))
    
    employment_type = models.CharField(_('نوع التوظيف'), max_length=30, choices=EMPLOYMENT_TYPE_CHOICES)
    hiring_date = models.DateField(_('تاريخ التعيين'))
    probation_months = models.IntegerField(_('أشهر التجربة'), default=3)
    
    contract_start = models.DateField(_('بداية العقد'), null=True, blank=True)
    contract_end = models.DateField(_('نهاية العقد'), null=True, blank=True)
    
    basic_salary = models.DecimalField(_('الراتب الأساسي'), max_digits=18, decimal_places=2)
    currency = models.CharField(_('العملة'), max_length=3, default='EGP')
    
    shift_type = models.CharField(_('نوع الوردية'), max_length=30, null=True, blank=True)
    current_week_shift = models.CharField(_('وردية الأسبوع الحالي'), max_length=50, null=True, blank=True)
    next_week_shift = models.CharField(_('وردية الأسبوع القادم'), max_length=50, null=True, blank=True)
    friday_operation = models.CharField(_('عمليات الجمعة'), max_length=50, null=True, blank=True)
    
    is_current = models.BooleanField(_('التعيين الحالي'), default=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='assignments_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='assignments_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('تعيين موظف')
        verbose_name_plural = _('تعيينات الموظفين')
        db_table = 'HR_Employee_Assignment'

    @property
    def probation_end_date(self):
        # Computed column logic: DATEADD(MONTH,Probation_Months,Hiring_Date)
        return self.hiring_date + relativedelta(months=self.probation_months)

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.job.job_name_ar} ({'Current' if self.is_current else 'Past'})"

# ================================================================
# 6) جدول أنواع الإجازات
# ================================================================
class SetupLeaveType(models.Model):
    PAID_UNPAID_CHOICES = [
        ('P', _('مدفوعة')),
        ('U', _('غير مدفوعة')),
    ]
    GENDER_LIMIT_CHOICES = [
        ('M', _('ذكور فقط')),
        ('F', _('إناث فقط')),
    ]

    company = models.ForeignKey(SetupCompany, on_delete=models.CASCADE, verbose_name=_('الشركة'))
    leave_code = models.CharField(_('كود الإجازة'), max_length=20)
    leave_name_ar = models.CharField(_('اسم الإجازة (عربي)'), max_length=100)
    leave_name_en = models.CharField(_('اسم الإجازة (إنجليزي)'), max_length=100, null=True, blank=True)
    paid_unpaid = models.CharField(_('مدفوعة/غير مدفوعة'), max_length=1, choices=PAID_UNPAID_CHOICES)
    max_days_year = models.IntegerField(_('الحد الأقصى سنوياً'))
    carry_forward = models.BooleanField(_('ترحيل الرصيد'), default=False)
    max_carry = models.IntegerField(_('الحد الأقصى للترحيل'), null=True, blank=True)
    gender_limit = models.CharField(_('قيد النوع'), max_length=1, choices=GENDER_LIMIT_CHOICES, null=True, blank=True)
    is_active = models.BooleanField(_('نشط'), default=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='leave_types_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='leave_types_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('نوع إجازة')
        verbose_name_plural = _('أنواع الإجازات')
        unique_together = ('company', 'leave_code')
        db_table = 'Setup_Leave_Type'

    def __str__(self):
        return self.leave_name_ar

# ================================================================
# 7) رصيد الإجازات السنوي للموظف
# ================================================================
class HREmpLeaveBalance(models.Model):
    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    leave_type = models.ForeignKey(SetupLeaveType, on_delete=models.PROTECT, verbose_name=_('نوع الإجازة'))
    year = models.IntegerField(_('السنة'))
    opening_balance = models.IntegerField(_('الرصيد الافتتاحي'))
    consumed_days = models.IntegerField(_('الأيام المستهلكة'), default=0)
    carry_forward_days = models.IntegerField(_('أيام مرحلة'), default=0)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='leave_balances_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='leave_balances_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('رصيد إجازة')
        verbose_name_plural = _('أرصدة الإجازات')
        unique_together = ('emp', 'leave_type', 'year')
        db_table = 'HR_Emp_Leave_Balance'

    @property
    def remaining_balance(self):
        # Computed column logic: Opening_Balance - Consumed_Days
        return self.opening_balance - self.consumed_days

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.leave_type.leave_name_ar} ({self.year})"

# ================================================================
# 8) طلبات/سجلات الإجازات
# ================================================================
class HREmpLeaveRequest(models.Model):
    STATUS_CHOICES = [
        ('Pending', _('قيد الانتظار')),
        ('Approved', _('موافق عليه')),
        ('Rejected', _('مرفوض')),
        ('Cancelled', _('ملغي')),
    ]

    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    leave_type = models.ForeignKey(SetupLeaveType, on_delete=models.PROTECT, verbose_name=_('نوع الإجازة'))
    start_date = models.DateField(_('تاريخ البداية'))
    end_date = models.DateField(_('تاريخ النهاية'))
    days_count = models.IntegerField(_('عدد الأيام'))
    reason = models.TextField(_('السبب'), max_length=500, null=True, blank=True)
    status = models.CharField(_('الحالة'), max_length=20, choices=STATUS_CHOICES, default='Pending')
    
    # Approval fields
    approved_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='leaves_approved', verbose_name=_('تمت الموافقة بواسطة'))
    approval_date = models.DateTimeField(_('تاريخ الموافقة'), null=True, blank=True)
    
    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='leave_requests_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='leave_requests_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('طلب إجازة')
        verbose_name_plural = _('طلبات الإجازات')
        db_table = 'HR_Emp_Leave_Request'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.leave_type.leave_name_ar} ({self.start_date})"

# ================================================================
# 9) سجل الحضور والانصراف
# ================================================================
class HREmpAttendance(models.Model):
    ATTENDANCE_TYPE_CHOICES = [
        ('In', _('دخول')),
        ('Out', _('خروج')),
        ('BreakStart', _('بداية استراحة')),
        ('BreakEnd', _('نهاية استراحة')),
    ]

    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    attendance_datetime = models.DateTimeField(_('التاريخ والوقت'))
    attendance_type = models.CharField(_('النوع'), max_length=10, choices=ATTENDANCE_TYPE_CHOICES)
    device_id = models.CharField(_('جهاز البصمة'), max_length=50, null=True, blank=True)
    location = models.CharField(_('الموقع'), max_length=100, null=True, blank=True)
    
    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='attendances_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='attendances_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('سجل حضور')
        verbose_name_plural = _('سجلات الحضور والانصراف')
        db_table = 'HR_Emp_Attendance'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.get_attendance_type_display()} at {self.attendance_datetime.strftime('%Y-%m-%d %H:%M')}"

# ================================================================
# 10) جدول عناصر الرواتب (استحقاقات وخصومات)
# ================================================================
class SetupPayrollItem(models.Model):
    ITEM_TYPE_CHOICES = [
        ('E', _('استحقاق')),
        ('D', _('خصم')),
    ]

    company = models.ForeignKey(SetupCompany, on_delete=models.CASCADE, verbose_name=_('الشركة'))
    item_code = models.CharField(_('كود العنصر'), max_length=20)
    item_name_ar = models.CharField(_('اسم العنصر (عربي)'), max_length=100)
    item_name_en = models.CharField(_('اسم العنصر (إنجليزي)'), max_length=100, null=True, blank=True)
    item_type = models.CharField(_('النوع'), max_length=1, choices=ITEM_TYPE_CHOICES)
    is_taxable = models.BooleanField(_('خاضع للضريبة'), default=True)
    is_active = models.BooleanField(_('نشط'), default=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='payroll_items_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='payroll_items_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('عنصر راتب')
        verbose_name_plural = _('عناصر الرواتب')
        unique_together = ('company', 'item_code')
        db_table = 'Setup_Payroll_Item'

    def __str__(self):
        return self.item_name_ar

# ================================================================
# 11) مكونات راتب الموظف الثابتة
# ================================================================
class HREmpSalaryComponent(models.Model):
    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    payroll_item = models.ForeignKey(SetupPayrollItem, on_delete=models.PROTECT, verbose_name=_('عنصر الراتب'))
    amount = models.DecimalField(_('المبلغ'), max_digits=18, decimal_places=2)
    is_fixed = models.BooleanField(_('ثابت شهرياً'), default=True)
    start_date = models.DateField(_('تاريخ البداية'))
    end_date = models.DateField(_('تاريخ النهاية'), null=True, blank=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='salary_components_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='salary_components_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('مكون راتب')
        verbose_name_plural = _('مكونات رواتب الموظفين')
        db_table = 'HR_Emp_Salary_Component'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.payroll_item.item_name_ar}: {self.amount}"

# ================================================================
# 12) دورة تشغيل الرواتب
# ================================================================
class HRPayrollRun(models.Model):
    STATUS_CHOICES = [
        ('Draft', _('مسودة')),
        ('Calculated', _('محسوب')),
        ('Approved', _('معتمد')),
        ('Paid', _('مدفوع')),
    ]

    company = models.ForeignKey(SetupCompany, on_delete=models.PROTECT, verbose_name=_('الشركة'))
    payroll_month = models.IntegerField(_('الشهر'))
    payroll_year = models.IntegerField(_('السنة'))
    run_date = models.DateTimeField(_('تاريخ التشغيل'), auto_now_add=True)
    status = models.CharField(_('الحالة'), max_length=20, choices=STATUS_CHOICES, default='Draft')
    total_net_salary = models.DecimalField(_('إجمالي صافي الرواتب'), max_digits=18, decimal_places=2, default=0)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='payroll_runs_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='payroll_runs_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('دورة رواتب')
        verbose_name_plural = _('دورات تشغيل الرواتب')
        unique_together = ('company', 'payroll_month', 'payroll_year')
        db_table = 'HR_Payroll_Run'

    def __str__(self):
        return f"{self.company.company_name_ar} - {self.payroll_month}/{self.payroll_year} ({self.get_status_display()})"

# ================================================================
# 13) كشف الراتب (تفاصيل الراتب لكل موظف)
# ================================================================
class HRPayrollSlip(models.Model):
    payroll_run = models.ForeignKey(HRPayrollRun, on_delete=models.CASCADE, verbose_name=_('دورة الرواتب'))
    emp = models.ForeignKey(HREmployee, on_delete=models.PROTECT, verbose_name=_('الموظف'))
    payroll_item = models.ForeignKey(SetupPayrollItem, on_delete=models.PROTECT, verbose_name=_('عنصر الراتب'))
    amount = models.DecimalField(_('المبلغ'), max_digits=18, decimal_places=2)
    
    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='payroll_slips_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='payroll_slips_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('كشف راتب')
        verbose_name_plural = _('كشوف الرواتب')
        db_table = 'HR_Payroll_Slip'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.payroll_item.item_name_ar} ({self.payroll_run})"

# ================================================================
# 14) مؤهلات الموظفين
# ================================================================
class HREmpQualification(models.Model):
    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    degree = models.CharField(_('الدرجة العلمية'), max_length=100)
    major = models.CharField(_('التخصص'), max_length=100)
    institution = models.CharField(_('المؤسسة التعليمية'), max_length=100)
    graduation_year = models.IntegerField(_('سنة التخرج'))
    grade = models.CharField(_('التقدير'), max_length=50, null=True, blank=True)
    
    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='qualifications_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='qualifications_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('مؤهل علمي')
        verbose_name_plural = _('مؤهلات الموظفين')
        db_table = 'HR_Emp_Qualification'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.degree} ({self.institution})"

# ================================================================
# 15) تدريب الموظفين
# ================================================================
class HREmpTraining(models.Model):
    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    training_name = models.CharField(_('اسم التدريب'), max_length=100)
    provider = models.CharField(_('مقدم التدريب'), max_length=100)
    start_date = models.DateField(_('تاريخ البداية'))
    end_date = models.DateField(_('تاريخ النهاية'))
    duration_hours = models.IntegerField(_('مدة التدريب (ساعة)'), null=True, blank=True)
    certificate_file = models.FileField(_('ملف الشهادة'), upload_to='training_certificates/', null=True, blank=True)
    
    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='trainings_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='trainings_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('تدريب')
        verbose_name_plural = _('تدريب الموظفين')
        db_table = 'HR_Emp_Training'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.training_name}"

# ================================================================
# 16) وثائق الموظفين
# ================================================================
class HREmpDocument(models.Model):
    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    document_type = models.CharField(_('نوع الوثيقة'), max_length=100)
    document_number = models.CharField(_('رقم الوثيقة'), max_length=50, null=True, blank=True)
    issue_date = models.DateField(_('تاريخ الإصدار'), null=True, blank=True)
    expiry_date = models.DateField(_('تاريخ الانتهاء'), null=True, blank=True)
    document_file = models.FileField(_('ملف الوثيقة'), upload_to='employee_documents/', null=True, blank=True)
    
    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='documents_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='documents_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('وثيقة موظف')
        verbose_name_plural = _('وثائق الموظفين')
        db_table = 'HR_Emp_Document'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.document_type}"

# ================================================================
# 17) أنواع الأصول
# ================================================================
class SetupAssetType(models.Model):
    company = models.ForeignKey(SetupCompany, on_delete=models.CASCADE, verbose_name=_('الشركة'))
    asset_code = models.CharField(_('كود الأصل'), max_length=20)
    asset_name_ar = models.CharField(_('اسم الأصل (عربي)'), max_length=100)
    asset_name_en = models.CharField(_('اسم الأصل (إنجليزي)'), max_length=100, null=True, blank=True)
    is_active = models.BooleanField(_('نشط'), default=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='asset_types_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='asset_types_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('نوع أصل')
        verbose_name_plural = _('أنواع الأصول')
        unique_together = ('company', 'asset_code')
        db_table = 'Setup_Asset_Type'

    def __str__(self):
        return self.asset_name_ar

# ================================================================
# 18) أصول الموظفين (عهد)
# ================================================================
class HREmpAsset(models.Model):
    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    asset_type = models.ForeignKey(SetupAssetType, on_delete=models.PROTECT, verbose_name=_('نوع الأصل'))
    serial_number = models.CharField(_('الرقم التسلسلي'), max_length=100, unique=True)
    assigned_date = models.DateField(_('تاريخ التسليم'))
    return_date = models.DateField(_('تاريخ الإرجاع'), null=True, blank=True)
    notes = models.TextField(_('ملاحظات'), max_length=500, null=True, blank=True)
    
    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='assets_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='assets_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('أصل موظف')
        verbose_name_plural = _('أصول الموظفين (عهد)')
        db_table = 'HR_Emp_Asset'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.asset_type.asset_name_ar} ({self.serial_number})"

# ================================================================
# 19) دورات تقييم الأداء
# ================================================================
class HRAppraisalCycle(models.Model):
    company = models.ForeignKey(SetupCompany, on_delete=models.CASCADE, verbose_name=_('الشركة'))
    cycle_name = models.CharField(_('اسم الدورة'), max_length=100)
    start_date = models.DateField(_('تاريخ البداية'))
    end_date = models.DateField(_('تاريخ النهاية'))
    is_active = models.BooleanField(_('نشط'), default=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='appraisal_cycles_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='appraisal_cycles_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('دورة تقييم')
        verbose_name_plural = _('دورات تقييم الأداء')
        db_table = 'HR_Appraisal_Cycle'

    def __str__(self):
        return self.cycle_name

# ================================================================
# 20) تقييمات الموظفين
# ================================================================
class HREmpAppraisal(models.Model):
    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    cycle = models.ForeignKey(HRAppraisalCycle, on_delete=models.PROTECT, verbose_name=_('دورة التقييم'))
    appraiser = models.ForeignKey(HREmployee, on_delete=models.SET_NULL, null=True, blank=True, related_name='appraisals_given', verbose_name=_('المقيّم'))
    appraisal_date = models.DateField(_('تاريخ التقييم'))
    overall_score = models.DecimalField(_('النتيجة الإجمالية'), max_digits=5, decimal_places=2, null=True, blank=True)
    comments = models.TextField(_('تعليقات'), max_length=1000, null=True, blank=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='appraisals_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='appraisals_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('تقييم موظف')
        verbose_name_plural = _('تقييمات الموظفين')
        unique_together = ('emp', 'cycle')
        db_table = 'HR_Emp_Appraisal'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.cycle.cycle_name}"

# ================================================================
# 21) العقود
# ================================================================
class HRContract(models.Model):
    CONTRACT_TYPE_CHOICES = [
        ('Limited', _('محدد المدة')),
        ('Unlimited', _('غير محدد المدة')),
    ]
    STATUS_CHOICES = [
        ('Draft', _('مسودة')),
        ('Signed', _('موقع')),
        ('Cancelled', _('ملغي')),
        ('Expired', _('منتهي')),
    ]

    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    contract_no = models.CharField(_('رقم العقد'), max_length=30, unique=True)
    contract_type = models.CharField(_('نوع العقد'), max_length=30, choices=CONTRACT_TYPE_CHOICES, null=True, blank=True)
    start_date = models.DateField(_('تاريخ البداية'))
    end_date = models.DateField(_('تاريخ النهاية'), null=True, blank=True)
    duration_months = models.IntegerField(_('مدة العقد (أشهر)'), null=True, blank=True)
    renewal_count = models.IntegerField(_('عدد مرات التجديد'), default=0)
    salary_basic = models.DecimalField(_('الراتب الأساسي'), max_digits=18, decimal_places=2)
    salary_gross = models.DecimalField(_('إجمالي الراتب'), max_digits=18, decimal_places=2)
    notice_period_days = models.IntegerField(_('أيام فترة الإشعار'), null=True, blank=True)
    probation_period = models.IntegerField(_('فترة التجربة (أيام)'), null=True, blank=True)
    status = models.CharField(_('الحالة'), max_length=20, choices=STATUS_CHOICES, null=True, blank=True)
    file_attachment = models.FileField(_('ملف العقد'), upload_to='contracts/', null=True, blank=True) # Changed VARBINARY(MAX) to FileField

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='contracts_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='contracts_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('عقد')
        verbose_name_plural = _('العقود')
        db_table = 'HR_Contract'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.contract_no}"

# ================================================================
# 22) أنواع الجزاءات والمخالفات
# ================================================================
class SetupViolationType(models.Model):
    PENALTY_TYPE_CHOICES = [
        ('Warning', _('إنذار')),
        ('Deduction', _('خصم')),
        ('Suspend', _('إيقاف عن العمل')),
    ]

    company = models.ForeignKey(SetupCompany, on_delete=models.CASCADE, verbose_name=_('الشركة'))
    violation_code = models.CharField(_('كود المخالفة'), max_length=20)
    violation_name = models.CharField(_('اسم المخالفة'), max_length=100)
    penalty_type = models.CharField(_('نوع الجزاء'), max_length=30, choices=PENALTY_TYPE_CHOICES, null=True, blank=True)
    penalty_days = models.IntegerField(_('أيام الجزاء'), null=True, blank=True)
    penalty_amount = models.DecimalField(_('مبلغ الجزاء'), max_digits=18, decimal_places=2, null=True, blank=True)
    is_active = models.BooleanField(_('نشط'), default=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='violation_types_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='violation_types_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('نوع مخالفة')
        verbose_name_plural = _('أنواع المخالفات')
        unique_together = ('company', 'violation_code')
        db_table = 'Setup_Violation_Type'

    def __str__(self):
        return self.violation_name

# ================================================================
# 23) سجل جزاءات الموظفين
# ================================================================
class HREmpViolation(models.Model):
    emp = models.ForeignKey(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    violation_type = models.ForeignKey(SetupViolationType, on_delete=models.PROTECT, verbose_name=_('نوع المخالفة'))
    violation_date = models.DateField(_('تاريخ المخالفة'))
    details = models.TextField(_('التفاصيل'), max_length=500, null=True, blank=True)
    penalty_executed = models.BooleanField(_('تم تنفيذ الجزاء'), default=False)
    executed_date = models.DateTimeField(_('تاريخ التنفيذ'), null=True, blank=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='violations_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='violations_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('جزاء موظف')
        verbose_name_plural = _('جزاءات الموظفين')
        db_table = 'HR_Emp_Violation'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.violation_type.violation_name} ({self.violation_date})"

# ================================================================
# 24) التأمينات الاجتماعية
# ================================================================
class HRSocialInsurance(models.Model):
    emp = models.OneToOneField(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    insurance_no = models.CharField(_('رقم التأمين'), max_length=30, unique=True, null=True, blank=True)
    form_s1_received = models.BooleanField(_('استلام نموذج س1'), default=False)
    form_s1_date = models.DateField(_('تاريخ س1'), null=True, blank=True)
    form_s6_received = models.BooleanField(_('استلام نموذج س6'), default=False)
    form_s6_date = models.DateField(_('تاريخ س6'), null=True, blank=True)
    subscription_date = models.DateField(_('تاريخ الاشتراك'), null=True, blank=True)
    subscription_salary = models.DecimalField(_('أجر الاشتراك التأميني'), max_digits=18, decimal_places=2, null=True, blank=True)
    employee_percent = models.DecimalField(_('نسبة الموظف'), max_digits=5, decimal_places=2, null=True, blank=True)
    company_percent = models.DecimalField(_('نسبة الشركة'), max_digits=5, decimal_places=2, null=True, blank=True)
    status = models.CharField(_('الحالة'), max_length=20, null=True, blank=True)
    exit_date = models.DateField(_('تاريخ الخروج'), null=True, blank=True)
    exit_reason = models.CharField(_('سبب الخروج'), max_length=100, null=True, blank=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='social_insurances_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='social_insurances_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('تأمين اجتماعي')
        verbose_name_plural = _('التأمينات الاجتماعية')
        db_table = 'HR_Social_Insurance'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.insurance_no or 'N/A'}"

# ================================================================
# 25) التأمين الصحي
# ================================================================
class HRHealthInsurance(models.Model):
    emp = models.OneToOneField(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    provider = models.CharField(_('مزود الخدمة'), max_length=100, null=True, blank=True)
    policy_no = models.CharField(_('رقم البوليصة'), max_length=30, null=True, blank=True)
    card_no = models.CharField(_('رقم البطاقة'), max_length=30, null=True, blank=True)
    start_date = models.DateField(_('تاريخ البداية'), null=True, blank=True)
    end_date = models.DateField(_('تاريخ النهاية'), null=True, blank=True)
    insurance_job_code = models.CharField(_('كود الوظيفة التأميني'), max_length=20, null=True, blank=True)
    insurance_job_name = models.CharField(_('اسم الوظيفة التأميني'), max_length=100, null=True, blank=True)
    premium_amount = models.DecimalField(_('قيمة القسط'), max_digits=18, decimal_places=2, null=True, blank=True)
    notes = models.TextField(_('ملاحظات'), max_length=200, null=True, blank=True)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='health_insurances_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='health_insurances_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('تأمين صحي')
        verbose_name_plural = _('التأمينات الصحية')
        db_table = 'HR_Health_Insurance'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.provider or 'N/A'}"

# ================================================================
# 26) العطلات الرسمية
# ================================================================
class SetupHoliday(models.Model):
    company = models.ForeignKey(SetupCompany, on_delete=models.CASCADE, verbose_name=_('الشركة'))
    holiday_date = models.DateField(_('التاريخ'))
    holiday_name_ar = models.CharField(_('اسم العطلة (عربي)'), max_length=100)
    holiday_name_en = models.CharField(_('اسم العطلة (إنجليزي)'), max_length=100, null=True, blank=True)
    is_recurring = models.BooleanField(_('متكررة سنوياً'), default=False)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='holidays_created')
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('عطلة رسمية')
        verbose_name_plural = _('العطلات الرسمية')
        unique_together = ('company', 'holiday_date')
        db_table = 'Setup_Holiday'

    def __str__(self):
        return f"{self.holiday_name_ar} ({self.holiday_date})"

# ================================================================
# 27) إنهاء الخدمة / استقالة
# ================================================================
class HRTermination(models.Model):
    REASON_TYPE_CHOICES = [
        ('Resignation', _('استقالة')),
        ('EndOfContract', _('انتهاء عقد')),
        ('Termination', _('إنهاء خدمة')),
    ]

    emp = models.OneToOneField(HREmployee, on_delete=models.CASCADE, verbose_name=_('الموظف'))
    request_date = models.DateField(_('تاريخ الطلب'))
    last_working_date = models.DateField(_('آخر يوم عمل'))
    reason_type = models.CharField(_('نوع السبب'), max_length=30, choices=REASON_TYPE_CHOICES, null=True, blank=True)
    reason_details = models.TextField(_('تفاصيل السبب'), max_length=500, null=True, blank=True)
    notice_period_days = models.IntegerField(_('أيام فترة الإشعار'), null=True, blank=True)
    notice_end_date = models.DateField(_('تاريخ انتهاء الإشعار'), null=True, blank=True)
    settlement_amount = models.DecimalField(_('مبلغ التسوية'), max_digits=18, decimal_places=2, null=True, blank=True)
    settlement_paid = models.BooleanField(_('تم دفع التسوية'), default=False)

    # Tracking fields
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='terminations_created')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='terminations_modified')
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('إنهاء خدمة')
        verbose_name_plural = _('إنهاءات الخدمة')
        db_table = 'HR_Termination'

    def __str__(self):
        return f"{self.emp.full_name_ar} - {self.get_reason_type_display()}"
