# Generated by Django 4.2.7 on 2025-08-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('holiday_id', models.AutoField(db_column='HolidayID', primary_key=True, serialize=False)),
                ('holiday_date', models.DateField(db_column='HolidayDate')),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'عطلة رسمية',
                'verbose_name_plural': 'العطلات الرسمية',
                'db_table': 'PublicHolidays',
            },
        ),
    ]
