# Generated by Django 4.2.30 on 2026-04-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0003_rename_tasks_status_031d4c_idx_core_tasks_status_db8e28_idx_and_more",
        ),
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavepolicy",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_policies",
                to="core.department",
                verbose_name="القسم",
            ),
        ),
    ]
