# Generated by Django 4.2.7 on 2025-08-17 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employeebankaccount_bank_id_and_more'),
        ('leaves', '0002_publicholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الطلب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='can_carry_forward',
            field=models.BooleanField(default=False, verbose_name='يمكن ترحيلها للسنة التالية'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_approval',
            field=models.BooleanField(default=True, verbose_name='تتطلب موافقة'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='عطلة متكررة سنوياً'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='ApprovedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employees.employee', verbose_name='معتمد من'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='approved_date',
            field=models.DateTimeField(blank=True, db_column='ApprovedDate', null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='emp',
            field=models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='end_date',
            field=models.DateField(db_column='EndDate', verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_type',
            field=models.ForeignKey(db_column='LeaveTypeID', on_delete=django.db.models.deletion.PROTECT, to='leaves.leavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='reason',
            field=models.TextField(blank=True, db_column='Reason', null=True, verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='start_date',
            field=models.DateField(db_column='StartDate', verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='status',
            field=models.CharField(choices=[('Pending', 'في الانتظار'), ('Approved', 'معتمدة'), ('Rejected', 'مرفوضة'), ('Cancelled', 'ملغاة')], db_column='Status', default='Pending', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(db_column='IsPaid', default=False, verbose_name='إجازة مدفوعة الأجر'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(db_column='LeaveName', max_length=100, verbose_name='اسم نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.IntegerField(blank=True, db_column='MaxDaysPerYear', null=True, verbose_name='الحد الأقصى للأيام سنوياً'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=255, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='holiday_date',
            field=models.DateField(db_column='HolidayDate', verbose_name='تاريخ العطلة'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeleave',
            unique_together={('emp', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('holiday_date',)},
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('allocated_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='الأيام المخصصة')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='الأيام المستخدمة')),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='الأيام المرحلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'رصيد إجازة',
                'verbose_name_plural': 'أرصدة الإجازات',
                'unique_together': {('emp', 'leave_type', 'year')},
            },
        ),
    ]
