# Generated by Django 4.2.22 on 2025-08-29 02:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employeebankaccount_bank_id_and_more'),
        ('org', '0002_branch_company'),
        ('leaves', '0003_employeeleave_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['sort_order', 'leave_name'], 'verbose_name': 'نوع إجازة', 'verbose_name_plural': 'أنواع الإجازات'},
        ),
        migrations.AddField(
            model_name='leavetype',
            name='accrual_frequency',
            field=models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي'), ('on_hire', 'عند التعيين')], default='yearly', max_length=20, verbose_name='تكرار الاستحقاق'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='accrual_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='معدل الاستحقاق'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='affects_attendance',
            field=models.BooleanField(default=True, verbose_name='تؤثر على الحضور'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='calculation_method',
            field=models.CharField(choices=[('days', 'بالأيام'), ('hours', 'بالساعات'), ('half_days', 'بأنصاف الأيام')], default='days', max_length=20, verbose_name='طريقة الحساب'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='color_code',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='لون العرض'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='excludes_holidays',
            field=models.BooleanField(default=True, verbose_name='استثناء العطل الرسمية'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='gender_specific',
            field=models.CharField(choices=[('all', 'جميع الموظفين'), ('male', 'ذكور فقط'), ('female', 'إناث فقط')], default='all', max_length=10, verbose_name='خاص بالجنس'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='leave_code',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='رمز الإجازة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_carry_forward_days',
            field=models.IntegerField(default=0, verbose_name='الحد الأقصى للترحيل'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='minimum_service_months',
            field=models.IntegerField(default=0, verbose_name='الحد الأدنى للخدمة (بالشهور)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_medical_certificate',
            field=models.BooleanField(default=False, verbose_name='تتطلب شهادة طبية'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(db_column='IsPaid', default=True, verbose_name='إجازة مدفوعة الأجر'),
        ),
        migrations.CreateModel(
            name='LeaveWorkflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_order', models.IntegerField(verbose_name='ترتيب الخطوة')),
                ('approver_role', models.CharField(max_length=50, verbose_name='دور المعتمد')),
                ('is_required', models.BooleanField(default=True, verbose_name='إجباري')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='الشروط')),
                ('approver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف المعتمد')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'سير عمل الإجازة',
                'verbose_name_plural': 'سير عمل الإجازات',
                'ordering': ['leave_type', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('duration_days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='عدد الأيام')),
                ('reason', models.TextField(verbose_name='سبب الإجازة')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='جهة الاتصال في حالة الطوارئ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى'), ('expired', 'منتهي الصلاحية')], default='draft', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/', verbose_name='مرفق')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaves.leavetype', verbose_name='نوع الإجازة')),
                ('replacement_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_for', to='employees.employee', verbose_name='الموظف البديل')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='employees.employee', verbose_name='مراجع من')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=100, verbose_name='اسم السياسة')),
                ('min_service_years', models.IntegerField(default=0, verbose_name='الحد الأدنى لسنوات الخدمة')),
                ('max_consecutive_days', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للأيام المتتالية')),
                ('advance_notice_days', models.IntegerField(default=0, verbose_name='عدد أيام الإشعار المسبق')),
                ('blackout_start_date', models.DateField(blank=True, null=True, verbose_name='بداية فترة الحظر')),
                ('blackout_end_date', models.DateField(blank=True, null=True, verbose_name='نهاية فترة الحظر')),
                ('requires_replacement', models.BooleanField(default=False, verbose_name='تتطلب بديل')),
                ('max_pending_requests', models.IntegerField(default=1, verbose_name='الحد الأقصى للطلبات المعلقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org.department', verbose_name='القسم')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org.job', verbose_name='المنصب')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'سياسة إجازة',
                'verbose_name_plural': 'سياسات الإجازات',
            },
        ),
        migrations.CreateModel(
            name='LeaveApprovalStep',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('skipped', 'متجاوز')], default='pending', max_length=20, verbose_name='الحالة')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='تعليقات')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='المعتمد')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='leaves.leaverequest', verbose_name='طلب الإجازة')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leaveworkflow', verbose_name='خطوة سير العمل')),
            ],
            options={
                'verbose_name': 'خطوة اعتماد',
                'verbose_name_plural': 'خطوات الاعتماد',
                'ordering': ['workflow_step__step_order'],
            },
        ),
        migrations.CreateModel(
            name='LeaveQuota',
            fields=[
                ('quota_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('total_quota', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='إجمالي الحصة')),
                ('used_quota', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='الحصة المستخدمة')),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='المرحل من العام السابق')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'حصة إجازة',
                'verbose_name_plural': 'حصص الإجازات',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveCalendar',
            fields=[
                ('calendar_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='عطلة رسمية')),
                ('is_weekend', models.BooleanField(default=False, verbose_name='عطلة نهاية أسبوع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'تقويم إجازة',
                'verbose_name_plural': 'تقويم الإجازات',
                'ordering': ['date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
