version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eldawliya_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "True"
      DB_NAME: "ElDawliya_Sys"
      DB_USER: "admin"
      DB_PASSWORD: "hgslduhgfwdv"
      DB_HOST: "db"
      DB_PORT: "1433"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eldawliya_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "hgslduhgfwdv"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
