# Generated by Django 5.2.8 on 2025-12-17 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='meetings', through='core.MeetingAttendee', through_fields=('meeting', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='الحضور'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(related_name='projects', through='core.ProjectMember', through_fields=('project', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='أعضاء الفريق'),
        ),
    ]
