# Generated by Django 5.2.8 on 2026-02-07 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_meeting_attendees_alter_project_team_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='core_tasks_status_db8e28_idx',
            old_name='tasks_status_031d4c_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_tasks_priorit_7bda85_idx',
            old_name='tasks_priorit_a9efa1_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_tasks_assigne_f0326d_idx',
            old_name='tasks_assigne_00feb5_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_tasks_project_ce6256_idx',
            old_name='tasks_project_f1bd77_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_tasks_due_dat_3754f0_idx',
            old_name='tasks_due_dat_0359a9_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_tasks_task_ty_10bcd7_idx',
            old_name='tasks_task_ty_7bc323_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_tasks_status_50a9b3_idx',
            old_name='tasks_status_a6382a_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_tasks_project_24740f_idx',
            old_name='tasks_project_fe19a5_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مكلف إلى'),
        ),
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_tasks', to='core.projectmilestone', verbose_name='المعلم'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_subtasks', to='core.task', verbose_name='المهمة الأب'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_tasks', to='core.projectphase', verbose_name='المرحلة'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_tasks', to='core.project', verbose_name='المشروع'),
        ),
        migrations.AlterModelTable(
            name='task',
            table='core_tasks',
        ),
    ]
