# Generated by Django 4.2.26 on 2025-12-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "bank_id",
                    models.AutoField(
                        db_column="BankID", primary_key=True, serialize=False
                    ),
                ),
                ("bank_name", models.CharField(db_column="BankName", max_length=150)),
                (
                    "swift_code",
                    models.CharField(
                        blank=True, db_column="SwiftCode", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "بنك",
                "verbose_name_plural": "البنوك",
                "db_table": "Banks",
            },
        ),
    ]
