# Generated by Django 4.2.26 on 2025-12-16 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationPeriod",
            fields=[
                (
                    "period_id",
                    models.AutoField(
                        db_column="PeriodID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "period_name",
                    models.CharField(
                        db_column="PeriodName",
                        max_length=100,
                        verbose_name="اسم الفترة",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_column="StartDate", verbose_name="تاريخ البداية"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(db_column="EndDate", verbose_name="تاريخ النهاية"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="IsActive", default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="CreatedAt",
                        verbose_name="تاريخ الإنشاء",
                    ),
                ),
            ],
            options={
                "verbose_name": "فترة تقييم",
                "verbose_name_plural": "فترات التقييم",
                "db_table": "EvaluationPeriods",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeEvaluation",
            fields=[
                (
                    "eval_id",
                    models.AutoField(
                        db_column="EvalID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(
                        blank=True,
                        db_column="ManagerID",
                        null=True,
                        verbose_name="المدير المقيم",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        db_column="Score",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="الدرجة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, db_column="Notes", null=True, verbose_name="ملاحظات"
                    ),
                ),
                (
                    "eval_date",
                    models.DateField(
                        blank=True,
                        db_column="EvalDate",
                        null=True,
                        verbose_name="تاريخ التقييم",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("submitted", "مقدم"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        db_column="Status",
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="CreatedAt",
                        verbose_name="تاريخ الإنشاء",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="UpdatedAt",
                        verbose_name="تاريخ التحديث",
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="EmpID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        db_column="PeriodID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="evaluations.evaluationperiod",
                        verbose_name="فترة التقييم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم موظف",
                "verbose_name_plural": "تقييمات الموظفين",
                "db_table": "EmployeeEvaluations",
                "ordering": ["-eval_date", "-created_at"],
                "unique_together": {("emp", "period")},
            },
        ),
    ]
