# Generated by Django 4.2.7 on 2025-08-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPeriod',
            fields=[
                ('period_id', models.AutoField(db_column='PeriodID', primary_key=True, serialize=False)),
                ('period_name', models.CharField(db_column='PeriodName', max_length=100)),
                ('start_date', models.DateField(db_column='StartDate')),
                ('end_date', models.DateField(db_column='EndDate')),
            ],
            options={
                'verbose_name': 'فترة تقييم',
                'verbose_name_plural': 'فترات التقييم',
                'db_table': 'EvaluationPeriods',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('eval_id', models.AutoField(db_column='EvalID', primary_key=True, serialize=False)),
                ('manager_id', models.IntegerField(blank=True, db_column='ManagerID', null=True)),
                ('score', models.DecimalField(blank=True, db_column='Score', decimal_places=2, max_digits=5, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=1000, null=True)),
                ('eval_date', models.DateField(blank=True, db_column='EvalDate', null=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('period', models.ForeignKey(db_column='PeriodID', on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationperiod')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'تقييمات الموظفين',
                'db_table': 'EmployeeEvaluations',
            },
        ),
    ]
