# Generated by Django 4.2.22 on 2025-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0003_zkdevice_attendanceprocessinglog_zkattendanceraw_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="zkdevice",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="Asia/Riyadh",
                max_length=50,
                verbose_name="المنطقة الزمنية",
            ),
        ),
    ]
