# Generated by Django 4.2.26 on 2025-12-16 16:52

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollCalculationRule",
            fields=[
                ("rule_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rule_name",
                    models.CharField(max_length=100, verbose_name="اسم القاعدة"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("overtime", "وقت إضافي"),
                            ("deduction", "خصم"),
                            ("bonus", "مكافأة"),
                            ("tax", "ضريبة"),
                        ],
                        max_length=20,
                        verbose_name="نوع القاعدة",
                    ),
                ),
                ("formula", models.TextField(verbose_name="معادلة الحساب")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "قاعدة حساب راتب",
                "verbose_name_plural": "قواعد حساب الرواتب",
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "run_id",
                    models.AutoField(
                        db_column="RunID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "run_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم التشغيل"
                    ),
                ),
                (
                    "payroll_type",
                    models.CharField(
                        choices=[
                            ("monthly", "شهري"),
                            ("bi_weekly", "نصف شهري"),
                            ("weekly", "أسبوعي"),
                            ("bonus", "مكافآت"),
                            ("final_settlement", "تصفية نهائية"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="نوع الراتب",
                    ),
                ),
                (
                    "run_date",
                    models.DateField(
                        db_column="RunDate",
                        default=datetime.date.today,
                        verbose_name="تاريخ التشغيل",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="بداية الفترة")),
                ("period_end", models.DateField(verbose_name="نهاية الفترة")),
                (
                    "month_year",
                    models.CharField(
                        db_column="MonthYear", max_length=7, verbose_name="الشهر والسنة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("calculating", "جاري الحساب"),
                            ("review", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("paid", "مدفوع"),
                            ("cancelled", "ملغى"),
                        ],
                        db_column="Status",
                        default="draft",
                        max_length=30,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "total_employees",
                    models.IntegerField(default=0, verbose_name="إجمالي الموظفين"),
                ),
                (
                    "processed_employees",
                    models.IntegerField(default=0, verbose_name="الموظفين المعالجين"),
                ),
                (
                    "total_gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="إجمالي المبلغ الإجمالي",
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="إجمالي الخصومات",
                    ),
                ),
                (
                    "total_net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="إجمالي المبلغ الصافي",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التأكيد"
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات المعالجة"
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        default="attendance_based",
                        max_length=50,
                        verbose_name="طريقة الحساب",
                    ),
                ),
                (
                    "include_overtime",
                    models.BooleanField(
                        default=True, verbose_name="تضمين الوقت الإضافي"
                    ),
                ),
                (
                    "include_bonuses",
                    models.BooleanField(default=True, verbose_name="تضمين المكافآت"),
                ),
                (
                    "include_deductions",
                    models.BooleanField(default=True, verbose_name="تضمين الخصومات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payrolls",
                        to="employees.employee",
                        verbose_name="معتمد بواسطة",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="ConfirmedBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_payrolls",
                        to="employees.employee",
                        verbose_name="مؤكد بواسطة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payrolls",
                        to="employees.employee",
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تشغيل راتب",
                "verbose_name_plural": "تشغيلات الرواتب",
                "db_table": "PayrollRuns",
                "ordering": ["-run_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollDeduction",
            fields=[
                ("deduction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "deduction_type",
                    models.CharField(
                        choices=[
                            ("disciplinary", "خصم تأديبي"),
                            ("loan", "خصم قرض"),
                            ("advance", "خصم سلفة"),
                            ("insurance", "خصم تأمين"),
                            ("other", "خصم آخر"),
                        ],
                        max_length=20,
                        verbose_name="نوع الخصم",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="المبلغ"
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                ("effective_date", models.DateField(verbose_name="تاريخ السريان")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="متكرر"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_deductions",
                        to="employees.employee",
                        verbose_name="معتمد بواسطة",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "خصم موظف",
                "verbose_name_plural": "خصومات الموظفين",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollBonus",
            fields=[
                ("bonus_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("performance", "مكافأة أداء"),
                            ("annual", "مكافأة سنوية"),
                            ("project", "مكافأة مشروع"),
                            ("attendance", "مكافأة حضور"),
                            ("special", "مكافأة خاصة"),
                        ],
                        max_length=20,
                        verbose_name="نوع المكافأة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="المبلغ"
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                ("effective_date", models.DateField(verbose_name="تاريخ السريان")),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="متكررة"),
                ),
                (
                    "is_taxable",
                    models.BooleanField(default=True, verbose_name="خاضعة للضريبة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_bonuses",
                        to="employees.employee",
                        verbose_name="معتمد بواسطة",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "مكافأة موظف",
                "verbose_name_plural": "مكافآت الموظفين",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                (
                    "salary_id",
                    models.AutoField(
                        db_column="SalaryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("monthly", "شهري"),
                            ("hourly", "بالساعة"),
                            ("daily", "يومي"),
                            ("project", "مشروع"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="نوع الراتب",
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        db_column="BasicSalary",
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="الراتب الأساسي",
                    ),
                ),
                (
                    "housing_allow",
                    models.DecimalField(
                        db_column="HousingAllow",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="بدل السكن",
                    ),
                ),
                (
                    "transport_allow",
                    models.DecimalField(
                        db_column="Transport",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="بدل المواصلات",
                    ),
                ),
                (
                    "food_allow",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="بدل الطعام",
                    ),
                ),
                (
                    "mobile_allow",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="بدل الهاتف",
                    ),
                ),
                (
                    "other_allow",
                    models.DecimalField(
                        db_column="OtherAllow",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="بدلات أخرى",
                    ),
                ),
                (
                    "gosi_deduction",
                    models.DecimalField(
                        db_column="GosiDeduction",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصم التأمينات",
                    ),
                ),
                (
                    "tax_deduction",
                    models.DecimalField(
                        db_column="TaxDeduction",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصم الضرائب",
                    ),
                ),
                (
                    "insurance_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصم التأمين الطبي",
                    ),
                ),
                (
                    "other_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصومات أخرى",
                    ),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.5"),
                        max_digits=5,
                        verbose_name="معدل الوقت الإضافي",
                    ),
                ),
                (
                    "weekend_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.0"),
                        max_digits=5,
                        verbose_name="معدل عمل نهاية الأسبوع",
                    ),
                ),
                (
                    "holiday_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.5"),
                        max_digits=5,
                        verbose_name="معدل عمل العطل",
                    ),
                ),
                (
                    "deduct_unpaid_leave",
                    models.BooleanField(
                        default=True, verbose_name="خصم الإجازات غير مدفوعة الأجر"
                    ),
                ),
                (
                    "deduct_late_minutes",
                    models.BooleanField(default=True, verbose_name="خصم دقائق التأخير"),
                ),
                (
                    "deduct_absent_days",
                    models.BooleanField(default=True, verbose_name="خصم أيام الغياب"),
                ),
                (
                    "currency",
                    models.CharField(
                        db_column="Currency",
                        default="SAR",
                        max_length=3,
                        verbose_name="العملة",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        db_column="EffectiveDate", verbose_name="تاريخ السريان"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        db_column="EndDate",
                        null=True,
                        verbose_name="تاريخ الانتهاء",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_column="IsCurrent", default=True, verbose_name="ساري حالياً"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_salaries",
                        to="employees.employee",
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="EmpID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "راتب موظف",
                "verbose_name_plural": "رواتب الموظفين",
                "db_table": "EmployeeSalaries",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollDetail",
            fields=[
                (
                    "payroll_detail_id",
                    models.AutoField(
                        db_column="PayrollDetailID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        db_column="BasicSalary",
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="الراتب الأساسي",
                    ),
                ),
                (
                    "housing_allowance",
                    models.DecimalField(
                        db_column="Housing",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="بدل السكن",
                    ),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(
                        db_column="Transport",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="بدل المواصلات",
                    ),
                ),
                (
                    "food_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="بدل الطعام",
                    ),
                ),
                (
                    "mobile_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="بدل الهاتف",
                    ),
                ),
                (
                    "other_allowances",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="بدلات أخرى",
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="ساعات إضافية",
                    ),
                ),
                (
                    "overtime_amount",
                    models.DecimalField(
                        db_column="Overtime",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="مبلغ الوقت الإضافي",
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="مكافآت",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="عمولة"
                    ),
                ),
                (
                    "worked_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="أيام العمل",
                    ),
                ),
                (
                    "absent_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="أيام الغياب",
                    ),
                ),
                (
                    "leave_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="أيام الإجازة",
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(default=0, verbose_name="دقائق التأخير"),
                ),
                (
                    "gosi_deduction",
                    models.DecimalField(
                        db_column="GOSI",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصم التأمينات",
                    ),
                ),
                (
                    "tax_deduction",
                    models.DecimalField(
                        db_column="Tax",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصم الضرائب",
                    ),
                ),
                (
                    "insurance_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصم التأمين الطبي",
                    ),
                ),
                (
                    "loan_deduction",
                    models.DecimalField(
                        db_column="LoanDeduction",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصم القروض",
                    ),
                ),
                (
                    "absence_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصم الغياب",
                    ),
                ),
                (
                    "late_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصم التأخير",
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="خصومات أخرى",
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="إجمالي الراتب",
                    ),
                ),
                (
                    "total_allowances",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="إجمالي البدلات",
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="إجمالي الخصومات",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        db_column="NetSalary",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="صافي الراتب",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="تم المعالجة"),
                ),
                (
                    "calculation_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات الحساب"
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True,
                        db_column="PaidDate",
                        null=True,
                        verbose_name="تاريخ الدفع",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="EmpID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        db_column="RunID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_details",
                        to="payroll.payrollrun",
                        verbose_name="تشغيل الراتب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفصيل راتب",
                "verbose_name_plural": "تفاصيل الرواتب",
                "db_table": "PayrollDetails",
                "ordering": ["emp__emp_code"],
                "unique_together": {("run", "emp")},
            },
        ),
    ]
