# Generated by Django 4.2.26 on 2025-12-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("banks", "0001_initial"),
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "emp_id",
                    models.AutoField(
                        db_column="EmpID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "emp_code",
                    models.CharField(db_column="EmpCode", max_length=20, unique=True),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, db_column="FirstName", max_length=100, null=True
                    ),
                ),
                (
                    "second_name",
                    models.CharField(
                        blank=True, db_column="SecondName", max_length=100, null=True
                    ),
                ),
                (
                    "third_name",
                    models.CharField(
                        blank=True, db_column="ThirdName", max_length=100, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_column="LastName", max_length=100, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "ذكر"), ("F", "أنثى")],
                        db_column="Gender",
                        max_length=1,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        db_column="BirthDate",
                        null=True,
                        verbose_name="تاريخ الميلاد",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        db_column="Nationality",
                        max_length=50,
                        null=True,
                        verbose_name="الجنسية",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        db_column="NationalID",
                        max_length=20,
                        null=True,
                        verbose_name="رقم الهوية الوطنية",
                    ),
                ),
                (
                    "passport_no",
                    models.CharField(
                        blank=True,
                        db_column="PassportNo",
                        max_length=20,
                        null=True,
                        verbose_name="رقم جواز السفر",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        db_column="Mobile",
                        max_length=50,
                        null=True,
                        verbose_name="الجوال",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_column="Email",
                        max_length=100,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_column="Address",
                        max_length=500,
                        null=True,
                        verbose_name="العنوان",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True,
                        db_column="HireDate",
                        null=True,
                        verbose_name="تاريخ التوظيف",
                    ),
                ),
                (
                    "join_date",
                    models.DateField(
                        blank=True,
                        db_column="JoinDate",
                        null=True,
                        verbose_name="تاريخ الالتحاق",
                    ),
                ),
                (
                    "probation_end",
                    models.DateField(
                        blank=True,
                        db_column="ProbationEnd",
                        null=True,
                        verbose_name="تاريخ انتهاء فترة التجربة",
                    ),
                ),
                (
                    "emp_status",
                    models.CharField(
                        choices=[
                            ("Active", "نشط"),
                            ("Inactive", "غير نشط"),
                            ("Terminated", "منتهي الخدمة"),
                            ("Suspended", "معلق"),
                            ("On Leave", "في إجازة"),
                        ],
                        db_column="EmpStatus",
                        default="Active",
                        max_length=30,
                        verbose_name="حالة الموظف",
                    ),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True,
                        db_column="TerminationDate",
                        null=True,
                        verbose_name="تاريخ إنهاء الخدمة",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        db_column="Notes",
                        max_length=500,
                        null=True,
                        verbose_name="ملاحظات",
                    ),
                ),
                (
                    "photo",
                    models.BinaryField(
                        blank=True,
                        db_column="Photo",
                        null=True,
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="CreatedAt",
                        verbose_name="تاريخ الإنشاء",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="UpdatedAt",
                        verbose_name="تاريخ التحديث",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        db_column="BranchID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="org.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        db_column="DeptID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="org.department",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        db_column="JobID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="org.job",
                        verbose_name="الوظيفة",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        db_column="ManagerID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="employees.employee",
                        verbose_name="المدير المباشر",
                    ),
                ),
            ],
            options={
                "verbose_name": "موظف",
                "verbose_name_plural": "الموظفون",
                "db_table": "Employees",
                "ordering": ["emp_code"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "doc_id",
                    models.AutoField(
                        db_column="DocID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("ID", "بطاقة الهوية"),
                            ("PASSPORT", "جواز السفر"),
                            ("CONTRACT", "عقد العمل"),
                            ("CERTIFICATE", "شهادة"),
                            ("MEDICAL", "تقرير طبي"),
                            ("OTHER", "أخرى"),
                        ],
                        db_column="DocType",
                        max_length=100,
                        verbose_name="نوع المستند",
                    ),
                ),
                (
                    "doc_name",
                    models.CharField(
                        blank=True,
                        db_column="DocName",
                        max_length=255,
                        null=True,
                        verbose_name="اسم المستند",
                    ),
                ),
                (
                    "file_data",
                    models.BinaryField(
                        blank=True,
                        db_column="FileData",
                        null=True,
                        verbose_name="بيانات الملف",
                    ),
                ),
                (
                    "file_ext",
                    models.CharField(
                        blank=True,
                        db_column="FileExt",
                        max_length=10,
                        null=True,
                        verbose_name="امتداد الملف",
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="UploadDate",
                        verbose_name="تاريخ الرفع",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ انتهاء الصلاحية"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        db_column="Notes",
                        max_length=500,
                        null=True,
                        verbose_name="ملاحظات",
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="EmpID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستند",
                "verbose_name_plural": "مستندات الموظفين",
                "db_table": "EmployeeDocuments",
                "ordering": ["-upload_date"],
                "indexes": [
                    models.Index(
                        fields=["emp", "doc_type"], name="EmployeeDoc_EmpID_c4c71f_idx"
                    ),
                    models.Index(
                        fields=["emp", "is_active"], name="EmployeeDoc_EmpID_79dfd7_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="EmployeeDoc_expiry__340b88_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeBankAccount",
            fields=[
                (
                    "acc_id",
                    models.AutoField(
                        db_column="AccID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "account_no",
                    models.CharField(
                        blank=True,
                        db_column="AccountNo",
                        max_length=50,
                        null=True,
                        verbose_name="رقم الحساب",
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True,
                        db_column="IBAN",
                        max_length=50,
                        null=True,
                        verbose_name="رقم الآيبان",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="الحساب الأساسي"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        db_column="BankID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_accounts",
                        to="banks.bank",
                        verbose_name="البنك",
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="EmpID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب بنكي",
                "verbose_name_plural": "حسابات الموظفين البنكية",
                "db_table": "EmployeeBankAccounts",
                "ordering": ["-is_primary", "bank__bank_name"],
                "indexes": [
                    models.Index(
                        fields=["emp", "is_primary"],
                        name="EmployeeBan_EmpID_ead9b8_idx",
                    ),
                    models.Index(
                        fields=["emp", "is_active"], name="EmployeeBan_EmpID_73e901_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["emp_status"], name="Employees_EmpStat_ac9bf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["dept", "emp_status"], name="Employees_DeptID_a8d9f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["branch", "emp_status"], name="Employees_BranchI_be970c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["hire_date"], name="Employees_HireDat_121a2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["manager"], name="Employees_Manager_259e4d_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["emp_code"], name="Employees_EmpCode_646634_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["email"], name="Employees_Email_49388d_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["national_id"], name="Employees_Nationa_f6979a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["created_at"], name="Employees_Created_bc53be_idx"
            ),
        ),
    ]
