# Generated by Django 4.2.7 on 2025-08-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(db_column='EmpID', primary_key=True, serialize=False)),
                ('emp_code', models.CharField(db_column='EmpCode', max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=100, null=True)),
                ('second_name', models.CharField(blank=True, db_column='SecondName', max_length=100, null=True)),
                ('third_name', models.CharField(blank=True, db_column='ThirdName', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=100, null=True)),
                ('gender', models.CharField(db_column='Gender', max_length=1)),
                ('birth_date', models.DateField(blank=True, db_column='BirthDate', null=True)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=50, null=True)),
                ('national_id', models.CharField(blank=True, db_column='NationalID', max_length=20, null=True)),
                ('passport_no', models.CharField(blank=True, db_column='PassportNo', max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=500, null=True)),
                ('hire_date', models.DateField(blank=True, db_column='HireDate', null=True)),
                ('join_date', models.DateField(blank=True, db_column='JoinDate', null=True)),
                ('probation_end', models.DateField(blank=True, db_column='ProbationEnd', null=True)),
                ('emp_status', models.CharField(db_column='EmpStatus', default='Active', max_length=30)),
                ('termination_date', models.DateField(blank=True, db_column='TerminationDate', null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500, null=True)),
                ('photo', models.BinaryField(blank=True, db_column='Photo', max_length='max', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('branch', models.ForeignKey(db_column='BranchID', on_delete=django.db.models.deletion.PROTECT, to='org.branch')),
                ('dept', models.ForeignKey(db_column='DeptID', on_delete=django.db.models.deletion.PROTECT, to='org.department')),
                ('job', models.ForeignKey(db_column='JobID', on_delete=django.db.models.deletion.PROTECT, to='org.job')),
                ('manager', models.ForeignKey(blank=True, db_column='ManagerID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('doc_id', models.AutoField(db_column='DocID', primary_key=True, serialize=False)),
                ('doc_type', models.CharField(db_column='DocType', max_length=100)),
                ('doc_name', models.CharField(blank=True, db_column='DocName', max_length=255, null=True)),
                ('file_data', models.BinaryField(blank=True, db_column='FileData', max_length='max', null=True)),
                ('file_ext', models.CharField(blank=True, db_column='FileExt', max_length=10, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_column='UploadDate')),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500, null=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'مستندات الموظفين',
                'db_table': 'EmployeeDocuments',
            },
        ),
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('acc_id', models.AutoField(db_column='AccID', primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField(blank=True, db_column='BankID', null=True)),
                ('account_no', models.CharField(blank=True, db_column='AccountNo', max_length=50, null=True)),
                ('iban', models.CharField(blank=True, db_column='IBAN', max_length=50, null=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'حسابات الموظفين البنكية',
                'db_table': 'EmployeeBankAccounts',
            },
        ),
    ]
