# Generated by Django 4.2.30 on 2026-04-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0003_rename_tasks_status_031d4c_idx_core_tasks_status_db8e28_idx_and_more",
        ),
        ("employees", "0002_employeedocumentcategory_evaluationcriteria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="dept",
            field=models.ForeignKey(
                db_column="DeptID",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees_legacy",
                to="core.department",
                verbose_name="القسم",
            ),
        ),
    ]
