# Generated by Django 4.2.7 on 2025-08-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebankaccount',
            name='bank_id',
        ),
        migrations.AddField(
            model_name='employeebankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, db_column='BankID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.bank'),
        ),
    ]
