# Generated by Django 5.2.8 on 2025-12-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='supported_models',
            field=models.JSONField(default=list, help_text='قائمة النماذج المدعومة'),
        ),
    ]
