# Generated by Django 4.2.7 on 2025-08-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysSetting',
            fields=[
                ('setting_id', models.AutoField(db_column='SettingID', primary_key=True, serialize=False)),
                ('setting_key', models.CharField(db_column='SettingKey', max_length=100, unique=True)),
                ('setting_value', models.CharField(blank=True, db_column='SettingValue', max_length=500, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'إعداد',
                'verbose_name_plural': 'الإعدادات',
                'db_table': 'SysSettings',
            },
        ),
    ]
