# Generated by Django 4.2.7 on 2025-08-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('asset_name', models.CharField(db_column='AssetName', max_length=150)),
                ('serial_no', models.CharField(blank=True, db_column='SerialNo', max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, db_column='PurchaseDate', null=True)),
                ('purchase_price', models.DecimalField(blank=True, db_column='PurchasePrice', decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(db_column='Status', default='Available', max_length=30)),
            ],
            options={
                'verbose_name': 'أصل',
                'verbose_name_plural': 'الأصول',
                'db_table': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='CategoryName', max_length=100)),
            ],
            options={
                'verbose_name': 'تصنيف أصل',
                'verbose_name_plural': 'تصنيفات الأصول',
                'db_table': 'AssetCategories',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('emp_asset_id', models.AutoField(db_column='EmpAssetID', primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(blank=True, db_column='AssignedDate', null=True)),
                ('return_date', models.DateField(blank=True, db_column='ReturnDate', null=True)),
                ('condition_notes', models.CharField(blank=True, db_column='ConditionNotes', max_length=500, null=True)),
                ('asset', models.ForeignKey(db_column='AssetID', on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'أصل موظف',
                'verbose_name_plural': 'أصول الموظفين',
                'db_table': 'EmployeeAssets',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, db_column='CategoryID', null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory'),
        ),
    ]
