# Generated by Django 5.0.14 on 2025-04-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Esta migración no hace nada porque las tablas ya existen en la base de datos
        migrations.RunSQL(
            sql='-- No hacer nada, las tablas ya existen',
            reverse_sql='-- No hacer nada en la reversión'
        )
    ]
