# Generated by Django 5.0.14 on 2025-05-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_image',
            field=models.BinaryField(blank=True, db_column='Emp_Image', editable=True, max_length='max', null=True, verbose_name='صورة الموظف'),
        ),
    ]
