# Generated by Django 5.0.14 on 2025-04-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeetask',
            table=None,
        ),
    ]
