# Generated by Django 5.0.14 on 2025-04-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0004_create_employeetask_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeenote',
            table=None,
        ),
    ]
