# Generated by Django 5.0.14 on 2025-04-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0006_create_employeenote_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeefile',
            table=None,
        ),
    ]
