# Generated by Django 5.0.14 on 2025-04-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0008_create_employeefile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hrtask',
            table=None,
        ),
    ]
