# Generated by Django 5.0.14 on 2025-07-09 14:10
# This migration adds the LegacyEmployee model which maps to the existing Tbl_Employee table
# The model is marked as unmanaged (managed=False) so Django doesn't try to create/modify the table

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0009_attendancerule_hrattendancemachine_hrattendancerule_and_more'),
    ]

    operations = [
        # No operations needed - LegacyEmployee model is unmanaged and maps to existing table
    ]
