# Generated by Django 5.0.14 on 2025-07-15 06:15
# Fixed migration to create the missing Tbl_Jop table and sync Django model state

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0012_merge_20250714_1927'),
    ]

    operations = [
        # Step 1: Remove the conflicting HrJob model (state-only, no DB table to drop)
        migrations.DeleteModel(
            name='HrJob',
        ),

        # Step 2: Remove the old Job model that was pointing to non-existent Tbl_Job
        migrations.DeleteModel(
            name='Job',
        ),

        # Step 3: Create the Job model with the correct schema and create the actual table
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jop_code', models.IntegerField(db_column='Jop_Code', primary_key=True, serialize=False, verbose_name='رمز الوظيفة')),
                ('jop_name', models.CharField(db_column='Jop_Name', max_length=50, verbose_name='اسم الوظيفة')),
                ('department', models.ForeignKey(blank=True, db_column='Dept_Code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.legacydepartment', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'الوظيفة',
                'verbose_name_plural': 'الوظائف',
                'db_table': 'Tbl_Jop',
                'managed': True,
            },
        ),
    ]
