# Generated by Django 5.0.14 on 2025-07-15 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0012_merge_20250714_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='note',
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(blank=True, db_column='Dept_Code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.legacydepartment', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jop_code',
            field=models.IntegerField(db_column='Jop_Code', primary_key=True, serialize=False, verbose_name='رمز الوظيفة'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jop_name',
            field=models.CharField(db_column='Jop_Name', max_length=50, verbose_name='اسم الوظيفة'),
        ),
        migrations.AlterModelTable(
            name='job',
            table='Tbl_Jop',
        ),
        migrations.DeleteModel(
            name='HrJob',
        ),
    ]
