# Generated by Django 5.0.14 on 2025-07-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0015_add_attendance_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='تاريخ الحضور (يتم حسابه تلقائياً)', verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time',
            field=models.TimeField(auto_now_add=True, help_text='وقت الحضور (يتم حسابه تلقائياً)', verbose_name='الوقت'),
        ),
    ]
