# Generated by Django 5.0.14 on 2025-04-26 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0016_merge_20240101_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True, 'verbose_name': 'الموظف', 'verbose_name_plural': 'الموظفون'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'managed': True, 'verbose_name': 'نوع الإجازة', 'verbose_name_plural': 'أنواع الإجازات'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='code',
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.CharField(blank=True, db_column='Age', max_length=100, null=True, verbose_name='العمر'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_certificate',
            field=models.BooleanField(blank=True, db_column='Birth_Certificate', null=True, verbose_name='شهادة الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='car_pick_up_point',
            field=models.CharField(blank=True, db_column='Car_Pick_Up_Point', max_length=100, null=True, verbose_name='نقطة التقاط السيارة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='car_ride_time',
            field=models.DateTimeField(blank=True, db_column='Car_Ride_Time', null=True, verbose_name='وقت ركوب السيارة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='confirm_exit_insurance',
            field=models.BooleanField(blank=True, db_column='Confirm_Exit_Insurance', null=True, verbose_name='تأكيد خروج التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='confirmation_insurance_entry',
            field=models.BooleanField(blank=True, db_column='Confirmation_Insurance_Entry', null=True, verbose_name='تأكيد دخول التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_expiry_date',
            field=models.DateField(blank=True, db_column='Contract_Expiry_Date', null=True, verbose_name='تاريخ انتهاء العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_renewal_date',
            field=models.DateField(blank=True, db_column='Contract_Renewal_Date', null=True, verbose_name='تاريخ تجديد العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_renewal_month',
            field=models.IntegerField(blank=True, db_column='Contract_Renewal_Month', null=True, verbose_name='شهر تجديد العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='criminal_record_check',
            field=models.BooleanField(blank=True, db_column='Criminal_Record_Check', null=True, verbose_name='فحص السجل الجنائي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='currentweekshift',
            field=models.CharField(blank=True, db_column='CurrentWeekShift', max_length=50, null=True, verbose_name='مناوبة الأسبوع الحالي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(blank=True, db_column='Date_Birth', null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_insurance_start',
            field=models.DateField(blank=True, db_column='Date_Insurance_Start', null=True, verbose_name='تاريخ بداية التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_resignation',
            field=models.DateField(blank=True, db_column='Date_Resignation', null=True, verbose_name='تاريخ الاستقالة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='delivery_date_s1',
            field=models.DateField(blank=True, db_column='Delivery_Date_S1', null=True, verbose_name='تاريخ تسليم S1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='delivery_date_s6',
            field=models.DateField(blank=True, db_column='Delivery_Date_S6', null=True, verbose_name='تاريخ تسليم S6'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, db_column='Dept_Code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='Hr.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dept_name',
            field=models.CharField(blank=True, db_column='Dept_Name', max_length=50, null=True, verbose_name='اسم القسم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='due_insurance_amount',
            field=models.DecimalField(blank=True, db_column='Due_Insurance_Amount', decimal_places=2, max_digits=18, null=True, verbose_name='مبلغ التأمين المستحق'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_address',
            field=models.CharField(blank=True, db_column='Emp_Address', max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_car',
            field=models.CharField(blank=True, db_column='Emp_Car', max_length=50, null=True, verbose_name='السيارة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_date_hiring',
            field=models.DateField(blank=True, db_column='Emp_Date_Hiring', null=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_first_name',
            field=models.CharField(blank=True, db_column='Emp_First_Name', max_length=50, null=True, verbose_name='الاسم الأول'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_full_name',
            field=models.CharField(blank=True, db_column='Emp_Full_Name', max_length=100, null=True, verbose_name='الاسم الكامل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(db_column='Emp_ID', default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='رقم الموظف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_image',
            field=models.BinaryField(blank=True, db_column='Emp_Image', max_length='max', null=True, verbose_name='صورة الموظف'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_marital_status',
            field=models.CharField(blank=True, choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج'), ('مطلق', 'مطلق'), ('أرمل', 'أرمل')], db_column='Emp_Marital_Status', max_length=50, null=True, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_name_english',
            field=models.CharField(blank=True, db_column='Emp_Name_English', max_length=50, null=True, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_nationality',
            field=models.CharField(blank=True, db_column='Emp_Nationality', max_length=50, null=True, verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_phone1',
            field=models.CharField(blank=True, db_column='Emp_Phone1', max_length=50, null=True, verbose_name='رقم الهاتف 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_phone2',
            field=models.CharField(blank=True, db_column='Emp_Phone2', max_length=50, null=True, verbose_name='رقم الهاتف 2'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_second_name',
            field=models.CharField(blank=True, db_column='Emp_Second_Name', max_length=50, null=True, verbose_name='الاسم الثاني'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], db_column='Emp_Type', max_length=50, null=True, verbose_name='نوع الموظف'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_contract',
            field=models.BooleanField(blank=True, db_column='Employment_Contract', null=True, verbose_name='عقد العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_date_probationary_period',
            field=models.DateField(blank=True, db_column='End_date_probationary_period', null=True, verbose_name='تاريخ انتهاء فترة الاختبار'),
        ),
        migrations.AddField(
            model_name='employee',
            name='entrance_date_s1',
            field=models.DateField(blank=True, db_column='Entrance_Date_S1', null=True, verbose_name='تاريخ دخول S1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='entrance_date_s6',
            field=models.DateField(blank=True, db_column='Entrance_Date_S6', null=True, verbose_name='تاريخ دخول S6'),
        ),
        migrations.AddField(
            model_name='employee',
            name='entrance_number_s1',
            field=models.IntegerField(blank=True, db_column='Entrance_Number_S1', null=True, verbose_name='رقم دخول S1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='entrance_number_s6',
            field=models.IntegerField(blank=True, db_column='Entrance_Number_S6', null=True, verbose_name='رقم دخول S6'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s1',
            field=models.BooleanField(blank=True, db_column='Form_S1', null=True, verbose_name='نموذج S1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s6',
            field=models.BooleanField(blank=True, db_column='Form_S6', null=True, verbose_name='نموذج S6'),
        ),
        migrations.AddField(
            model_name='employee',
            name='friday_operation',
            field=models.CharField(blank=True, db_column='Friday_Operation', max_length=50, null=True, verbose_name='عملية يوم الجمعة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='governorate',
            field=models.CharField(blank=True, db_column='Governorate', max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card',
            field=models.CharField(blank=True, choices=[('موجودة', 'موجودة'), ('غير موجوده', 'غير موجوده')], db_column='Health_Card', max_length=50, null=True, verbose_name='بطاقة صحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card_expiration_date',
            field=models.DateField(blank=True, db_column='Health_Card_Expiration_Date', null=True, verbose_name='تاريخ انتهاء البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card_number',
            field=models.IntegerField(blank=True, db_column='Health_Card_Number', null=True, verbose_name='رقم البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card_renewal_date',
            field=models.DateField(blank=True, db_column='Health_Card_Renewal_Date', null=True, verbose_name='تاريخ تجديد البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card_start_date',
            field=models.DateField(blank=True, db_column='Health_Card_Start_Date', null=True, verbose_name='تاريخ بداية البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='heel_work_number',
            field=models.IntegerField(blank=True, db_column='Heel_Work_Number', null=True, verbose_name='رقم كعب العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='heel_work_recipient',
            field=models.CharField(blank=True, db_column='Heel_Work_Recipient', max_length=50, null=True, verbose_name='مستلم كعب العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='heel_work_recipient_address',
            field=models.CharField(blank=True, db_column='Heel_Work_Recipient_Address', max_length=50, null=True, verbose_name='عنوان مستلم كعب العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='heel_work_registration_date',
            field=models.DateField(blank=True, db_column='Heel_Work_Registration_Date', null=True, verbose_name='تاريخ تسجيل كعب العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hiring_date_health_card',
            field=models.DateField(blank=True, db_column='Hiring_Date_Health_Card', null=True, verbose_name='تاريخ تعيين البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_card_photo',
            field=models.BooleanField(blank=True, db_column='ID_Card_Photo', null=True, verbose_name='صورة البطاقة الشخصية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_code',
            field=models.IntegerField(blank=True, db_column='Insurance_Code', null=True, verbose_name='كود التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_printout',
            field=models.BooleanField(blank=True, db_column='Insurance_Printout', null=True, verbose_name='مطبوعة التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_salary',
            field=models.DecimalField(blank=True, db_column='Insurance_Salary', decimal_places=2, max_digits=18, null=True, verbose_name='راتب التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_status',
            field=models.CharField(blank=True, choices=[('مؤمن عليه', 'مؤمن عليه'), ('غير مؤمن عليه', 'غير مؤمن عليه')], db_column='Insurance_Status', max_length=50, null=True, verbose_name='حالة التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='jop_code',
            field=models.IntegerField(blank=True, db_column='Jop_Code', null=True, verbose_name='كود الوظيفة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='jop_code_insurance',
            field=models.IntegerField(blank=True, db_column='Jop_Code_insurance', null=True, verbose_name='كود وظيفة التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='jop_name',
            field=models.CharField(blank=True, db_column='Jop_Name', max_length=50, null=True, verbose_name='اسم الوظيفة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='jop_name_insurance',
            field=models.CharField(blank=True, db_column='Jop_Name_insurance', max_length=50, null=True, verbose_name='اسم وظيفة التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_exam_form',
            field=models.BooleanField(blank=True, db_column='Medical_Exam_Form', null=True, verbose_name='استمارة الفحص الطبي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_exam_form_submission',
            field=models.BooleanField(blank=True, db_column='Medical_Exam_Form_Submission', null=True, verbose_name='تقديم استمارة الفحص الطبي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='military_service_certificate',
            field=models.CharField(blank=True, choices=[('أدى الخدمة', 'أدى الخدمة'), ('إعفاء', 'إعفاء'), ('مؤجل', 'مؤجل'), ('لم يبلغ السن', 'لم يبلغ السن')], db_column='Military_Service_Certificate', max_length=50, null=True, verbose_name='شهادة الخدمة العسكرية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, db_column='Mother_Name', max_length=50, null=True, verbose_name='اسم الأم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, db_column='National_ID', max_length=14, null=True, verbose_name='الرقم القومي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nextweekshift',
            field=models.CharField(blank=True, db_column='NextWeekShift', max_length=50, null=True, verbose_name='مناوبة الأسبوع القادم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='number_insurance',
            field=models.IntegerField(blank=True, db_column='Number_Insurance', null=True, verbose_name='رقم التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='people_with_special_needs',
            field=models.BooleanField(blank=True, db_column='People_With_Special_Needs', null=True, verbose_name='ذوي الاحتياجات الخاصة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='percentage_insurance_payable',
            field=models.DecimalField(blank=True, db_column='Percentage_Insurance_Payable', decimal_places=4, max_digits=18, null=True, verbose_name='نسبة التأمين المستحق'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_id_expiry_date',
            field=models.DateField(blank=True, db_column='Personal_ID_Expiry_Date', null=True, verbose_name='تاريخ انتهاء البطاقة الشخصية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_photos',
            field=models.BooleanField(blank=True, db_column='Personal_Photos', null=True, verbose_name='صور شخصية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_birth',
            field=models.CharField(blank=True, db_column='Place_Birth', max_length=50, null=True, verbose_name='محل الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification_certificate',
            field=models.CharField(blank=True, db_column='Qualification_Certificate', max_length=50, null=True, verbose_name='شهادة المؤهل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reason_resignation',
            field=models.CharField(blank=True, db_column='Reason_Resignation', max_length=100, null=True, verbose_name='سبب الاستقالة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='receive_date_s1',
            field=models.DateField(blank=True, db_column='Receive_Date_S1', null=True, verbose_name='تاريخ استلام S1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='receive_date_s6',
            field=models.DateField(blank=True, db_column='Receive_Date_S6', null=True, verbose_name='تاريخ استلام S6'),
        ),
        migrations.AddField(
            model_name='employee',
            name='remaining_contract_renewal',
            field=models.IntegerField(blank=True, db_column='Remaining_Contract_Renewal', null=True, verbose_name='تجديد العقد المتبقي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_paper',
            field=models.CharField(blank=True, db_column='Shift_paper', max_length=50, null=True, verbose_name='ورقة الشيفت'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('صباحي', 'صباحي'), ('مسائي', 'مسائي'), ('ليلي', 'ليلي')], db_column='Shift_Type', max_length=50, null=True, verbose_name='نوع المناوبة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skill_level_measurement_certificate',
            field=models.BooleanField(blank=True, db_column='Skill_level_measurement_certificate', null=True, verbose_name='شهادة قياس مستوى المهارة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_status_report',
            field=models.BooleanField(blank=True, db_column='Social_Status_Report', null=True, verbose_name='تقرير الحالة الاجتماعية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='the_health_card_remains_expire',
            field=models.IntegerField(blank=True, db_column='The_health_card_remains_expire', null=True, verbose_name='المتبقي لانتهاء البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_heel',
            field=models.BooleanField(blank=True, db_column='Work_Heel', null=True, verbose_name='كعب العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_condition',
            field=models.CharField(blank=True, choices=[('سارى', 'سارى'), ('إجازة', 'إجازة'), ('استقالة', 'استقالة'), ('انقطاع عن العمل', 'انقطاع عن العمل')], db_column='Working_Condition', max_length=50, null=True, verbose_name='حالة العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='years_since_contract_start',
            field=models.CharField(blank=True, db_column='Years_Since_Contract_Start', max_length=100, null=True, verbose_name='السنوات منذ بداية العقد'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='affects_salary',
            field=models.BooleanField(default=False, verbose_name='يؤثر على الراتب'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='مدفوع الأجر'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.PositiveIntegerField(default=0, help_text='0 يعني غير محدود', verbose_name='الحد الأقصى للأيام في السنة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Tbl_Employee',
        ),
    ]
