# Generated by Django 5.0.14 on 2025-04-26 14:21 - Modified to fix migration issue

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0016_merge_20240101_0001'),
    ]

    operations = [
        # Check if tables already exist and do nothing if they do
        migrations.RunSQL(
            """
            -- This is a no-op SQL statement that will be executed safely
            SELECT 1;
            """,
            reverse_sql="""
            SELECT 1;
            """
        ),

    ]
