# Generated by Django 5.0.14 on 2025-07-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0018_legacyemployee_hrattendancemachine_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hrjob',
            table='Tbl_Legacy_Jop',
        ),
    ]
