# Generated by Django 5.0.14 on 2025-05-05 15:08 - Modified to fix migration issue

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0021_taskstep'),
    ]

    operations = [
        # Check if tables already exist and do nothing if they do
        migrations.RunSQL(
            """
            -- This is a no-op SQL statement that will be executed safely
            SELECT 1;
            """,
            reverse_sql="""
            SELECT 1;
            """
        ),
    ]
