# Generated by Django 5.0.14 on 2025-07-23 23:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0023_remove_employeetraining_approved_by_and_more'),
        ('accounts', '0002_remove_users_login_new_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrEmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('days_count', models.PositiveIntegerField(verbose_name='عدد الأيام')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إجازة الموظف',
                'verbose_name_plural': 'إجازات الموظفين',
                'db_table': 'Hr_EmployeeLeave',
                'ordering': ['-start_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HrEmployeeSalaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='القيمة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'بند راتب موظف',
                'verbose_name_plural': 'بنود رواتب الموظفين',
                'ordering': ['employee', 'salary_item'],
            },
        ),
        migrations.CreateModel(
            name='HrLeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('affects_salary', models.BooleanField(default=False, verbose_name='يؤثر على الراتب')),
                ('is_paid', models.BooleanField(default=True, verbose_name='مدفوع الأجر')),
                ('max_days_per_year', models.PositiveIntegerField(default=0, help_text='0 يعني غير محدود', verbose_name='الحد الأقصى للأيام في السنة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نوع الإجازة',
                'verbose_name_plural': 'أنواع الإجازات',
                'db_table': 'Hr_LeaveType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HrPayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='إجمالي المبلغ')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('paid', 'مدفوع')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سجل راتب',
                'verbose_name_plural': 'سجلات الرواتب',
                'ordering': ['-period__period', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='HrPayrollItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='القيمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تفاصيل بند راتب',
                'verbose_name_plural': 'تفاصيل بنود الرواتب',
                'ordering': ['payroll_entry', 'salary_item'],
            },
        ),
        migrations.CreateModel(
            name='HrPayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='الفترة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('calculating', 'جاري الحساب'), ('completed', 'مكتمل'), ('approved', 'معتمد'), ('paid', 'مدفوع')], default='draft', max_length=20, verbose_name='الحالة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فترة راتب',
                'verbose_name_plural': 'فترات الرواتب',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='HrSalaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, unique=True, verbose_name='كود البند')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البند')),
                ('type', models.CharField(choices=[('addition', 'إضافة'), ('deduction', 'خصم')], default='addition', max_length=20, verbose_name='نوع البند')),
                ('default_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='القيمة الافتراضية')),
                ('is_auto_applied', models.BooleanField(default=False, verbose_name='تطبيق تلقائي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'بند راتب',
                'verbose_name_plural': 'بنود الرواتب',
                'ordering': ['item_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['company', 'name'], 'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['company', 'department', 'position', 'employee_id'], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='hrms_compan_is_acti_263f67_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='hrms_compan_code_c1eeb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='hrms_compan_commerc_0199dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='hrms_compan_tax_num_9ab43f_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='hrms_depart_is_acti_afdeaa_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='hrms_depart_departm_dcb9b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='hrms_depart_level_c46999_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='hrms_depart_branch__25928b_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='hrms_depart_cost_ce_a7887e_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hrms_employ_employe_78f709_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hrms_employ_email_f94efb_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hrms_employ_status_1d0e6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hrms_employ_company_091840_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hrms_employ_hire_da_7d8095_idx',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='established_date',
            new_name='founded_date',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='company',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='commercial_register',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='default_currency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='company',
            name='language',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name_english',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tax_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vat_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='confirmation_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='full_name_english',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passport_expiry',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='probation_end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_account',
        ),
        migrations.AddField(
            model_name='company',
            name='company_settings',
            field=models.JSONField(default=dict, verbose_name='إعدادات الشركة'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='EGP', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='نهاية السنة المالية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم القانوني'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي'),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='Hr.company', verbose_name='الشركة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='cost_center',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الميلاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='الرقم التعريفي للموظف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التعيين'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(default=django.utils.timezone.now, help_text='يتم تشفير هذه البيانات', max_length=20, verbose_name='رقم الجوال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.jobposition', verbose_name='الوظيفة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='private_email',
            field=models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=254, null=True, verbose_name='البريد الإلكتروني الشخصي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إنهاء الخدمة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fiscal_year_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='بداية السنة المالية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المجال'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='Hr.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود القسم'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_settings',
            field=models.JSONField(default=dict, verbose_name='إعدادات القسم'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Hr.department', verbose_name='القسم الرئيسي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=50, null=True, verbose_name='رقم الحساب البنكي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(help_text='للاتفاقية القديمة فقط', max_length=20, unique=True, verbose_name='رقم الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى'), ('O', 'أخرى')], default=django.utils.timezone.now, max_length=1, verbose_name='النوع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='iban',
            field=models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=34, null=True, verbose_name='رقم الأيبان'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='الاسم الأخير'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('S', 'أعزب'), ('M', 'متزوج'), ('D', 'مطلق'), ('W', 'أرمل')], default='S', max_length=1, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='يتم تشفير هذه البيانات', max_length=20, unique=True, verbose_name='رقم الهوية/الرقم القومي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=20, null=True, unique=True, verbose_name='رقم الجواز'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('terminated', 'منتهي الخدمة')], default='active', max_length=10, verbose_name='الحالة الوظيفية'),
        ),
        migrations.AlterField(
            model_name='hrattendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_attendance_records', to='Hr.legacyemployee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='hrattendancesummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_attendance_summaries', to='Hr.legacyemployee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='hremployeeattendancerule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='Hr.legacyemployee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='hremployeetask',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_assigned_tasks', to='accounts.users_login_new', verbose_name='تم التكليف بواسطة'),
        ),
        migrations.AlterField(
            model_name='hrtasknew',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_tasks', to='accounts.users_login_new', verbose_name='تم التكليف إلى'),
        ),
        migrations.AlterField(
            model_name='hrtasknew',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hr_tasks', to='accounts.users_login_new', verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_steps', to='accounts.users_login_new', verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'branch'], name='hrms_depart_company_e6a62c_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'status'], name='hrms_employ_company_c2f88b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='hrms_employ_employe_cfecc3_idx'),
        ),
        migrations.AddField(
            model_name='hremployeeleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='accounts.users_login_new', verbose_name='تمت الموافقة بواسطة'),
        ),
        migrations.AddField(
            model_name='hremployeeleave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='Hr.legacyemployee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='hremployeesalaryitem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_salary_items', to='Hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='hremployeeleave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves', to='Hr.hrleavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AddField(
            model_name='hrpayrollentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_payroll_entries', to='Hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='hrpayrollitemdetail',
            name='payroll_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Hr.hrpayrollentry', verbose_name='سجل الراتب'),
        ),
        migrations.AddField(
            model_name='hrpayrollperiod',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_approved_payroll_periods', to='accounts.users_login_new', verbose_name='تم الاعتماد بواسطة'),
        ),
        migrations.AddField(
            model_name='hrpayrollperiod',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_created_payroll_periods', to='accounts.users_login_new', verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AddField(
            model_name='hrpayrollentry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='Hr.hrpayrollperiod', verbose_name='فترة الراتب'),
        ),
        migrations.AddField(
            model_name='hrpayrollitemdetail',
            name='salary_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hr.hrsalaryitem', verbose_name='بند الراتب'),
        ),
        migrations.AddField(
            model_name='hremployeesalaryitem',
            name='salary_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hr.hrsalaryitem', verbose_name='بند الراتب'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='annual_budget',
        ),
        migrations.RemoveField(
            model_name='department',
            name='assistant_manager',
        ),
        migrations.RemoveField(
            model_name='department',
            name='cost_center_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='current_employees',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_type',
        ),
        migrations.RemoveField(
            model_name='department',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='department',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_profit_center',
        ),
        migrations.RemoveField(
            model_name='department',
            name='kpis',
        ),
        migrations.RemoveField(
            model_name='department',
            name='level',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
        migrations.RemoveField(
            model_name='department',
            name='max_employees',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_english',
        ),
        migrations.RemoveField(
            model_name='department',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='department',
            name='working_hours',
        ),
        migrations.AlterUniqueTogether(
            name='hrpayrollperiod',
            unique_together={('period',)},
        ),
        migrations.AlterUniqueTogether(
            name='hrpayrollentry',
            unique_together={('period', 'employee')},
        ),
    ]
