# Generated by Django 5.0.14 on 2025-05-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0009_create_employee_table'),
        ('Hr', '0024_fix_migration_dependencies'),
    ]

    operations = [
    ]
