# Generated by Django 4.2.7 on 2025-07-26 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hr', '0024_hremployeeleave_hremployeesalaryitem_hrleavetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree_type', models.CharField(choices=[('elementary', 'ابتدائية'), ('intermediate', 'متوسطة'), ('high_school', 'ثانوية عامة'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه'), ('certificate', 'شهادة مهنية'), ('training', 'دورة تدريبية')], max_length=20, verbose_name='نوع الشهادة')),
                ('major', models.CharField(max_length=200, verbose_name='التخصص')),
                ('institution', models.CharField(max_length=200, verbose_name='الجامعة/المؤسسة')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='سنة التخرج')),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='المعدل/الدرجة')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='education/certificates/', verbose_name='ملف الشهادة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='Hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مؤهل دراسي',
                'verbose_name_plural': 'المؤهلات الدراسية',
                'ordering': ['-graduation_year', 'degree_type'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insurance_type', models.CharField(choices=[('social', 'تأمين اجتماعي'), ('medical', 'تأمين صحي'), ('life', 'تأمين على الحياة'), ('disability', 'تأمين ضد العجز')], max_length=20, verbose_name='نوع التأمين')),
                ('policy_number', models.CharField(max_length=100, verbose_name='رقم البوليصة')),
                ('provider', models.CharField(max_length=200, verbose_name='مقدم التأمين')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قسط التأمين')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ التغطية')),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مساهمة الموظف')),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مساهمة صاحب العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='insurance/policies/', verbose_name='وثيقة التأمين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records', to='Hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تأمين موظف',
                'verbose_name_plural': 'تأمينات الموظفين',
                'ordering': ['employee', 'insurance_type', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('company', 'سيارة الشركة'), ('personal', 'سيارة شخصية'), ('allowance', 'بدل سيارة'), ('rental', 'سيارة مستأجرة')], max_length=20, verbose_name='نوع السيارة')),
                ('make', models.CharField(max_length=100, verbose_name='الماركة')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('year', models.PositiveIntegerField(verbose_name='سنة الصنع')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون')),
                ('assigned_date', models.DateField(verbose_name='تاريخ التخصيص')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع')),
                ('monthly_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='البدل الشهري')),
                ('insurance_expiry', models.DateField(verbose_name='تاريخ انتهاء التأمين')),
                ('registration_expiry', models.DateField(verbose_name='تاريخ انتهاء الاستمارة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_records', to='Hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سيارة موظف',
                'verbose_name_plural': 'سيارات الموظفين',
                'ordering': ['employee', '-assigned_date'],
            },
        ),
    ]
