# Generated by Django 4.2.7 on 2025-07-26 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hr', '0026_remove_employeeinsurance_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم نوع الإجازة')),
                ('name_english', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(max_length=20, verbose_name='كود نوع الإجازة')),
                ('category', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('maternity', 'إجازة أمومة'), ('paternity', 'إجازة أبوة'), ('emergency', 'إجازة طارئة'), ('study', 'إجازة دراسية'), ('pilgrimage', 'إجازة حج'), ('unpaid', 'إجازة بدون راتب'), ('compensatory', 'إجازة تعويضية'), ('other', 'أخرى')], max_length=20, verbose_name='فئة الإجازة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='لون العرض')),
                ('default_days', models.PositiveIntegerField(default=0, verbose_name='الأيام الافتراضية')),
                ('max_days_per_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى سنوياً')),
                ('max_consecutive_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى متتالي')),
                ('min_notice_days', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى للإشعار المسبق')),
                ('accrual_method', models.CharField(choices=[('monthly', 'شهرياً'), ('yearly', 'سنوياً'), ('fixed', 'ثابت'), ('none', 'لا يوجد')], default='yearly', max_length=20, verbose_name='طريقة الاستحقاق')),
                ('accrual_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل الاستحقاق')),
                ('allow_carryover', models.BooleanField(default=False, verbose_name='السماح بالترحيل')),
                ('max_carryover_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للترحيل')),
                ('carryover_expiry_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='انتهاء الترحيل (شهور)')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='يتطلب موافقة')),
                ('approval_levels', models.PositiveIntegerField(default=1, verbose_name='مستويات الموافقة')),
                ('auto_approve_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='الموافقة التلقائية للأيام')),
                ('exclude_weekends', models.BooleanField(default=True, verbose_name='استبعاد عطل نهاية الأسبوع')),
                ('exclude_holidays', models.BooleanField(default=True, verbose_name='استبعاد العطل الرسمية')),
                ('is_paid', models.BooleanField(default=True, verbose_name='مدفوعة الأجر')),
                ('gender_restriction', models.CharField(choices=[('male', 'ذكور فقط'), ('female', 'إناث فقط'), ('all', 'الجميع')], default='all', max_length=10, verbose_name='قيود الجنس')),
                ('employment_type_restriction', models.CharField(choices=[('permanent', 'دائم فقط'), ('contract', 'تعاقد فقط'), ('all', 'الجميع')], default='all', max_length=20, verbose_name='قيود نوع التوظيف')),
                ('min_service_months', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى لشهور الخدمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, verbose_name='ساري من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='ساري حتى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='Hr.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'نوع الإجازة',
                'verbose_name_plural': 'أنواع الإجازات',
                'ordering': ['company', 'name'],
                'indexes': [
                    models.Index(fields=['company', 'code'], name='Hr_leavetype_company_b8e123_idx'),
                    models.Index(fields=['category'], name='Hr_leavetype_categor_9c7d4e_idx'),
                    models.Index(fields=['is_active'], name='Hr_leavetype_is_acti_8f4a2b_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('days_requested', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='الأيام المطلوبة')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'معلق'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('expired', 'منتهي الصلاحية')], default='draft', max_length=20, verbose_name='الحالة')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('approved_days', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الأيام المعتمدة')),
                ('approval_comments', models.TextField(blank=True, null=True, verbose_name='تعليقات الاعتماد')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='معتمد بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='Hr.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Hr.leavetype', verbose_name='نوع الإجازة')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='مرفوض بواسطة')),
            ],
            options={
                'verbose_name': 'طلب الإجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-requested_at'],
                'indexes': [
                    models.Index(fields=['employee', 'status'], name='Hr_leaverequ_employe_8a4b7c_idx'),
                    models.Index(fields=['leave_type', 'status'], name='Hr_leaverequ_leave_t_3f9e2d_idx'),
                    models.Index(fields=['start_date', 'end_date'], name='Hr_leaverequ_start_d_6c5a8b_idx'),
                    models.Index(fields=['status', 'requested_at'], name='Hr_leaverequ_status_7d2f4e_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('allocated_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الأيام المخصصة')),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الأيام المستخدمة')),
                ('remaining_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الأيام المتبقية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='Hr.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='Hr.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'رصيد الإجازة',
                'verbose_name_plural': 'أرصدة الإجازات',
                'ordering': ['employee', 'leave_type', '-year'],
                'indexes': [
                    models.Index(fields=['employee', 'year'], name='Hr_leavebala_employe_4b8c9d_idx'),
                    models.Index(fields=['leave_type', 'year'], name='Hr_leavebala_leave_t_7e3f5a_idx'),
                    models.Index(fields=['is_active'], name='Hr_leavebala_is_acti_2a6b8c_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='دائم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='معين بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='Hr.employee', verbose_name='الموظف')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='Hr.workshift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'تعيين وردية الموظف',
                'verbose_name_plural': 'تعيينات ورديات الموظفين',
                'ordering': ['-start_date'],
                'indexes': [
                    models.Index(fields=['employee', 'start_date'], name='Hr_employee_employe_9d4e7f_idx'),
                    models.Index(fields=['shift', 'start_date'], name='Hr_employee_shift_1a2b3c_idx'),
                    models.Index(fields=['is_active'], name='Hr_employee_is_acti_4d5e6f_idx'),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
