# Generated by Django 5.0.14 on 2025-07-28 14:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0027_add_leave_management_models'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصلاحية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='الرمز')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('permission_type', models.CharField(choices=[('view', 'عرض'), ('add', 'إضافة'), ('change', 'تعديل'), ('delete', 'حذف'), ('export', 'تصدير'), ('import', 'استيراد'), ('approve', 'موافقة'), ('reject', 'رفض'), ('manage', 'إدارة'), ('admin', 'إدارة كاملة')], max_length=20, verbose_name='نوع الصلاحية')),
                ('scope_level', models.CharField(choices=[('own', 'البيانات الشخصية فقط'), ('department', 'القسم'), ('branch', 'الفرع'), ('company', 'الشركة'), ('all', 'جميع البيانات')], default='department', max_length=20, verbose_name='نطاق الصلاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, verbose_name='صلاحية نظام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صلاحية الموارد البشرية',
                'verbose_name_plural': 'صلاحيات الموارد البشرية',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(max_length=20, verbose_name='نوع الإشعار')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('read', 'تم القراءة'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الإرسال')),
            ],
            options={
                'verbose_name': 'الإشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية'), ('push', 'إشعار فوري'), ('in_app', 'داخل التطبيق'), ('slack', 'سلاك'), ('teams', 'تيمز')], max_length=20, verbose_name='طريقة التسليم')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('failed', 'فشل'), ('bounced', 'مرتد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('recipient_address', models.CharField(max_length=200, verbose_name='عنوان المستلم')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='مقدم الخدمة')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='المعرف الخارجي')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الاستجابة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('attempts', models.IntegerField(default=0, verbose_name='عدد المحاولات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد المحاولة التالية')),
            ],
            options={
                'verbose_name': 'تسليم الإشعار',
                'verbose_name_plural': 'تسليمات الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], max_length=20, verbose_name='التكرار')),
                ('period_start', models.DateTimeField(verbose_name='بداية الفترة')),
                ('period_end', models.DateTimeField(verbose_name='نهاية الفترة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('notifications_count', models.IntegerField(default=0, verbose_name='عدد الإشعارات')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم الإرسال'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'ملخص الإشعارات',
                'verbose_name_plural': 'ملخصات الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='البريد الإلكتروني')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='الرسائل النصية')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='الإشعارات الفورية')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='داخل التطبيق')),
                ('digest_enabled', models.BooleanField(default=False, verbose_name='تفعيل الملخص')),
                ('digest_frequency', models.CharField(choices=[('none', 'بدون ملخص'), ('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='daily', max_length=20, verbose_name='تكرار الملخص')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='تفعيل الساعات الهادئة')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية الساعات الهادئة')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الساعات الهادئة')),
                ('notification_types', models.JSONField(blank=True, default=dict, verbose_name='تفضيلات الأنواع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تفضيلات الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القاعدة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('trigger_event', models.CharField(choices=[('employee_created', 'إنشاء موظف جديد'), ('employee_updated', 'تحديث بيانات موظف'), ('leave_request_created', 'طلب إجازة جديد'), ('leave_request_approved', 'موافقة على طلب إجازة'), ('leave_request_rejected', 'رفض طلب إجازة'), ('attendance_late', 'تأخير في الحضور'), ('document_expiry', 'انتهاء صلاحية وثيقة'), ('birthday', 'عيد ميلاد موظف'), ('work_anniversary', 'ذكرى التوظيف'), ('performance_review_due', 'موعد تقييم الأداء'), ('payroll_processed', 'معالجة الراتب'), ('system_alert', 'تنبيه النظام')], max_length=50, verbose_name='حدث التشغيل')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='الشروط')),
                ('recipient_rules', models.JSONField(blank=True, default=dict, verbose_name='قواعد المستلمين')),
                ('delay_minutes', models.IntegerField(default=0, verbose_name='تأخير بالدقائق')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='متكرر')),
                ('recurrence_pattern', models.JSONField(blank=True, default=dict, verbose_name='نمط التكرار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.IntegerField(default=1, verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قاعدة الإشعار',
                'verbose_name_plural': 'قواعد الإشعارات',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notification_type', models.CharField(choices=[('info', 'معلومات'), ('warning', 'تحذير'), ('error', 'خطأ'), ('success', 'نجاح'), ('reminder', 'تذكير'), ('urgent', 'عاجل')], max_length=20, verbose_name='نوع الإشعار')),
                ('title_template', models.CharField(max_length=200, verbose_name='قالب العنوان')),
                ('message_template', models.TextField(verbose_name='قالب الرسالة')),
                ('email_template', models.TextField(blank=True, verbose_name='قالب البريد الإلكتروني')),
                ('sms_template', models.TextField(blank=True, verbose_name='قالب الرسائل النصية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب الإشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-shield-alt', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='اللون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فئة الصلاحيات',
                'verbose_name_plural': 'فئات الصلاحيات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('granted', 'منح'), ('revoked', 'سحب'), ('modified', 'تعديل'), ('used', 'استخدام')], max_length=20, verbose_name='الإجراء')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سجل الصلاحية',
                'verbose_name_plural': 'سجلات الصلاحيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('grant', 'منح صلاحية'), ('revoke', 'سحب صلاحية'), ('modify', 'تعديل صلاحية')], max_length=20, verbose_name='نوع الطلب')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('approval_notes', models.TextField(blank=True, verbose_name='ملاحظات الموافقة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'طلب صلاحية',
                'verbose_name_plural': 'طلبات الصلاحيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_default', models.BooleanField(default=False, verbose_name='قالب افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب الدور',
                'verbose_name_plural': 'قوالب الأدوار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم البحث')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('search_type', models.CharField(choices=[('simple', 'بحث بسيط'), ('advanced', 'بحث متقدم'), ('filter', 'فلترة'), ('smart', 'بحث ذكي')], default='simple', max_length=20, verbose_name='نوع البحث')),
                ('query', models.TextField(verbose_name='استعلام البحث')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='فلاتر البحث المطبقة', verbose_name='الفلاتر')),
                ('content_types', models.JSONField(blank=True, default=list, help_text='أنواع المحتوى المشمولة في البحث', verbose_name='أنواع المحتوى')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدام')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='مفضل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'بحث محفوظ',
                'verbose_name_plural': 'عمليات البحث المحفوظة',
                'ordering': ['-last_used_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفلتر')),
                ('field_name', models.CharField(max_length=100, verbose_name='اسم الحقل')),
                ('display_name', models.CharField(max_length=100, verbose_name='الاسم المعروض')),
                ('filter_type', models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ'), ('choice', 'اختيار'), ('boolean', 'منطقي'), ('range', 'نطاق')], default='text', max_length=20, verbose_name='نوع الفلتر')),
                ('supported_operators', models.JSONField(default=list, help_text='قائمة بالعمليات المدعومة لهذا الفلتر', verbose_name='العمليات المدعومة')),
                ('choices', models.JSONField(blank=True, default=list, help_text='خيارات الفلتر للأنواع المحددة', verbose_name='الخيارات')),
                ('content_types', models.JSONField(default=list, help_text='أنواع المحتوى التي يطبق عليها هذا الفلتر', verbose_name='أنواع المحتوى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_required', models.BooleanField(default=False, verbose_name='مطلوب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='نص المساعدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فلتر البحث',
                'verbose_name_plural': 'فلاتر البحث',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف الكائن')),
                ('title', models.CharField(max_length=500, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('keywords', models.TextField(blank=True, verbose_name='الكلمات المفتاحية')),
                ('search_vector', models.TextField(blank=True, verbose_name='فهرس البحث')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='معلومات إضافية للبحث والفلترة', verbose_name='البيانات الوصفية')),
                ('company_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الشركة')),
                ('department_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف القسم')),
                ('branch_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الفرع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('indexed_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الفهرسة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فهرس البحث',
                'verbose_name_plural': 'فهارس البحث',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='مفتاح الجلسة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('query', models.TextField(verbose_name='استعلام البحث')),
                ('search_type', models.CharField(default='simple', max_length=20, verbose_name='نوع البحث')),
                ('filters_applied', models.JSONField(blank=True, default=dict, verbose_name='الفلاتر المطبقة')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='عدد النتائج')),
                ('result_status', models.CharField(choices=[('success', 'نجح'), ('no_results', 'لا توجد نتائج'), ('error', 'خطأ'), ('cancelled', 'ملغي')], default='success', max_length=20, verbose_name='حالة النتائج')),
                ('execution_time', models.FloatField(default=0.0, verbose_name='وقت التنفيذ (ثانية)')),
                ('user_agent', models.TextField(blank=True, verbose_name='وكيل المستخدم')),
                ('referer', models.URLField(blank=True, verbose_name='المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البحث')),
            ],
            options={
                'verbose_name': 'سجل البحث',
                'verbose_name_plural': 'سجلات البحث',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200, verbose_name='النص')),
                ('suggestion_type', models.CharField(choices=[('keyword', 'كلمة مفتاحية'), ('phrase', 'عبارة'), ('filter', 'فلتر'), ('correction', 'تصحيح')], default='keyword', max_length=20, verbose_name='نوع الاقتراح')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدام')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='معدل النجاح')),
                ('context', models.JSONField(blank=True, default=dict, help_text='معلومات السياق للاقتراح', verbose_name='السياق')),
                ('categories', models.JSONField(blank=True, default=list, help_text='فئات المحتوى المرتبطة', verbose_name='الفئات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='مُولد تلقائياً')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'اقتراح البحث',
                'verbose_name_plural': 'اقتراحات البحث',
                'ordering': ['-usage_count', '-success_rate'],
            },
        ),
        migrations.CreateModel(
            name='SmartSearchPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=200, verbose_name='النمط')),
                ('replacement', models.CharField(max_length=200, verbose_name='البديل')),
                ('pattern_type', models.CharField(choices=[('synonym', 'مرادف'), ('abbreviation', 'اختصار'), ('common_typo', 'خطأ شائع'), ('related_term', 'مصطلح مرتبط'), ('category', 'فئة')], default='synonym', max_length=20, verbose_name='نوع النمط')),
                ('weight', models.FloatField(default=1.0, verbose_name='الوزن')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='الأولوية')),
                ('context_filters', models.JSONField(blank=True, default=dict, help_text='شروط تطبيق النمط', verbose_name='فلاتر السياق')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدام')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='معدل النجاح')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_case_sensitive', models.BooleanField(default=False, verbose_name='حساس للأحرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نمط البحث الذكي',
                'verbose_name_plural': 'أنماط البحث الذكي',
                'ordering': ['-priority', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='صالح من')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='صالح حتى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'دور المستخدم',
                'verbose_name_plural': 'أدوار المستخدمين',
            },
        ),
        # migrations.RemoveField(
        #     model_name='employeeshiftassignment',
        #     name='assigned_by',
        # ),
        # migrations.RemoveField(
        #     model_name='employeeshiftassignment',
        #     name='employee',
        # ),
        # migrations.RemoveField(
        #     model_name='employeeshiftassignment',
        #     name='shift',
        # ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['employee', 'leave_type', '-balance_year'], 'verbose_name': 'رصيد إجازة', 'verbose_name_plural': 'أرصدة الإجازات'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب إجازة', 'verbose_name_plural': 'طلبات الإجازات'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'نوع إجازة', 'verbose_name_plural': 'أنواع الإجازات'},
        ),
        # migrations.RemoveIndex(
        #     model_name='leavebalance',
        #     name='Hr_leavebala_employe_4b8c9d_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='leavebalance',
        #     name='Hr_leavebala_leave_t_7e3f5a_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='leaverequest',
        #     name='Hr_leaverequ_employe_8a4b7c_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='leaverequest',
        #     name='Hr_leaverequ_leave_t_3f9e2d_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='leaverequest',
        #     name='Hr_leaverequ_status_7d2f4e_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='leavetype',
        #     name='Hr_leavetype_company_b8e123_idx',
        # ),
        migrations.RenameField(
            model_name='leavetype',
            old_name='min_service_months',
            new_name='minimum_service_months',
        ),
        migrations.RenameIndex(
            model_name='leavebalance',
            new_name='hrms_leave__is_acti_0557d6_idx',
            old_name='Hr_leavebala_is_acti_2a6b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='hrms_leave__start_d_a30332_idx',
            old_name='Hr_leaverequ_start_d_6c5a8b_idx',
        ),
        migrations.RenameIndex(
            model_name='leavetype',
            new_name='hrms_leave__categor_3ad6a1_idx',
            old_name='Hr_leavetype_categor_9c7d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='leavetype',
            new_name='hrms_leave__is_acti_fe50e4_idx',
            old_name='Hr_leavetype_is_acti_8f4a2b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'balance_year')},
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approval_comments',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_days',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='requested_at',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='accrued_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='الرصيد المستحق'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='adjustment_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='تعديل الرصيد'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='available_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='الرصيد المتاح'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='balance_year',
            field=models.PositiveIntegerField(default=2024, verbose_name='سنة الرصيد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carried_forward_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='الرصيد المرحل'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carry_forward_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الرصيد المرحل'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carry_forward_from_previous',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='مرحل من السنة السابقة'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='current_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='الرصيد الحالي'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='encashed_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='الرصيد المصروف'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='freeze_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب التجميد'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='هل الرصيد مجمد ولا يمكن استخدامه؟', verbose_name='مجمد'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='last_accrual_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر استحقاق'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='last_calculation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر حساب'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='opening_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='الرصيد الافتتاحي'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='pending_balance',
            field=models.DecimalField(decimal_places=1, default=0, help_text='الرصيد المحجوز للطلبات المعلقة', max_digits=6, verbose_name='الرصيد المعلق'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='period_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ نهاية الفترة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='period_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بداية الفترة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='الرصيد المستخدم'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='actual_days_taken',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الأيام المأخوذة فعلياً'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية الفعلي'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ العودة الفعلي'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البداية الفعلي'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='auto_approved',
            field=models.BooleanField(default=False, verbose_name='موافقة تلقائية'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='balance_after_request',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='الرصيد بعد الطلب'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='balance_before_request',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='الرصيد قبل الطلب'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='current_approval_level',
            field=models.PositiveIntegerField(default=0, verbose_name='مستوى الموافقة الحالي'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='emergency_contact_during_leave',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='جهة الاتصال أثناء الإجازة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='emergency_phone_during_leave',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف الطوارئ أثناء الإجازة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_comments',
            field=models.TextField(blank=True, null=True, verbose_name='تعليقات الموظف'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ العودة المتوقع'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_period',
            field=models.CharField(blank=True, choices=[('morning', 'الفترة الصباحية'), ('afternoon', 'الفترة المسائية')], max_length=10, null=True, verbose_name='فترة نصف اليوم'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='handover_completed',
            field=models.BooleanField(default=False, verbose_name='تم التسليم'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='handover_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات التسليم'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='handover_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_handovers', to='Hr.employee', verbose_name='تسليم المهام إلى'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_comments',
            field=models.TextField(blank=True, null=True, verbose_name='تعليقات الموارد البشرية'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_backdated',
            field=models.BooleanField(default=False, verbose_name='طلب بأثر رجعي'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_emergency_leave',
            field=models.BooleanField(default=False, verbose_name='إجازة طارئة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_half_day',
            field=models.BooleanField(default=False, verbose_name='نصف يوم'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='Hr.leavepolicy', verbose_name='سياسة الإجازة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_comments',
            field=models.TextField(blank=True, null=True, verbose_name='تعليقات المدير'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/medical/', verbose_name='الشهادة الطبية'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='return_confirmed',
            field=models.BooleanField(default=False, verbose_name='تم تأكيد العودة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='return_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تأكيد العودة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='return_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_returns', to=settings.AUTH_USER_MODEL, verbose_name='تم تأكيد العودة بواسطة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='قدم بواسطة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/supporting/', verbose_name='المستندات الداعمة'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='auto_approve_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='الطلبات أقل من هذا العدد تتم الموافقة عليها تلقائياً', null=True, verbose_name='حد الموافقة التلقائية (أيام)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='blackout_periods',
            field=models.JSONField(default=list, help_text='فترات لا يمكن أخذ إجازة فيها', verbose_name='فترات المنع'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='can_be_split',
            field=models.BooleanField(default=True, help_text='هل يمكن أخذ هذه الإجازة على فترات منفصلة؟', verbose_name='يمكن تقسيمها'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_allowed',
            field=models.BooleanField(default=False, help_text='هل يمكن ترحيل الرصيد للسنة التالية؟', verbose_name='يسمح بترحيل الرصيد'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_expiry_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='انتهاء صلاحية الرصيد المرحل (شهور)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_types', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='gender_eligibility',
            field=models.CharField(choices=[('all', 'الجميع'), ('male', 'ذكور فقط'), ('female', 'إناث فقط')], default='all', max_length=10, verbose_name='الأهلية حسب الجنس'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_system_leave',
            field=models.BooleanField(default=False, help_text='هل هذا نوع إجازة أساسي في النظام؟', verbose_name='إجازة نظام'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='leave_settings',
            field=models.JSONField(default=dict, help_text='إعدادات إضافية خاصة بنوع الإجازة', verbose_name='إعدادات الإجازة'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_carry_forward_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى لأيام الترحيل'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_concurrent_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للموظفين في نفس الوقت'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_per_request',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للأيام في الطلب الواحد'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='maximum_advance_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للحجز المسبق (أيام)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='medical_certificate_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='عدد الأيام التي تتطلب شهادة طبية', null=True, verbose_name='حد الشهادة الطبية (أيام)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='min_days_per_request',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للأيام في الطلب الواحد'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='minimum_notice_days',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى لفترة الإشعار (أيام)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='payment_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='نسبة الراتب المدفوع أثناء الإجازة', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الدفع (%)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_medical_certificate',
            field=models.BooleanField(default=False, verbose_name='يتطلب شهادة طبية'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_supporting_documents',
            field=models.BooleanField(default=False, verbose_name='يتطلب مستندات داعمة'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_balances', to='Hr.leavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='days_requested',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='عدد الأيام المطلوبة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='Hr.leavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='سبب الإجازة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('pending_approval', 'في انتظار الموافقة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('in_progress', 'جاري'), ('completed', 'مكتمل'), ('partially_taken', 'مأخوذ جزئياً')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='accrual_method',
            field=models.CharField(choices=[('annual', 'سنوي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('weekly', 'أسبوعي'), ('none', 'لا يوجد استحقاق')], default='annual', max_length=20, verbose_name='طريقة الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='accrual_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='عدد الأيام المستحقة حسب طريقة الاستحقاق', max_digits=5, null=True, verbose_name='معدل الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='approval_levels',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='مستويات الموافقة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='category',
            field=models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('maternity', 'إجازة أمومة'), ('paternity', 'إجازة أبوة'), ('emergency', 'إجازة طارئة'), ('bereavement', 'إجازة وفاة'), ('study', 'إجازة دراسية'), ('pilgrimage', 'إجازة حج/عمرة'), ('marriage', 'إجازة زواج'), ('unpaid', 'إجازة بدون راتب'), ('compensatory', 'إجازة تعويضية'), ('sabbatical', 'إجازة تفرغ'), ('military', 'إجازة خدمة عسكرية'), ('other', 'أخرى')], max_length=20, verbose_name='فئة الإجازة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='exclude_weekends',
            field=models.BooleanField(default=True, verbose_name='استبعاد عطلات نهاية الأسبوع'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='إجازة مدفوعة الأجر'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.PositiveIntegerField(blank=True, help_text='الحد الأقصى لأيام الإجازة في السنة', null=True, verbose_name='الحد الأقصى للأيام سنوياً'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['employee', 'leave_type'], name='hrms_leave__employe_705178_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['balance_year'], name='hrms_leave__balance_948721_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'start_date'], name='hrms_leave__employe_24e4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='hrms_leave__status_612389_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['leave_type'], name='hrms_leave__leave_t_b3141c_idx'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['code'], name='hrms_leave__code_e057b2_idx'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['sort_order'], name='hrms_leave__sort_or_e0c269_idx'),
        ),
        migrations.AlterModelTable(
            name='leavebalance',
            table='hrms_leave_balance',
        ),
        migrations.AlterModelTable(
            name='leaverequest',
            table='hrms_leave_request',
        ),
        migrations.AlterModelTable(
            name='leavetype',
            table='hrms_leave_type',
        ),
        migrations.AddField(
            model_name='hrpermission',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى'),
        ),
        migrations.AddField(
            model_name='hrpermission',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_permissions', to='Hr.hrpermission', verbose_name='الصلاحيات المطلوبة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_notifications', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='Hr.notification', verbose_name='الإشعار'),
        ),
        migrations.AddField(
            model_name='notificationdigest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='notification',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.notificationrule', verbose_name='القاعدة'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.notificationtemplate', verbose_name='القالب'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.notificationtemplate', verbose_name='القالب'),
        ),
        migrations.AddField(
            model_name='hrpermission',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Hr.permissioncategory', verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='permissionlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_permission_logs', to=settings.AUTH_USER_MODEL, verbose_name='نفذ بواسطة'),
        ),
        migrations.AddField(
            model_name='permissionlog',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Hr.hrpermission', verbose_name='الصلاحية'),
        ),
        migrations.AddField(
            model_name='permissionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='الموافق'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='permissions',
            field=models.ManyToManyField(related_name='permission_requests', to='Hr.hrpermission', verbose_name='الصلاحيات المطلوبة'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests_for', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستهدف'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_role_templates', to=settings.AUTH_USER_MODEL, verbose_name='منشئ القالب'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='permissions',
            field=models.ManyToManyField(related_name='role_templates', to='Hr.hrpermission', verbose_name='الصلاحيات'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='searchfilter',
            index=models.Index(fields=['name'], name='Hr_searchfi_name_8bf04b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchfilter',
            index=models.Index(fields=['field_name'], name='Hr_searchfi_field_n_59fa15_idx'),
        ),
        migrations.AddIndex(
            model_name='searchfilter',
            index=models.Index(fields=['filter_type'], name='Hr_searchfi_filter__6b655e_idx'),
        ),
        migrations.AddIndex(
            model_name='searchfilter',
            index=models.Index(fields=['is_active'], name='Hr_searchfi_is_acti_a39b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='searchfilter',
            index=models.Index(fields=['order'], name='Hr_searchfi_order_923ded_idx'),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='searchsuggestion',
            index=models.Index(fields=['text'], name='Hr_searchsu_text_1bad6d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsuggestion',
            index=models.Index(fields=['suggestion_type'], name='Hr_searchsu_suggest_021cab_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsuggestion',
            index=models.Index(fields=['usage_count'], name='Hr_searchsu_usage_c_97ad03_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsuggestion',
            index=models.Index(fields=['success_rate'], name='Hr_searchsu_success_08eb98_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsuggestion',
            index=models.Index(fields=['is_active'], name='Hr_searchsu_is_acti_3edcbf_idx'),
        ),
        migrations.AddIndex(
            model_name='smartsearchpattern',
            index=models.Index(fields=['pattern'], name='Hr_smartsea_pattern_bbd394_idx'),
        ),
        migrations.AddIndex(
            model_name='smartsearchpattern',
            index=models.Index(fields=['pattern_type'], name='Hr_smartsea_pattern_b20454_idx'),
        ),
        migrations.AddIndex(
            model_name='smartsearchpattern',
            index=models.Index(fields=['weight'], name='Hr_smartsea_weight_870bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='smartsearchpattern',
            index=models.Index(fields=['priority'], name='Hr_smartsea_priorit_04c5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='smartsearchpattern',
            index=models.Index(fields=['is_active'], name='Hr_smartsea_is_acti_f52995_idx'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='additional_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_roles_additional', to='Hr.hrpermission', verbose_name='صلاحيات إضافية'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='معين بواسطة'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='branch_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_users', to='Hr.branch', verbose_name='نطاق الفرع'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='department_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_users', to='Hr.department', verbose_name='نطاق القسم'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='removed_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_roles_removed', to='Hr.hrpermission', verbose_name='صلاحيات محذوفة'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles', to='Hr.roletemplate', verbose_name='قالب الدور'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_role', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        # migrations.DeleteModel(
        #     name='EmployeeShiftAssignment',
        # ),
        migrations.RemoveField(
            model_name='leavetype',
            name='allow_carryover',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='auto_approve_days',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='carryover_expiry_months',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='default_days',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='employment_type_restriction',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='gender_restriction',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='max_carryover_days',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='max_consecutive_days',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='min_notice_days',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='name_english',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='allocated_days',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='remaining_days',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='used_days',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='year',
        ),
        migrations.AlterUniqueTogether(
            name='notificationdelivery',
            unique_together={('notification', 'method')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationdigest',
            unique_together={('user', 'frequency', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='Hr_notifica_recipie_ffab37_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='Hr_notifica_created_35e143_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='Hr_notifica_priorit_0bff4f_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user', 'is_favorite'], name='Hr_savedsea_user_id_7948fb_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['is_public'], name='Hr_savedsea_is_publ_3db596_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['search_type'], name='Hr_savedsea_search__263d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['usage_count'], name='Hr_savedsea_usage_c_6d78cf_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['content_type', 'object_id'], name='Hr_searchin_content_d6958b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['company_id'], name='Hr_searchin_company_688326_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['department_id'], name='Hr_searchin_departm_340e33_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['branch_id'], name='Hr_searchin_branch__c360cc_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['created_at'], name='Hr_searchin_created_2115e4_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['is_active'], name='Hr_searchin_is_acti_eaeb07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchindex',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['user', 'created_at'], name='Hr_searchlo_user_id_820cac_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['query'], name='Hr_searchlo_query_ddd0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['search_type'], name='Hr_searchlo_search__2fbaac_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['result_status'], name='Hr_searchlo_result__31a2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['created_at'], name='Hr_searchlo_created_142706_idx'),
        ),
    ]
