# Generated by Django 5.0.14 on 2025-05-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0023_fix_employeeleave_table_sqlite'),
        ('Hr', '0027_fix_employeeleave_table_agnostic'),
    ]

    operations = [
    ]
