# Generated by Django 5.0.14 on 2025-07-28 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0028_hrpermission_notification_notificationdelivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('import_format', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('xml', 'XML'), ('txt', 'نص')], max_length=20, verbose_name='تنسيق الاستيراد')),
                ('target_model', models.CharField(max_length=100, verbose_name='النموذج المستهدف')),
                ('field_mapping', models.JSONField(default=dict, help_text='ربط حقول الملف بحقول النموذج', verbose_name='خريطة الحقول')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='قواعد التحقق من صحة البيانات', verbose_name='قواعد التحقق')),
                ('import_settings', models.JSONField(blank=True, default=dict, help_text='إعدادات إضافية للاستيراد', verbose_name='إعدادات الاستيراد')),
                ('template_file', models.FileField(blank=True, help_text='ملف قالب للتحميل', upload_to='import_templates/', verbose_name='ملف القالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب استيراد البيانات',
                'verbose_name_plural': 'قوالب استيراد البيانات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('template_type', models.CharField(choices=[('notification', 'إشعار'), ('welcome', 'ترحيب'), ('reminder', 'تذكير'), ('report', 'تقرير'), ('alert', 'تنبيه'), ('newsletter', 'نشرة إخبارية'), ('invitation', 'دعوة'), ('confirmation', 'تأكيد')], max_length=20, verbose_name='نوع القالب')),
                ('subject_template', models.CharField(max_length=500, verbose_name='قالب الموضوع')),
                ('html_content', models.TextField(verbose_name='المحتوى HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='المحتوى النصي')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='من البريد')),
                ('reply_to', models.EmailField(blank=True, max_length=254, verbose_name='الرد إلى')),
                ('available_variables', models.JSONField(blank=True, default=list, help_text='قائمة بالمتغيرات المتاحة في القالب', verbose_name='المتغيرات المتاحة')),
                ('default_attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات الافتراضية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب البريد الإلكتروني',
                'verbose_name_plural': 'قوالب البريد الإلكتروني',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم النظام')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('system_type', models.CharField(choices=[('attendance_device', 'جهاز حضور'), ('accounting_system', 'نظام محاسبة'), ('email_service', 'خدمة بريد إلكتروني'), ('payroll_system', 'نظام رواتب'), ('hr_system', 'نظام موارد بشرية'), ('erp_system', 'نظام تخطيط موارد'), ('time_tracking', 'تتبع الوقت'), ('document_management', 'إدارة الوثائق'), ('backup_service', 'خدمة النسخ الاحتياطي'), ('reporting_tool', 'أداة التقارير')], max_length=50, verbose_name='نوع النظام')),
                ('connection_type', models.CharField(choices=[('api', 'API'), ('database', 'قاعدة بيانات'), ('file_transfer', 'نقل ملفات'), ('web_service', 'خدمة ويب'), ('tcp_socket', 'TCP Socket'), ('serial_port', 'منفذ تسلسلي'), ('webhook', 'Webhook'), ('sftp', 'SFTP'), ('email', 'بريد إلكتروني')], max_length=50, verbose_name='نوع الاتصال')),
                ('endpoint_url', models.URLField(blank=True, verbose_name='رابط النقطة')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='المضيف')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='المنفذ')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='اسم المستخدم')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='كلمة المرور')),
                ('api_key', models.TextField(blank=True, verbose_name='مفتاح API')),
                ('token', models.TextField(blank=True, verbose_name='الرمز المميز')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='مهلة الاتصال (ثانية)')),
                ('retry_attempts', models.PositiveIntegerField(default=3, verbose_name='محاولات الإعادة')),
                ('retry_delay', models.PositiveIntegerField(default=5, verbose_name='تأخير الإعادة (ثانية)')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='إعدادات إضافية خاصة بالنظام', verbose_name='الإعدادات')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('error', 'خطأ'), ('maintenance', 'صيانة'), ('testing', 'اختبار')], default='inactive', max_length=20, verbose_name='الحالة')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('last_error', models.TextField(blank=True, verbose_name='آخر خطأ')),
                ('auto_sync_enabled', models.BooleanField(default=False, verbose_name='المزامنة التلقائية')),
                ('sync_interval', models.PositiveIntegerField(default=60, verbose_name='فترة المزامنة (دقائق)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نظام خارجي',
                'verbose_name_plural': 'الأنظمة الخارجية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_file', models.FileField(upload_to='import_data/', verbose_name='ملف البيانات')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد المعالجة'), ('validating', 'قيد التحقق'), ('importing', 'قيد الاستيراد'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='نسبة التقدم')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='إجمالي الصفوف')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='الصفوف المعالجة')),
                ('successful_rows', models.PositiveIntegerField(default=0, verbose_name='الصفوف الناجحة')),
                ('failed_rows', models.PositiveIntegerField(default=0, verbose_name='الصفوف الفاشلة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية المعالجة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء المعالجة')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='أخطاء التحقق')),
                ('import_errors', models.JSONField(blank=True, default=list, verbose_name='أخطاء الاستيراد')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='ملخص النتائج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مهمة استيراد البيانات',
                'verbose_name_plural': 'مهام استيراد البيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_name', models.CharField(max_length=200, verbose_name='اسم الربط')),
                ('mapping_type', models.CharField(choices=[('field_mapping', 'ربط حقول'), ('data_transformation', 'تحويل بيانات'), ('validation_rule', 'قاعدة تحقق'), ('calculation', 'حساب'), ('lookup', 'بحث')], max_length=50, verbose_name='نوع الربط')),
                ('local_model', models.CharField(max_length=100, verbose_name='النموذج المحلي')),
                ('local_field', models.CharField(max_length=100, verbose_name='الحقل المحلي')),
                ('external_field', models.CharField(max_length=100, verbose_name='الحقل الخارجي')),
                ('external_format', models.CharField(blank=True, max_length=100, verbose_name='تنسيق خارجي')),
                ('transformation_rules', models.JSONField(blank=True, default=dict, help_text='قواعد تحويل البيانات', verbose_name='قواعد التحويل')),
                ('sync_direction', models.CharField(choices=[('import', 'استيراد'), ('export', 'تصدير'), ('bidirectional', 'ثنائي الاتجاه')], default='bidirectional', max_length=20, verbose_name='اتجاه المزامنة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خريطة التكامل',
                'verbose_name_plural': 'خرائط التكامل',
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=200, verbose_name='اسم المهمة')),
                ('job_type', models.CharField(choices=[('manual', 'يدوي'), ('scheduled', 'مجدول'), ('triggered', 'مُفعل'), ('real_time', 'فوري')], max_length=20, verbose_name='نوع المهمة')),
                ('sync_criteria', models.JSONField(blank=True, default=dict, help_text='معايير تحديد البيانات للمزامنة', verbose_name='معايير المزامنة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('running', 'قيد التشغيل'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي'), ('partial', 'جزئي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='نسبة التقدم')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='إجمالي السجلات')),
                ('processed_records', models.PositiveIntegerField(default=0, verbose_name='السجلات المعالجة')),
                ('successful_records', models.PositiveIntegerField(default=0, verbose_name='السجلات الناجحة')),
                ('failed_records', models.PositiveIntegerField(default=0, verbose_name='السجلات الفاشلة')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد التشغيل')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية التشغيل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء التشغيل')),
                ('log_data', models.JSONField(blank=True, default=list, verbose_name='بيانات السجل')),
                ('error_details', models.TextField(blank=True, verbose_name='تفاصيل الأخطاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مهمة المزامنة',
                'verbose_name_plural': 'مهام المزامنة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignment',
            name='shift',
        ),
        migrations.RemoveIndex(
            model_name='leavebalance',
            name='Hr_leavebala_employe_4b8c9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavebalance',
            name='Hr_leavebala_leave_t_7e3f5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='Hr_leaverequ_employe_8a4b7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='Hr_leaverequ_leave_t_3f9e2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='Hr_leaverequ_status_7d2f4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavetype',
            name='Hr_leavetype_company_b8e123_idx',
        ),
        migrations.AddField(
            model_name='dataimporttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_templates', to=settings.AUTH_USER_MODEL, verbose_name='منشئ القالب'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to=settings.AUTH_USER_MODEL, verbose_name='منشئ القالب'),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_systems', to=settings.AUTH_USER_MODEL, verbose_name='منشئ النظام'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='منشئ المهمة'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='Hr.dataimporttemplate', verbose_name='القالب'),
        ),
        migrations.AddField(
            model_name='integrationmapping',
            name='external_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='Hr.externalsystem', verbose_name='النظام الخارجي'),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to=settings.AUTH_USER_MODEL, verbose_name='منشئ المهمة'),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='external_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='Hr.externalsystem', verbose_name='النظام الخارجي'),
        ),
        migrations.DeleteModel(
            name='EmployeeShiftAssignment',
        ),
        migrations.AlterUniqueTogether(
            name='integrationmapping',
            unique_together={('external_system', 'mapping_name')},
        ),
    ]
