# Generated by Django 5.0.14 on 2025-05-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0028_merge_20250505_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='كود مدير القسم'),
        ),
        migrations.AddField(
            model_name='department',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
    ]
