# Generated by Django 5.0.14 on 2025-05-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0003_fix_tbl_car_table'),
        ('Hr', '0029_department_is_active_department_manager_id_and_more'),
    ]

    operations = [
    ]
