# Generated by Django 5.0.14 on 2025-05-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0005_skip_employeetask_table'),
        ('Hr', '0030_merge_20250506_2104'),
    ]

    operations = [
    ]
