# Generated by Django 5.0.14 on 2025-05-06 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0031_merge_20250506_2157'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetask',
            options={'managed': True, 'ordering': ['-due_date', 'priority'], 'verbose_name': 'مهمة الموظف', 'verbose_name_plural': 'مهام الموظفين'},
        ),
        migrations.AddField(
            model_name='employeetask',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='تم التكليف بواسطة'),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='employee',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Hr.employee', verbose_name='الموظف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز'),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='من 0 إلى 100', verbose_name='نسبة الإنجاز (%)'),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterModelTable(
            name='employeetask',
            table=None,
        ),
    ]
