# Generated by Django 4.2.7 on 2025-08-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0030_create_enhanced_attendance_models'),
        ('Hr', '0032_add_enhanced_education_fields'),
    ]

    operations = [
    ]
