# Generated by Django 4.2.7 on 2025-08-09 10:07

import Hr.models.employee.employee_file_models
import Hr.models.employee.employee_models_enhanced
import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hr', '0035_merge_20250806_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMachineEnhanced',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='الرقم التسلسلي')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموديل')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='الشركة المصنعة')),
                ('machine_type', models.CharField(choices=[('fingerprint', 'بصمة الإصبع'), ('face_recognition', 'التعرف على الوجه'), ('card_reader', 'قارئ البطاقات'), ('pin_pad', 'لوحة الأرقام'), ('iris_scanner', 'ماسح القزحية'), ('palm_reader', 'قارئ الكف'), ('mobile_app', 'تطبيق الجوال'), ('web_portal', 'البوابة الإلكترونية'), ('hybrid', 'متعدد الوسائل')], default='fingerprint', max_length=20, verbose_name='نوع الجهاز')),
                ('supported_methods', models.JSONField(default=list, help_text='قائمة بطرق المصادقة التي يدعمها الجهاز', verbose_name='طرق المصادقة المدعومة')),
                ('location_name', models.CharField(max_length=200, verbose_name='اسم الموقع')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='المبنى')),
                ('floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='الطابق')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='الغرفة')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط الطول')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='المنفذ')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='عنوان MAC')),
                ('connection_type', models.CharField(choices=[('tcp', 'TCP/IP'), ('udp', 'UDP'), ('serial', 'منفذ تسلسلي'), ('usb', 'USB'), ('wifi', 'WiFi'), ('bluetooth', 'Bluetooth'), ('cloud', 'السحابة'), ('api', 'API')], default='tcp', max_length=20, verbose_name='نوع الاتصال')),
                ('connection_string', models.TextField(blank=True, null=True, verbose_name='سلسلة الاتصال')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستخدم')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='كلمة المرور')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح API')),
                ('encryption_enabled', models.BooleanField(default=False, verbose_name='التشفير مفعل')),
                ('status', models.CharField(choices=[('online', 'متصل'), ('offline', 'غير متصل'), ('maintenance', 'صيانة'), ('error', 'خطأ'), ('disabled', 'معطل'), ('testing', 'اختبار')], default='offline', max_length=20, verbose_name='الحالة')),
                ('last_ping', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('max_users', models.PositiveIntegerField(default=1000, verbose_name='الحد الأقصى للمستخدمين')),
                ('max_records', models.PositiveIntegerField(default=100000, verbose_name='الحد الأقصى للسجلات')),
                ('current_users', models.PositiveIntegerField(default=0, verbose_name='المستخدمون الحاليون')),
                ('current_records', models.PositiveIntegerField(default=0, verbose_name='السجلات الحالية')),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='إصدار البرنامج الثابت')),
                ('software_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='إصدار البرنامج')),
                ('last_firmware_update', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث للبرنامج الثابت')),
                ('auto_sync_enabled', models.BooleanField(default=True, verbose_name='المزامنة التلقائية مفعلة')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=15, verbose_name='فترة المزامنة (دقيقة)')),
                ('sync_start_time', models.TimeField(default=datetime.time(0, 0), verbose_name='وقت بداية المزامنة')),
                ('sync_end_time', models.TimeField(default=datetime.time(23, 59), verbose_name='وقت نهاية المزامنة')),
                ('timezone_name', models.CharField(default='Asia/Riyadh', max_length=50, verbose_name='المنطقة الزمنية')),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20, verbose_name='تنسيق التاريخ')),
                ('time_format', models.CharField(default='HH:mm:ss', max_length=20, verbose_name='تنسيق الوقت')),
                ('send_alerts', models.BooleanField(default=True, verbose_name='إرسال التنبيهات')),
                ('alert_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد التنبيهات')),
                ('offline_alert_minutes', models.PositiveIntegerField(default=30, verbose_name='تنبيه انقطاع الاتصال (دقيقة)')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التركيب')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='انتهاء الضمان')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='آخر صيانة')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='الصيانة القادمة')),
                ('maintenance_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الصيانة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_primary', models.BooleanField(default=False, help_text='هل هذا الجهاز الرئيسي للموقع؟', verbose_name='جهاز رئيسي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('configuration', models.JSONField(default=dict, verbose_name='إعدادات الجهاز')),
                ('metadata', models.JSONField(default=dict, verbose_name='بيانات إضافية')),
            ],
            options={
                'verbose_name': 'جهاز حضور محسن',
                'verbose_name_plural': 'أجهزة الحضور المحسنة',
                'db_table': 'hrms_attendance_machine_enhanced',
                'ordering': ['location_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceMachineGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المجموعة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('sync_all_together', models.BooleanField(default=False, verbose_name='مزامنة جماعية')),
                ('shared_configuration', models.JSONField(default=dict, verbose_name='إعدادات مشتركة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مجموعة أجهزة حضور',
                'verbose_name_plural': 'مجموعات أجهزة الحضور',
                'db_table': 'hrms_attendance_machine_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceMachineLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد')),
                ('activity_type', models.CharField(choices=[('ping', 'اختبار اتصال'), ('sync', 'مزامنة'), ('sync_error', 'خطأ مزامنة'), ('reset', 'إعادة تشغيل'), ('reset_error', 'خطأ إعادة تشغيل'), ('clear_data', 'مسح البيانات'), ('clear_error', 'خطأ مسح البيانات'), ('firmware_update', 'تحديث البرنامج الثابت'), ('firmware_error', 'خطأ تحديث البرنامج الثابت'), ('maintenance', 'صيانة'), ('configuration', 'تكوين'), ('status_change', 'تغيير الحالة'), ('user_add', 'إضافة مستخدم'), ('user_delete', 'حذف مستخدم'), ('record_download', 'تحميل السجلات'), ('error', 'خطأ عام')], max_length=20, verbose_name='نوع النشاط')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(max_length=20, verbose_name='الحالة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('data', models.JSONField(default=dict, verbose_name='بيانات إضافية')),
            ],
            options={
                'verbose_name': 'سجل نشاط جهاز الحضور',
                'verbose_name_plural': 'سجلات أنشطة أجهزة الحضور',
                'db_table': 'hrms_attendance_machine_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('total_working_days', models.PositiveIntegerField(default=0, verbose_name='إجمالي أيام العمل')),
                ('present_days', models.PositiveIntegerField(default=0, verbose_name='أيام الحضور')),
                ('absent_days', models.PositiveIntegerField(default=0, verbose_name='أيام الغياب')),
                ('late_days', models.PositiveIntegerField(default=0, verbose_name='أيام التأخير')),
                ('overtime_days', models.PositiveIntegerField(default=0, verbose_name='أيام الوقت الإضافي')),
                ('leave_days', models.PositiveIntegerField(default=0, verbose_name='أيام الإجازة')),
                ('holiday_days', models.PositiveIntegerField(default=0, verbose_name='أيام العطل')),
                ('total_scheduled_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='إجمالي الساعات المجدولة')),
                ('total_actual_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='إجمالي الساعات الفعلية')),
                ('total_regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='إجمالي الساعات العادية')),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='إجمالي ساعات الوقت الإضافي')),
                ('total_late_minutes', models.PositiveIntegerField(default=0, verbose_name='إجمالي دقائق التأخير')),
                ('total_early_departure_minutes', models.PositiveIntegerField(default=0, verbose_name='إجمالي دقائق الانصراف المبكر')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='معدل الحضور')),
                ('punctuality_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='معدل الالتزام بالوقت')),
                ('avg_daily_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='متوسط الساعات اليومية')),
                ('avg_efficiency_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='متوسط نقاط الكفاءة')),
                ('total_regular_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الأجر العادي')),
                ('total_overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي أجر الوقت الإضافي')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الخصومات')),
                ('total_net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي صافي الأجر')),
                ('total_exceptions', models.PositiveIntegerField(default=0, verbose_name='إجمالي الاستثناءات')),
                ('manual_entries', models.PositiveIntegerField(default=0, verbose_name='الإدخالات اليدوية')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ملخص حضور شهري',
                'verbose_name_plural': 'ملخصات الحضور الشهرية',
                'db_table': 'hrms_monthly_attendance_summary',
                'ordering': ['-year', '-month', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='ShiftPatternAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(blank=True, help_text='0=الاثنين, 6=الأحد', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='يوم الأسبوع')),
                ('sequence_order', models.PositiveIntegerField(default=1, verbose_name='ترتيب التسلسل')),
            ],
            options={
                'verbose_name': 'تعيين نمط وردية',
                'verbose_name_plural': 'تعيينات أنماط الورديات',
                'db_table': 'hrms_shift_pattern_assignment',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='ShiftPatternEnhanced',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النمط')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('pattern_type', models.CharField(choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('custom', 'مخصص'), ('rotating', 'متناوب')], default='weekly', max_length=20, verbose_name='نوع النمط')),
                ('rotation_days', models.PositiveIntegerField(default=7, verbose_name='أيام الدوران')),
                ('rotation_order', models.JSONField(default=list, help_text='ترتيب الورديات في الدوران', verbose_name='ترتيب الدوران')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نمط وردية محسن',
                'verbose_name_plural': 'أنماط الورديات المحسنة',
                'db_table': 'hrms_shift_pattern_enhanced',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkShiftEnhanced',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوردية')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الوردية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='بداية الاستراحة')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='نهاية الاستراحة')),
                ('break_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدة الاستراحة (دقيقة)')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, help_text='الوقت المسموح للتأخير بدون احتساب', verbose_name='فترة السماح (دقيقة)')),
                ('early_departure_grace_minutes', models.PositiveIntegerField(default=15, verbose_name='فترة السماح للانصراف المبكر (دقيقة)')),
                ('overtime_threshold_minutes', models.PositiveIntegerField(default=30, help_text='الحد الأدنى لاحتساب الوقت الإضافي', verbose_name='حد الوقت الإضافي (دقيقة)')),
                ('shift_type', models.CharField(choices=[('regular', 'عادية'), ('night', 'ليلية'), ('split', 'منقسمة'), ('flexible', 'مرنة'), ('rotating', 'متناوبة'), ('on_call', 'استدعاء'), ('remote', 'عن بُعد')], default='regular', max_length=20, verbose_name='نوع الوردية')),
                ('is_overnight', models.BooleanField(default=False, help_text='هل تمتد الوردية لليوم التالي؟', verbose_name='وردية ليلية')),
                ('is_flexible', models.BooleanField(default=False, help_text='هل يمكن للموظف اختيار أوقات العمل؟', verbose_name='وردية مرنة')),
                ('flexible_hours_range', models.PositiveIntegerField(default=0, help_text='عدد الساعات المرنة المسموحة', verbose_name='نطاق الساعات المرنة')),
                ('working_days', models.JSONField(default=list, help_text='أيام الأسبوع [0=الاثنين, 6=الأحد]', verbose_name='أيام العمل')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='الموقع')),
                ('allowed_locations', models.JSONField(default=list, help_text='قائمة بالمواقع المسموح بها للحضور', verbose_name='المواقع المسموحة')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=4, verbose_name='معامل الوقت الإضافي')),
                ('weekend_overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.0'), max_digits=4, verbose_name='معامل الوقت الإضافي في العطل')),
                ('max_overtime_hours_daily', models.DecimalField(decimal_places=2, default=Decimal('4.0'), max_digits=4, verbose_name='الحد الأقصى للوقت الإضافي اليومي')),
                ('max_overtime_hours_weekly', models.DecimalField(decimal_places=2, default=Decimal('20.0'), max_digits=4, verbose_name='الحد الأقصى للوقت الإضافي الأسبوعي')),
                ('require_check_in', models.BooleanField(default=True, verbose_name='يتطلب تسجيل دخول')),
                ('require_check_out', models.BooleanField(default=True, verbose_name='يتطلب تسجيل خروج')),
                ('auto_check_out', models.BooleanField(default=False, verbose_name='تسجيل خروج تلقائي')),
                ('auto_check_out_time', models.TimeField(blank=True, null=True, verbose_name='وقت التسجيل التلقائي للخروج')),
                ('late_notification_threshold', models.PositiveIntegerField(default=30, verbose_name='حد إشعار التأخير (دقيقة)')),
                ('absence_notification_time', models.TimeField(blank=True, null=True, verbose_name='وقت إشعار الغياب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, verbose_name='ساري من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='ساري حتى')),
                ('color_code', models.CharField(default='#007bff', help_text='لون الوردية في التقويم', max_length=7, verbose_name='رمز اللون')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='الأيقونة')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='الأولوية')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('metadata', models.JSONField(default=dict, verbose_name='بيانات إضافية')),
            ],
            options={
                'verbose_name': 'وردية محسنة',
                'verbose_name_plural': 'الورديات المحسنة',
                'db_table': 'hrms_work_shift_enhanced',
                'ordering': ['sort_order', 'start_time'],
            },
        ),
        migrations.RenameModel(
            old_name='EmployeeDocument',
            new_name='EmployeeDocumentEnhanced',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='machine',
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='verified_by',
        ),
        migrations.AlterUniqueTogether(
            name='employeeemergencycontact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeemergencycontact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeeemergencycontact',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeetraining',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='employeetraining',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeetraining',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='attendancemachine',
            options={'verbose_name': 'جهاز حضور', 'verbose_name_plural': 'أجهزة الحضور'},
        ),
        migrations.AlterModelOptions(
            name='attendancesummaryenhanced',
            options={'ordering': ['-date', 'employee'], 'verbose_name': 'ملخص حضور محسن', 'verbose_name_plural': 'ملخصات الحضور المحسنة'},
        ),
        migrations.AlterModelOptions(
            name='employeeshiftassignmentenhanced',
            options={'ordering': ['-start_date'], 'verbose_name': 'تعيين وردية محسن', 'verbose_name_plural': 'تعيينات الورديات المحسنة'},
        ),
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'verbose_name': 'تعيين وردية', 'verbose_name_plural': 'تعيينات الورديات'},
        ),
        migrations.AlterModelOptions(
            name='workshift',
            options={'verbose_name': 'وردية', 'verbose_name_plural': 'الورديات'},
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecordenhanced',
            name='unique_employee_date_attendance',
        ),
        migrations.RemoveConstraint(
            model_name='attendancesummaryenhanced',
            name='unique_employee_period_summary',
        ),
        migrations.RemoveConstraint(
            model_name='employeeshiftassignmentenhanced',
            name='unique_employee_shift_start_date',
        ),
        migrations.RemoveIndex(
            model_name='attendancemachine',
            name='Hr_attendan_ip_addr_3d96fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancemachine',
            name='Hr_attendan_status_89d024_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancemachine',
            name='Hr_attendan_branch__c114b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancemachine',
            name='Hr_attendan_is_acti_61035a_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancemachine',
            name='Hr_attendan_serial__2ffd03_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecordenhanced',
            name='hrms_attendance_record_enhanced_is_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecordenhanced',
            name='hrms_attendance_record_enhanced_has_exception_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecordenhanced',
            name='hrms_attendance_record_enhanced_assigned_shift_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecordenhanced',
            name='hrms_attendance_record_enhanced_check_in_machine_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecordenhanced',
            name='hrms_attendance_record_enhanced_check_out_machine_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancesummaryenhanced',
            name='hrms_attendance_summary_enhanced_employee_period_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancesummaryenhanced',
            name='hrms_attendance_summary_enhanced_period_start_end_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancesummaryenhanced',
            name='hrms_attendance_summary_enhanced_year_month_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancesummaryenhanced',
            name='hrms_attendance_summary_enhanced_attendance_rate_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancesummaryenhanced',
            name='hrms_attendance_summary_enhanced_is_processed_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancesummaryenhanced',
            name='hrms_attendance_summary_enhanced_needs_review_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeshiftassignmentenhanced',
            name='hrms_employee_shift_assignment_enhanced_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeshiftassignmentenhanced',
            name='hrms_employee_shift_assignment_enhanced_assignment_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeshiftassignmentenhanced',
            name='hrms_employee_shift_assignment_enhanced_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='machineuser',
            name='Hr_machineu_machine_e80812_idx',
        ),
        migrations.RemoveIndex(
            model_name='machineuser',
            name='Hr_machineu_employe_ca84dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='machineuser',
            name='Hr_machineu_is_enro_9076f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftassignment',
            name='Hr_shiftass_employe_800d9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftassignment',
            name='Hr_shiftass_shift_i_9c2bf7_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftassignment',
            name='Hr_shiftass_start_d_3375d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='workshift',
            name='Hr_workshif_shift_t_b0e142_idx',
        ),
        migrations.RemoveIndex(
            model_name='workshift',
            name='Hr_workshif_status_f51df4_idx',
        ),
        migrations.RemoveIndex(
            model_name='workshift',
            name='Hr_workshif_start_t_3dd204_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecordenhanced',
            new_name='hrms_attend_employe_f33dee_idx',
            old_name='hrms_attendance_record_enhanced_employee_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecordenhanced',
            new_name='hrms_attend_status_e6a740_idx',
            old_name='hrms_attendance_record_enhanced_status_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecordenhanced',
            new_name='hrms_attend_created_83f655_idx',
            old_name='hrms_attendance_record_enhanced_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeenhanced',
            new_name='hrms_employ_company_6bf0f0_idx',
            old_name='Hr_employee_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeenhanced',
            new_name='hrms_employ_employe_63006b_idx',
            old_name='Hr_employee_id_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeenhanced',
            new_name='hrms_employ_nationa_65c453_idx',
            old_name='Hr_employee_national_id_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeenhanced',
            new_name='hrms_employ_departm_8ec970_idx',
            old_name='Hr_employee_department_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeenhanced',
            new_name='hrms_employ_positio_fabc13_idx',
            old_name='Hr_employee_position_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeenhanced',
            new_name='hrms_employ_join_da_f1f24b_idx',
            old_name='Hr_employee_join_date_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeenhanced',
            new_name='hrms_employ_status_65e597_idx',
            old_name='Hr_employee_status_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeenhanced',
            new_name='hrms_employ_employm_6fad93_idx',
            old_name='Hr_employee_employment_type_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeenhanced',
            new_name='hrms_employ_direct__739f26_idx',
            old_name='Hr_employee_direct_manager_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeshiftassignmentenhanced',
            new_name='hrms_employ_employe_1dcd02_idx',
            old_name='hrms_employee_shift_assignment_enhanced_employee_active_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeshiftassignmentenhanced',
            new_name='hrms_employ_shift_i_8f10b1_idx',
            old_name='hrms_employee_shift_assignment_enhanced_shift_active_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeshiftassignmentenhanced',
            new_name='hrms_employ_start_d_4658ee_idx',
            old_name='hrms_employee_shift_assignment_enhanced_start_end_date_idx',
        ),
        migrations.RenameIndex(
            model_name='employeetrainingenhanced',
            new_name='hrms_employ_employe_3d3c5c_idx',
            old_name='hrms_employee_training_enhanced_employee_status_idx',
        ),
        migrations.RenameIndex(
            model_name='employeetrainingenhanced',
            new_name='hrms_employ_start_d_b9a266_idx',
            old_name='hrms_employee_training_enhanced_start_end_date_idx',
        ),
        migrations.RenameIndex(
            model_name='employeetrainingenhanced',
            new_name='hrms_employ_categor_007ed0_idx',
            old_name='hrms_employee_training_enhanced_category_idx',
        ),
        migrations.RenameIndex(
            model_name='employeetrainingenhanced',
            new_name='hrms_employ_provide_a82ee6_idx',
            old_name='hrms_employee_training_enhanced_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='employeetrainingenhanced',
            new_name='hrms_employ_priorit_015973_idx',
            old_name='hrms_employee_training_enhanced_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='employeetrainingenhanced',
            new_name='hrms_employ_certifi_f00a8e_idx',
            old_name='hrms_employee_training_enhanced_cert_expiry_idx',
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='department',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='firmware_version',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='is_entry_device',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='is_exit_device',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='last_ping_time',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='last_sync_time',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='max_records',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='model',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='port',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='sync_interval_minutes',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='machineuser',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='machineuser',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='machineuser',
            name='face_template_exists',
        ),
        migrations.RemoveField(
            model_name='machineuser',
            name='fingerprint_templates',
        ),
        migrations.RemoveField(
            model_name='machineuser',
            name='is_enrolled',
        ),
        migrations.RemoveField(
            model_name='machineuser',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='machineuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='break_end_time',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='break_start_time',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='grace_period_minutes',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='overtime_threshold_minutes',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='total_hours',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='absence_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='خصم الغياب'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت النهاية الفعلي'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='الساعات الفعلية'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت البداية الفعلي'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_summaries', to=settings.AUTH_USER_MODEL, verbose_name='معتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ساعات الاستراحة'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='check_in_method',
            field=models.CharField(blank=True, choices=[('fingerprint', 'بصمة الإصبع'), ('face', 'التعرف على الوجه'), ('card', 'البطاقة'), ('pin', 'رمز PIN'), ('manual', 'يدوي'), ('mobile', 'تطبيق الجوال'), ('web', 'الموقع الإلكتروني')], max_length=20, null=True, verbose_name='طريقة تسجيل الدخول'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='check_out_method',
            field=models.CharField(blank=True, choices=[('fingerprint', 'بصمة الإصبع'), ('face', 'التعرف على الوجه'), ('card', 'البطاقة'), ('pin', 'رمز PIN'), ('manual', 'يدوي'), ('mobile', 'تطبيق الجوال'), ('web', 'الموقع الإلكتروني')], max_length=20, null=True, verbose_name='طريقة تسجيل الخروج'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='early_departure_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='دقائق الانصراف المبكر'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='exception_types',
            field=models.JSONField(default=list, verbose_name='أنواع الاستثناءات'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='has_exception',
            field=models.BooleanField(default=False, verbose_name='يحتوي على استثناء'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='is_manual_entry',
            field=models.BooleanField(default=False, verbose_name='إدخال يدوي'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='late_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='خصم التأخير'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='دقائق التأخير'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.leaverequest', verbose_name='طلب الإجازة'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.leavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='صافي الأجر'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ساعات الوقت الإضافي'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='أجر الوقت الإضافي'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='الساعات العادية'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='regular_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الأجر العادي'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='يتطلب موافقة'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت النهاية المجدول'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='scheduled_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='الساعات المجدولة'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت البداية المجدول'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('early_departure', 'انصراف مبكر'), ('half_day', 'نصف يوم'), ('overtime', 'وقت إضافي'), ('holiday', 'عطلة'), ('leave', 'إجازة'), ('sick_leave', 'إجازة مرضية'), ('business_trip', 'مهمة عمل'), ('training', 'تدريب'), ('work_from_home', 'عمل من المنزل'), ('pending', 'في انتظار المراجعة')], default='present', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='supervisor_comments',
            field=models.TextField(blank=True, null=True, verbose_name='تعليقات المشرف'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='tasks_assigned',
            field=models.PositiveIntegerField(default=0, verbose_name='المهام المعينة'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='المهام المكتملة'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة الحرارة'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='إجمالي الخصومات'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='إجمالي الأجر'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حالة الطقس'),
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='work_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='موقع العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الطول (سم)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='languages_spoken',
            field=models.TextField(blank=True, help_text='فصل بين اللغات بفاصلة', null=True, verbose_name='اللغات المتحدث بها'),
        ),
        migrations.AddField(
            model_name='employee',
            name='military_service_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الخدمة العسكرية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='military_service_status',
            field=models.CharField(blank=True, choices=[('completed', 'مكتملة'), ('exempted', 'معفى'), ('postponed', 'مؤجلة'), ('not_applicable', 'غير مطلوبة')], max_length=20, null=True, verbose_name='حالة الخدمة العسكرية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=200, null=True, verbose_name='اسم الأم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الأطفال'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن (كغ)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الجهاز'),
        ),
        migrations.AlterField(
            model_name='employeebank',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='Hr.employeeenhanced', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='Hr.employeeenhanced', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeeeducationenhanced',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeeemergencycontactenhanced',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeeenhanced',
            name='date_of_birth',
            field=models.DateField(validators=[Hr.models.employee.employee_models_enhanced.validate_birth_date], verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='Hr.employeeenhanced', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='Hr.employeeenhanced', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeefileaccesslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeefilecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeefileenhanced',
            name='file',
            field=models.FileField(upload_to=Hr.models.employee.employee_file_models.employee_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'xls', 'xlsx', 'csv', 'ppt', 'pptx', 'zip', 'rar', '7z'])], verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='employeefileenhanced',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeeinsuranceenhanced',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeevehicleenhanced',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machineuser',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.employeeenhanced', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='machineuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machineuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='machineuser',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.attendancemachine', verbose_name='الجهاز'),
        ),
        migrations.AlterField(
            model_name='machineuser',
            name='user_id',
            field=models.CharField(max_length=50, verbose_name='معرف المستخدم في الجهاز'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.employeeenhanced', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.workshift', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='end_time',
            field=models.TimeField(verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='is_overnight',
            field=models.BooleanField(default=False, verbose_name='وردية ليلية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الوردية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البداية'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecordenhanced',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummaryenhanced',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeemergencycontactenhanced',
            unique_together={('employee', 'priority')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeshiftassignmentenhanced',
            unique_together={('employee', 'shift', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='attendancesummaryenhanced',
            index=models.Index(fields=['employee', 'date'], name='hrms_attend_employe_84dd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummaryenhanced',
            index=models.Index(fields=['status'], name='hrms_attend_status_12a30a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummaryenhanced',
            index=models.Index(fields=['is_verified'], name='hrms_attend_is_veri_3e5096_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummaryenhanced',
            index=models.Index(fields=['has_exception'], name='hrms_attend_has_exc_15008f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummaryenhanced',
            index=models.Index(fields=['requires_approval'], name='hrms_attend_require_322a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummaryenhanced',
            index=models.Index(fields=['assigned_shift'], name='hrms_attend_assigne_517e57_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummaryenhanced',
            index=models.Index(fields=['leave_type'], name='hrms_attend_leave_t_7d1ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummaryenhanced',
            index=models.Index(fields=['created_at'], name='hrms_attend_created_d70f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeeducationenhanced',
            index=models.Index(fields=['employee'], name='Hr_employee_employe_f460e7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeeducationenhanced',
            index=models.Index(fields=['degree_type'], name='Hr_employee_degree__11dda4_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeeducationenhanced',
            index=models.Index(fields=['graduation_year'], name='Hr_employee_graduat_6f1aab_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeeducationenhanced',
            index=models.Index(fields=['is_verified'], name='Hr_employee_is_veri_4023ed_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeeducationenhanced',
            index=models.Index(fields=['country'], name='Hr_employee_country_57ab28_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeeducationenhanced',
            index=models.Index(fields=['is_relevant_to_job'], name='Hr_employee_is_rele_b80596_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeemergencycontactenhanced',
            index=models.Index(fields=['employee', 'priority'], name='hrms_employ_employe_0e6341_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeemergencycontactenhanced',
            index=models.Index(fields=['is_primary'], name='hrms_employ_is_prim_a3d5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeemergencycontactenhanced',
            index=models.Index(fields=['is_active'], name='hrms_employ_is_acti_eaf2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefileaccesslog',
            index=models.Index(fields=['file', 'timestamp'], name='hrms_employ_file_id_916a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefileaccesslog',
            index=models.Index(fields=['user', 'timestamp'], name='hrms_employ_user_id_51357e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefileaccesslog',
            index=models.Index(fields=['action'], name='hrms_employ_action_aec360_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefileenhanced',
            index=models.Index(fields=['employee', 'category'], name='hrms_employ_employe_d8afe1_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefileenhanced',
            index=models.Index(fields=['status'], name='hrms_employ_status_3780e3_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefileenhanced',
            index=models.Index(fields=['access_level'], name='hrms_employ_access__bc5c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefileenhanced',
            index=models.Index(fields=['expiry_date'], name='hrms_employ_expiry__456a16_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefileenhanced',
            index=models.Index(fields=['file_hash'], name='hrms_employ_file_ha_d93f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefileenhanced',
            index=models.Index(fields=['created_at'], name='hrms_employ_created_71d9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinsuranceenhanced',
            index=models.Index(fields=['employee'], name='Hr_employee_employe_883c18_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinsuranceenhanced',
            index=models.Index(fields=['insurance_type'], name='Hr_employee_insuran_5a1038_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinsuranceenhanced',
            index=models.Index(fields=['policy_number'], name='Hr_employee_policy__57eb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinsuranceenhanced',
            index=models.Index(fields=['status'], name='Hr_employee_status_c548b8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinsuranceenhanced',
            index=models.Index(fields=['end_date'], name='Hr_employee_end_dat_28fba3_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinsuranceenhanced',
            index=models.Index(fields=['renewal_date'], name='Hr_employee_renewal_e49215_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinsuranceenhanced',
            index=models.Index(fields=['provider'], name='Hr_employee_provide_3e7bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevehicleenhanced',
            index=models.Index(fields=['employee'], name='Hr_employee_employe_f889ea_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevehicleenhanced',
            index=models.Index(fields=['license_plate'], name='Hr_employee_license_5ca4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevehicleenhanced',
            index=models.Index(fields=['vehicle_type'], name='Hr_employee_vehicle_f446df_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevehicleenhanced',
            index=models.Index(fields=['status'], name='Hr_employee_status_0ae9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevehicleenhanced',
            index=models.Index(fields=['insurance_expiry'], name='Hr_employee_insuran_400c66_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevehicleenhanced',
            index=models.Index(fields=['registration_expiry'], name='Hr_employee_registr_e9ddd8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevehicleenhanced',
            index=models.Index(fields=['make', 'model'], name='Hr_employee_make_588898_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevehicleenhanced',
            index=models.Index(fields=['year'], name='Hr_employee_year_b64888_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeeducationenhanced',
            constraint=models.CheckConstraint(check=models.Q(('start_year__lte', models.F('graduation_year'))), name='start_before_graduation'),
        ),
        migrations.AddConstraint(
            model_name='employeeeducationenhanced',
            constraint=models.CheckConstraint(check=models.Q(('class_rank__lte', models.F('class_size'))), name='rank_within_class_size'),
        ),
        migrations.AddConstraint(
            model_name='employeeinsuranceenhanced',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='end_after_start_insurance'),
        ),
        migrations.AddConstraint(
            model_name='employeeinsuranceenhanced',
            constraint=models.CheckConstraint(check=models.Q(('employee_contribution__lte', models.F('premium_amount'))), name='employee_contribution_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeeinsuranceenhanced',
            constraint=models.CheckConstraint(check=models.Q(('employer_contribution__lte', models.F('premium_amount'))), name='employer_contribution_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeevehicleenhanced',
            constraint=models.CheckConstraint(check=models.Q(('return_date__gte', models.F('assigned_date'))), name='return_after_assignment'),
        ),
        migrations.AddConstraint(
            model_name='employeevehicleenhanced',
            constraint=models.CheckConstraint(check=models.Q(('current_value__lte', models.F('purchase_price'))), name='current_value_realistic'),
        ),
        migrations.AlterModelTable(
            name='attendancemachine',
            table='hrms_attendance_machine',
        ),
        migrations.AlterModelTable(
            name='employeesalaryitem',
            table='Hr_EmployeeSalaryItem',
        ),
        migrations.AlterModelTable(
            name='machineuser',
            table='hrms_machine_user',
        ),
        migrations.AlterModelTable(
            name='salaryitem',
            table='Hr_SalaryItem',
        ),
        migrations.AlterModelTable(
            name='shiftassignment',
            table='hrms_shift_assignment',
        ),
        migrations.AlterModelTable(
            name='workshift',
            table='hrms_work_shift',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='AttendanceSummary',
        ),
        migrations.DeleteModel(
            name='EmployeeEducation',
        ),
        migrations.DeleteModel(
            name='EmployeeEmergencyContact',
        ),
        migrations.DeleteModel(
            name='EmployeeTraining',
        ),
        migrations.AddField(
            model_name='workshiftenhanced',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_shifts', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='workshiftenhanced',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_shifts', to='Hr.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='shiftpatternenhanced',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='shiftpatternenhanced',
            name='shifts',
            field=models.ManyToManyField(through='Hr.ShiftPatternAssignment', to='Hr.workshiftenhanced', verbose_name='الورديات'),
        ),
        migrations.AddField(
            model_name='shiftpatternassignment',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_assignments', to='Hr.shiftpatternenhanced', verbose_name='النمط'),
        ),
        migrations.AddField(
            model_name='shiftpatternassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.workshiftenhanced', verbose_name='الوردية'),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendance_summaries', to='Hr.employeeenhanced', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اكتمل بواسطة'),
        ),
        migrations.AddField(
            model_name='attendancemachinelog',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='Hr.attendancemachineenhanced', verbose_name='الجهاز'),
        ),
        migrations.AddField(
            model_name='attendancemachinelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='attendancemachinegroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='attendancemachinegroup',
            name='machines',
            field=models.ManyToManyField(related_name='machine_groups', to='Hr.attendancemachineenhanced', verbose_name='الأجهزة'),
        ),
        migrations.AddField(
            model_name='attendancemachineenhanced',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='accessible_machines', to='Hr.department', verbose_name='الأقسام المسموحة'),
        ),
        migrations.AddField(
            model_name='attendancemachineenhanced',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_machines', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='attendancemachineenhanced',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_machines', to='Hr.department', verbose_name='القسم'),
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='assigned_shift',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='break_end_time',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='break_hours',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='break_start_time',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='check_in_location',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='check_in_machine',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='check_in_method',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='check_out_location',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='check_out_machine',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='check_out_method',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='exception_notes',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='exception_type',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='has_exception',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='is_manual_entry',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='manual_entry_reason',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='productivity_score',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='remote_work_approved',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='tasks_completed',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='weather_condition',
        ),
        migrations.RemoveField(
            model_name='attendancerecordenhanced',
            name='work_from_home',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='absent_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='attendance_rate',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='attendance_trend',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='avg_daily_hours',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='avg_late_minutes',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='business_trip_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='early_departure_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='expected_hours',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='half_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='holiday_work_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='late_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='manual_entries',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='month',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='most_common_check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='most_common_check_out_time',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='needs_review',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='overtime_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='present_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='processing_date',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='punctuality_rate',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='remote_work_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='sick_leave_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='total_break_hours',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='total_early_departure_minutes',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='total_exceptions',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='total_hours_worked',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='total_late_minutes',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='total_overtime_hours',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='total_regular_hours',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='total_working_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='training_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='trend_percentage',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='unverified_records',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='vacation_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='week',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='weekend_work_days',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryenhanced',
            name='year',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='notification_sent',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='notification_sent_at',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='notify_employee',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignmentenhanced',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='attendancesummaryenhanced',
            name='assigned_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.workshiftenhanced', verbose_name='الوردية المعينة'),
        ),
        migrations.AddIndex(
            model_name='workshiftenhanced',
            index=models.Index(fields=['is_active'], name='hrms_work_s_is_acti_7ec1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='workshiftenhanced',
            index=models.Index(fields=['shift_type'], name='hrms_work_s_shift_t_2cfe81_idx'),
        ),
        migrations.AddIndex(
            model_name='workshiftenhanced',
            index=models.Index(fields=['department'], name='hrms_work_s_departm_912475_idx'),
        ),
        migrations.AddIndex(
            model_name='workshiftenhanced',
            index=models.Index(fields=['effective_from', 'effective_to'], name='hrms_work_s_effecti_fc8fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='workshiftenhanced',
            index=models.Index(fields=['start_time', 'end_time'], name='hrms_work_s_start_t_5c4bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='workshiftenhanced',
            index=models.Index(fields=['priority'], name='hrms_work_s_priorit_5fc9ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftpatternassignment',
            unique_together={('pattern', 'day_of_week'), ('pattern', 'sequence_order')},
        ),
        migrations.AddIndex(
            model_name='monthlyattendancesummary',
            index=models.Index(fields=['employee', 'year', 'month'], name='hrms_monthl_employe_67a4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyattendancesummary',
            index=models.Index(fields=['year', 'month'], name='hrms_monthl_year_0f3f51_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyattendancesummary',
            index=models.Index(fields=['is_finalized'], name='hrms_monthl_is_fina_e58379_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyattendancesummary',
            unique_together={('employee', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='attendancemachinelog',
            index=models.Index(fields=['machine', 'timestamp'], name='hrms_attend_machine_f7182a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachinelog',
            index=models.Index(fields=['activity_type'], name='hrms_attend_activit_ce76e4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachinelog',
            index=models.Index(fields=['status'], name='hrms_attend_status_06b400_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachinelog',
            index=models.Index(fields=['timestamp'], name='hrms_attend_timesta_6cd2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachineenhanced',
            index=models.Index(fields=['status'], name='hrms_attend_status_bedf89_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachineenhanced',
            index=models.Index(fields=['is_active'], name='hrms_attend_is_acti_6ddb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachineenhanced',
            index=models.Index(fields=['machine_type'], name='hrms_attend_machine_f46a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachineenhanced',
            index=models.Index(fields=['department'], name='hrms_attend_departm_f5f3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachineenhanced',
            index=models.Index(fields=['ip_address'], name='hrms_attend_ip_addr_e071be_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachineenhanced',
            index=models.Index(fields=['serial_number'], name='hrms_attend_serial__dce4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachineenhanced',
            index=models.Index(fields=['last_ping'], name='hrms_attend_last_pi_9222a3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachineenhanced',
            index=models.Index(fields=['last_sync'], name='hrms_attend_last_sy_9f7863_idx'),
        ),
    ]
