# Generated by Django 4.2.7 on 2025-08-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0036_attendancemachineenhanced_attendancemachinegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name_english',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الكود'),
        ),
        migrations.AddField(
            model_name='company',
            name='commercial_register',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_english',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي (متوافق)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_hr_manager',
            field=models.BooleanField(default=False, verbose_name='مدير موارد بشرية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_hr_staff',
            field=models.BooleanField(default=False, verbose_name='موظف موارد بشرية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='مدير'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري الداخلي'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة/الولاية'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي الداخلي'),
        ),
    ]
