# Generated by Django 5.0.14 on 2025-07-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0007_alter_department_created_at_and_more'),
    ]

    operations = [
    ]
