# Generated by Django 5.0.14 on 2025-07-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0011_fixed_legacyemployee_only'),
        ('Hr', '0011_legacyemployee_remove_job_is_active_remove_job_note_and_more'),
    ]

    operations = [
    ]
