# Generated by Django 5.0.14 on 2025-07-15 06:37
# Create the missing Tbl_Jop table

import django.db.models.deletion
from django.db import migrations, models


def create_job_table(apps, schema_editor):
    """Create the Tbl_Jop table manually using raw SQL"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE Tbl_Jop (
                Jop_Code int NOT NULL PRIMARY KEY,
                Jop_Name nvarchar(50) NOT NULL,
                Dept_Code int NULL,
                FOREIGN KEY (Dept_Code) REFERENCES Tbl_Department(dept_code)
            )
        """)


def drop_job_table(apps, schema_editor):
    """Drop the Tbl_Jop table"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS Tbl_Jop")


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0013_remove_job_is_active_remove_job_note_job_department_and_more'),
    ]

    operations = [
        # Create the table using raw SQL
        migrations.RunPython(
            create_job_table,
            drop_job_table,
        ),

        # Now create the Django model to match the table
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jop_code', models.IntegerField(db_column='Jop_Code', primary_key=True, serialize=False, verbose_name='رمز الوظيفة')),
                ('jop_name', models.CharField(db_column='Jop_Name', max_length=50, verbose_name='اسم الوظيفة')),
                ('department', models.ForeignKey(blank=True, db_column='Dept_Code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.legacydepartment', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'الوظيفة',
                'verbose_name_plural': 'الوظائف',
                'db_table': 'Tbl_Jop',
                'managed': True,
            },
        ),
    ]
