# Generated by Django 5.0.14 on 2025-07-18 12:04

import Hr.models.employee.employee_models
from encrypted_model_fields.fields import EncryptedCharField
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0014_create_job_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف')),
                ('user_id', models.CharField(help_text='معرف الموظف في جهاز الحضور', max_length=20, verbose_name='معرف المستخدم في الجهاز')),
                ('is_enrolled', models.BooleanField(default=False, help_text='هل تم تسجيل الموظف في الجهاز؟', verbose_name='مسجل')),
                ('enrollment_date', models.DateTimeField(blank=True, help_text='تاريخ تسجيل الموظف في الجهاز', null=True, verbose_name='تاريخ التسجيل')),
                ('fingerprint_templates', models.PositiveIntegerField(default=0, help_text='عدد قوالب البصمة المسجلة', verbose_name='عدد قوالب البصمة')),
                ('face_template_exists', models.BooleanField(default=False, help_text='هل يوجد قالب للوجه؟', verbose_name='قالب الوجه موجود')),
                ('card_number', models.CharField(blank=True, help_text='رقم بطاقة الموظف', max_length=20, verbose_name='رقم البطاقة')),
                ('pin_code', models.CharField(blank=True, help_text='رمز PIN للموظف', max_length=10, verbose_name='رمز PIN')),
                ('is_active', models.BooleanField(default=True, help_text='هل المستخدم نشط في الجهاز؟', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مستخدم جهاز',
                'verbose_name_plural': 'مستخدمو الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف')),
                ('assignment_type', models.CharField(choices=[('permanent', 'دائم'), ('temporary', 'مؤقت'), ('rotating', 'متناوب')], default='permanent', max_length=20, verbose_name='نوع التعيين')),
                ('start_date', models.DateField(help_text='تاريخ بداية تعيين الوردية', verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, help_text='تاريخ نهاية تعيين الوردية (اختياري للتعيين الدائم)', null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, help_text='هل هذا التعيين نشط؟', verbose_name='نشط')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية حول تعيين الوردية', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تعيين وردية',
                'verbose_name_plural': 'تعيينات الورديات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeshiftassignment',
            name='work_shift',
        ),
        migrations.AlterModelOptions(
            name='attendancemachine',
            options={'ordering': ['location', 'name'], 'verbose_name': 'جهاز حضور', 'verbose_name_plural': 'أجهزة الحضور'},
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-timestamp'], 'verbose_name': 'سجل حضور', 'verbose_name_plural': 'سجلات الحضور'},
        ),
        migrations.AlterModelOptions(
            name='attendancesummary',
            options={'ordering': ['-date'], 'verbose_name': 'ملخص حضور يومي', 'verbose_name_plural': 'ملخصات الحضور اليومية'},
        ),
        migrations.RemoveIndex(
            model_name='attendancemachine',
            name='hrms_attend_device__2463d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='hrms_attend_employe_05d53e_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='hrms_attend_record__075871_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='hrms_attend_record__f2def1_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancesummary',
            name='hrms_attend_is_proc_dd2215_idx',
        ),
        migrations.RemoveIndex(
            model_name='workshift',
            name='hrms_work_s_code_63c6f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='workshift',
            name='hrms_work_s_is_acti_54be2a_idx',
        ),
        migrations.RenameField(
            model_name='attendancesummary',
            old_name='late_arrival_minutes',
            new_name='late_minutes',
        ),
        migrations.RenameIndex(
            model_name='attendancemachine',
            new_name='Hr_attendan_status_89d024_idx',
            old_name='hrms_attend_status_784a25_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancemachine',
            new_name='Hr_attendan_branch__c114b9_idx',
            old_name='hrms_attend_branch__f98d05_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancemachine',
            new_name='Hr_attendan_ip_addr_3d96fd_idx',
            old_name='hrms_attend_ip_addr_e458a5_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='Hr_attendan_machine_1dba2a_idx',
            old_name='hrms_attend_machine_8e4e85_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='Hr_attendan_status_3b5834_idx',
            old_name='hrms_attend_status_293f75_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancesummary',
            new_name='Hr_attendan_employe_22bcbf_idx',
            old_name='hrms_attend_employe_c71f86_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancesummary',
            new_name='Hr_attendan_date_e618f9_idx',
            old_name='hrms_attend_date_597201_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancesummary',
            new_name='Hr_attendan_status_fc1996_idx',
            old_name='hrms_attend_status_c26732_idx',
        ),
        migrations.RenameIndex(
            model_name='workshift',
            new_name='Hr_workshif_shift_t_b0e142_idx',
            old_name='hrms_work_s_shift_t_7bbf13_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='auto_sync_enabled',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='current_records',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='current_users',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='device_settings',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='last_online_time',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='last_sync_status',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='maintenance_notes',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='max_fingerprints',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='next_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='password',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='supports_card',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='supports_face_recognition',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='supports_fingerprint',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='supports_password',
        ),
        migrations.RemoveField(
            model_name='attendancemachine',
            name='warranty_expiry_date',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='calculation_details',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='exceptions',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='first_in_time',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='has_incomplete_punches',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='in_punches',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='is_working_day',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='last_out_time',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='leave_hours',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='leave_request',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='out_punches',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='scheduled_in_time',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='scheduled_out_time',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='total_punches',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='total_work_hours',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='work_shift',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='auto_check_out',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='break_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='code',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='early_leave_grace_minutes',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='is_night_shift',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='late_grace_minutes',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='max_overtime_hours',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='minimum_hours_for_full_day',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='minimum_hours_for_half_day',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='requires_check_in',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='requires_check_out',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='brand',
            field=models.CharField(blank=True, help_text='مثال: ZKTeco, Hikvision', max_length=50, verbose_name='الماركة'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='connection_type',
            field=models.CharField(choices=[('tcp_ip', 'TCP/IP'), ('usb', 'USB'), ('serial', 'Serial'), ('wifi', 'WiFi'), ('ethernet', 'Ethernet')], default='tcp_ip', max_length=20, verbose_name='نوع الاتصال'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='department',
            field=models.ForeignKey(blank=True, help_text='القسم المخصص له الجهاز (اختياري)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_machines', to='Hr.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='last_ping_time',
            field=models.DateTimeField(blank=True, help_text='آخر وقت فحص اتصال', null=True, verbose_name='آخر ping'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='location',
            field=models.CharField(default='غير محدد', help_text='موقع الجهاز (مثال: المدخل الرئيسي، الطابق الثاني)', max_length=200, verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='machine_type',
            field=models.CharField(choices=[('fingerprint', 'بصمة الإصبع'), ('face_recognition', 'التعرف على الوجه'), ('card_reader', 'قارئ البطاقات'), ('pin_code', 'رمز PIN'), ('hybrid', 'مختلط')], default='fingerprint', max_length=20, verbose_name='نوع الجهاز'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='name_en',
            field=models.CharField(blank=True, help_text='Main Entrance Attendance Machine', max_length=100, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='notes',
            field=models.TextField(blank=True, help_text='ملاحظات إضافية حول الجهاز', verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='timezone',
            field=models.CharField(default='Asia/Riyadh', help_text='المنطقة الزمنية للجهاز', max_length=50, verbose_name='المنطقة الزمنية'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='تاريخ الحضور (يتم حسابه تلقائياً)', verbose_name='التاريخ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='هل تم إدخال هذا السجل يدوياً؟', verbose_name='يدوي'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='وقت الحضور (يتم حسابه تلقائياً)', verbose_name='الوقت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='وقت وتاريخ تسجيل الحضور', verbose_name='الوقت والتاريخ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الدخول'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الخروج'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='is_leave',
            field=models.BooleanField(default=False, help_text='هل الموظف في إجازة؟', verbose_name='إجازة'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='leave_type',
            field=models.CharField(blank=True, help_text='نوع الإجازة إذا كان في إجازة', max_length=50, verbose_name='نوع الإجازة'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_summaries', to='Hr.workshift', verbose_name='الوردية'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='إجمالي الساعات'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=15, help_text='فترة السماح للتأخير بالدقائق', verbose_name='فترة السماح (دقيقة)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='is_overnight',
            field=models.BooleanField(default=False, help_text='هل تمتد الوردية لليوم التالي؟', verbose_name='وردية ليلية'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='name_en',
            field=models.CharField(blank=True, help_text='Morning Shift', max_length=100, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_machines', to='Hr.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='firmware_version',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='إصدار firmware الجهاز', max_length=50, verbose_name='إصدار البرنامج الثابت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='عنوان IP للجهاز (للاتصال الشبكي)', null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل الجهاز نشط؟', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='is_entry_device',
            field=models.BooleanField(default=True, help_text='هل يستخدم لتسجيل الدخول؟', verbose_name='جهاز دخول'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='is_exit_device',
            field=models.BooleanField(default=True, help_text='هل يستخدم لتسجيل الخروج؟', verbose_name='جهاز خروج'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, help_text='آخر وقت مزامنة مع الجهاز', null=True, verbose_name='آخر مزامنة'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='max_records',
            field=models.PositiveIntegerField(default=100000, help_text='الحد الأقصى لعدد سجلات الحضور', verbose_name='الحد الأقصى للسجلات'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='max_users',
            field=models.PositiveIntegerField(default=1000, help_text='الحد الأقصى لعدد المستخدمين المسجلين', verbose_name='الحد الأقصى للمستخدمين'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='model',
            field=models.CharField(blank=True, help_text='رقم موديل الجهاز', max_length=50, verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='name',
            field=models.CharField(help_text='مثال: جهاز الحضور - المدخل الرئيسي', max_length=100, verbose_name='اسم الجهاز'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=4370, help_text='منفذ الاتصال (افتراضي: 4370)', null=True, verbose_name='المنفذ'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='serial_number',
            field=models.CharField(help_text='الرقم التسلسلي للجهاز', max_length=100, unique=True, verbose_name='الرقم التسلسلي'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='status',
            field=models.CharField(choices=[('online', 'متصل'), ('offline', 'غير متصل'), ('maintenance', 'صيانة'), ('error', 'خطأ'), ('disabled', 'معطل')], default='offline', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=15, help_text='فترة المزامنة التلقائية بالدقائق', verbose_name='فترة المزامنة (دقيقة)'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='device_user_id',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='معرف الموظف في جهاز الحضور', max_length=20, verbose_name='معرف المستخدم في الجهاز'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='هل تم معالجة هذا السجل؟', verbose_name='تم المعالجة'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True, default=django.utils.timezone.now, help_text='ملاحظات إضافية حول السجل', verbose_name='ملاحظات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='raw_data',
            field=models.TextField(blank=True, help_text='البيانات الخام من الجهاز', verbose_name='البيانات الخام'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='record_type',
            field=models.CharField(choices=[('check_in', 'دخول'), ('check_out', 'خروج'), ('break_out', 'خروج استراحة'), ('break_in', 'عودة من الاستراحة'), ('overtime_in', 'دخول وقت إضافي'), ('overtime_out', 'خروج وقت إضافي')], max_length=20, verbose_name='نوع السجل'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('valid', 'صحيح'), ('invalid', 'غير صحيح'), ('duplicate', 'مكرر'), ('suspicious', 'مشكوك فيه'), ('corrected', 'مصحح')], default='valid', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='verification_method',
            field=models.CharField(choices=[('fingerprint', 'بصمة الإصبع'), ('face', 'التعرف على الوجه'), ('card', 'البطاقة'), ('pin', 'رمز PIN'), ('manual', 'يدوي'), ('web', 'عبر الويب'), ('mobile', 'عبر الجوال')], default='fingerprint', max_length=20, verbose_name='طريقة التحقق'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='ساعات الاستراحة'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='early_departure_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='دقائق المغادرة المبكرة'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='هل هذا اليوم عطلة رسمية؟', verbose_name='عطلة'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='is_weekend',
            field=models.BooleanField(default=False, help_text='هل هذا اليوم نهاية أسبوع؟', verbose_name='نهاية أسبوع'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='notes',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='ملاحظات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='ساعات الوقت الإضافي'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='الساعات العادية'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('half_day', 'نصف يوم'), ('holiday', 'عطلة'), ('leave', 'إجازة'), ('weekend', 'نهاية أسبوع')], default='present', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=EncryptedCharField(blank=True, max_length=200, null=True, verbose_name='رقم الحساب البنكي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='iban',
            field=EncryptedCharField(blank=True, max_length=200, null=True, verbose_name='رقم الآيبان'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=EncryptedCharField(blank=True, max_length=200, null=True, unique=True, verbose_name='رقم الهوية الوطنية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number',
            field=EncryptedCharField(blank=True, max_length=200, null=True, verbose_name='رقم جواز السفر'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='leaveapproval',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='leavetransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='break_end_time',
            field=models.TimeField(blank=True, help_text='وقت نهاية استراحة الغداء', null=True, verbose_name='نهاية الاستراحة'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='break_start_time',
            field=models.TimeField(blank=True, help_text='وقت بداية استراحة الغداء', null=True, verbose_name='بداية الاستراحة'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now, help_text='وصف إضافي للوردية', verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshift',
            name='end_time',
            field=models.TimeField(help_text='وقت نهاية الوردية', verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='name',
            field=models.CharField(help_text='مثال: الوردية الصباحية', max_length=100, verbose_name='اسم الوردية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='overtime_threshold_minutes',
            field=models.PositiveIntegerField(default=30, help_text='الحد الأدنى للوقت الإضافي بالدقائق', verbose_name='حد الوقت الإضافي (دقيقة)'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='shift_type',
            field=models.CharField(choices=[('regular', 'عادية'), ('night', 'ليلية'), ('split', 'مقسمة'), ('flexible', 'مرنة'), ('rotating', 'متناوبة')], default='regular', max_length=20, verbose_name='نوع الوردية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.TimeField(help_text='وقت بداية الوردية', verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, help_text='إجمالي ساعات العمل في الوردية', max_digits=4, verbose_name='إجمالي الساعات'),
        ),
        migrations.AddIndex(
            model_name='attendancemachine',
            index=models.Index(fields=['is_active'], name='Hr_attendan_is_acti_61035a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemachine',
            index=models.Index(fields=['serial_number'], name='Hr_attendan_serial__2ffd03_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='Hr_attendan_employe_5d971d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'record_type'], name='Hr_attendan_date_505bab_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['timestamp'], name='Hr_attendan_timesta_930ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['is_processed'], name='Hr_attendan_is_proc_3e8311_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['is_holiday'], name='Hr_attendan_is_holi_3da115_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['is_weekend'], name='Hr_attendan_is_week_c5da98_idx'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['status'], name='Hr_workshif_status_f51df4_idx'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['start_time', 'end_time'], name='Hr_workshif_start_t_3dd204_idx'),
        ),
        migrations.AlterModelTable(
            name='attendancemachine',
            table=None,
        ),
        migrations.AlterModelTable(
            name='attendancerecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='attendancesummary',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workshift',
            table=None,
        ),
        migrations.AddField(
            model_name='machineuser',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_users', to='Hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='machineuser',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_users', to='Hr.attendancemachine', verbose_name='الجهاز'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='Hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Hr.workshift', verbose_name='الوردية'),
        ),
        migrations.DeleteModel(
            name='EmployeeShiftAssignment',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='early_minutes',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='is_early',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='is_manual_entry',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='late_minutes',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='record_datetime',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='record_time',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='source',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='work_shift',
        ),
        migrations.AddIndex(
            model_name='machineuser',
            index=models.Index(fields=['machine', 'user_id'], name='Hr_machineu_machine_e80812_idx'),
        ),
        migrations.AddIndex(
            model_name='machineuser',
            index=models.Index(fields=['employee'], name='Hr_machineu_employe_ca84dd_idx'),
        ),
        migrations.AddIndex(
            model_name='machineuser',
            index=models.Index(fields=['is_enrolled'], name='Hr_machineu_is_enro_9076f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='machineuser',
            unique_together={('machine', 'employee')},
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['employee', 'is_active'], name='Hr_shiftass_employe_800d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['shift', 'is_active'], name='Hr_shiftass_shift_i_9c2bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['start_date', 'end_date'], name='Hr_shiftass_start_d_3375d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('employee', 'shift', 'start_date')},
        ),
    ]
