# Generated by Django 4.2.7 on 2025-07-26 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hr', '0025_add_new_employee_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinsurance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeevehicle',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='employeeeducation',
            options={'ordering': ['employee', '-end_date', '-start_date'], 'verbose_name': 'تعليم الموظف', 'verbose_name_plural': 'تعليم الموظفين'},
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='degree_type',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='major',
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='الإنجازات'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الشهادة'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_education', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='degree_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='اسم الدرجة/المؤهل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة (بالشهور)'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='education_type',
            field=models.CharField(choices=[('school', 'تعليم مدرسي'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه'), ('certification', 'شهادة مهنية'), ('course', 'دورة تدريبية'), ('other', 'أخرى')], default=django.utils.timezone.now, max_length=20, verbose_name='نوع التعليم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مجال الدراسة'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='institution_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دولة المؤسسة'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='institution_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='موقع المؤسسة'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='institution_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='اسم المؤسسة التعليمية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='حالي'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الدرجة/المعدل'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='score_type',
            field=models.CharField(blank=True, help_text='مثل: GPA، النسبة المئوية، إلخ', max_length=50, null=True, verbose_name='نوع الدرجة'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البداية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_education', to=settings.AUTH_USER_MODEL, verbose_name='تم التحقق بواسطة'),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_certificates/', verbose_name='ملف الشهادة'),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='Hr.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الدرجة/التقدير'),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد'),
        ),
        migrations.AddIndex(
            model_name='employeeeducation',
            index=models.Index(fields=['employee', 'education_type'], name='hrms_employ_employe_847cca_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeeducation',
            index=models.Index(fields=['is_verified'], name='hrms_employ_is_veri_1ab34c_idx'),
        ),
        migrations.AlterModelTable(
            name='employeeeducation',
            table='hrms_employee_education',
        ),
        migrations.DeleteModel(
            name='EmployeeInsurance',
        ),
        migrations.DeleteModel(
            name='EmployeeVehicle',
        ),
    ]
