# Generated migration for enhanced employee models

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0027_add_leave_management_models'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEnhanced',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف الفريد')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يحتوي على حروف فقط', regex='^[a-zA-Zأ-ي\\s]+$')], verbose_name='الاسم الأول')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يحتوي على حروف فقط', regex='^[a-zA-Zأ-ي\\s]+$')], verbose_name='الاسم الأوسط')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يحتوي على حروف فقط', regex='^[a-zA-Zأ-ي\\s]+$')], verbose_name='الاسم الأخير')),
                ('first_name_en', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='الاسم الإنجليزي يجب أن يحتوي على حروف إنجليزية فقط', regex='^[a-zA-Z\\s]+$')], verbose_name='الاسم الأول بالإنجليزية')),
                ('middle_name_en', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='الاسم الإنجليزي يجب أن يحتوي على حروف إنجليزية فقط', regex='^[a-zA-Z\\s]+$')], verbose_name='الاسم الأوسط بالإنجليزية')),
                ('last_name_en', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='الاسم الإنجليزي يجب أن يحتوي على حروف إنجليزية فقط', regex='^[a-zA-Z\\s]+$')], verbose_name='الاسم الأخير بالإنجليزية')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى'), ('O', 'أخرى')], max_length=1, verbose_name='النوع')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان الميلاد')),
                ('marital_status', models.CharField(choices=[('S', 'أعزب'), ('M', 'متزوج'), ('D', 'مطلق'), ('W', 'أرمل')], default='S', max_length=1, verbose_name='الحالة الاجتماعية')),
                ('number_of_children', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='عدد الأطفال')),
                ('mother_name', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=200, null=True, verbose_name='اسم الأم')),
                ('private_email', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=254, null=True, verbose_name='البريد الإلكتروني الشخصي')),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني للعمل')),
                ('mobile_phone', models.CharField(help_text='يتم تشفير هذه البيانات', max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح', regex='^\\+?[1-9]\\d{1,14}$')], verbose_name='رقم الجوال')),
                ('home_phone', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح', regex='^\\+?[1-9]\\d{1,14}$')], verbose_name='هاتف المنزل')),
                ('address', models.TextField(blank=True, help_text='يتم تشفير هذه البيانات', null=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('state_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة/الولاية')),
                ('country', models.CharField(default='Saudi Arabia', max_length=100, verbose_name='الدولة')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='الجنسية')),
                ('religion', models.CharField(blank=True, max_length=50, null=True, verbose_name='الديانة')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='فصيلة الدم')),
                ('height', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='الطول (سم)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='الوزن (كغ)')),
                ('languages_spoken', models.TextField(blank=True, help_text='فصل بين اللغات بفاصلة', null=True, verbose_name='اللغات المتحدث بها')),
                ('military_service_status', models.CharField(blank=True, choices=[('completed', 'مكتملة'), ('exempted', 'معفى'), ('postponed', 'مؤجلة'), ('not_applicable', 'غير مطلوبة'), ('in_progress', 'جارية')], max_length=20, null=True, verbose_name='حالة الخدمة العسكرية')),
                ('military_service_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الخدمة العسكرية')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم التعريفي للموظف')),
                ('employee_number', models.CharField(help_text='للاتفاقية القديمة فقط', max_length=20, unique=True, verbose_name='رقم الموظف')),
                ('join_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء فترة التجربة')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العقد')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء العقد')),
                ('employment_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد مؤقت'), ('internship', 'تدريب'), ('consultant', 'استشاري'), ('freelancer', 'عمل حر'), ('temporary', 'مؤقت')], default='full_time', max_length=20, verbose_name='نوع التوظيف')),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الراتب الأساسي')),
                ('salary_currency', models.CharField(default='SAR', max_length=10, verbose_name='عملة الراتب')),
                ('work_schedule', models.CharField(choices=[('regular', 'نظام عادي'), ('shift', 'نظام ورديات'), ('flexible', 'مرن'), ('remote', 'عن بُعد'), ('hybrid', 'مختلط')], default='regular', max_length=20, verbose_name='نظام العمل')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البنك')),
                ('bank_account_number', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=50, null=True, verbose_name='رقم الحساب البنكي')),
                ('iban', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=34, null=True, verbose_name='رقم الأيبان')),
                ('national_id', models.CharField(help_text='يتم تشفير هذه البيانات', max_length=20, unique=True, verbose_name='رقم الهوية/الرقم القومي')),
                ('passport_number', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=20, null=True, unique=True, verbose_name='رقم الجواز')),
                ('passport_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الجواز')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار الجواز')),
                ('passport_issue_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان إصدار الجواز')),
                ('visa_number', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=50, null=True, verbose_name='رقم التأشيرة')),
                ('visa_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التأشيرة')),
                ('social_insurance_number', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=20, null=True, verbose_name='رقم التأمين الاجتماعي')),
                ('health_insurance_number', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=20, null=True, verbose_name='رقم التأمين الصحي')),
                ('insurance_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية التأمين')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=200, null=True, verbose_name='اسم جهة الاتصال للطوارئ')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='صلة القرابة')),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='يتم تشفير هذه البيانات', max_length=20, null=True, verbose_name='هاتف جهة الاتصال للطوارئ')),
                ('emergency_contact_address', models.TextField(blank=True, help_text='يتم تشفير هذه البيانات', null=True, verbose_name='عنوان جهة الاتصال للطوارئ')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('terminated', 'منتهي الخدمة'), ('on_leave', 'في إجازة'), ('probation', 'فترة تجربة')], default='active', max_length=10, verbose_name='الحالة الوظيفية')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إنهاء الخدمة')),
                ('termination_reason', models.TextField(blank=True, null=True, verbose_name='سبب إنهاء الخدمة')),
                ('last_evaluation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر تقييم')),
                ('next_evaluation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التقييم القادم')),
                ('performance_rating', models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جداً'), ('good', 'جيد'), ('satisfactory', 'مرضي'), ('needs_improvement', 'يحتاج تحسين')], max_length=20, null=True, verbose_name='تقييم الأداء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='الصورة الشخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_enhanced', to='Hr.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_enhanced', to='Hr.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_employees_enhanced', to='accounts.users_login_new', verbose_name='تم الإنشاء بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_enhanced', to='Hr.department', verbose_name='القسم')),
                ('direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates_enhanced', to='Hr.employeeenhanced', verbose_name='المدير المباشر')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_enhanced', to='Hr.jobposition', verbose_name='الوظيفة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_employees_enhanced', to='accounts.users_login_new', verbose_name='تم التحديث بواسطة')),
            ],
            options={
                'verbose_name': 'موظف محسن',
                'verbose_name_plural': 'الموظفين المحسنين',
                'db_table': 'hrms_employee_enhanced',
                'ordering': ['company', 'department', 'position', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeVehicleEnhanced',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('company', 'سيارة الشركة'), ('personal', 'سيارة شخصية'), ('allowance', 'بدل سيارة'), ('rental', 'سيارة مستأجرة'), ('lease', 'سيارة مؤجرة'), ('pool', 'سيارة مشتركة')], max_length=20, verbose_name='نوع السيارة')),
                ('make', models.CharField(max_length=100, verbose_name='الماركة')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2027)], verbose_name='سنة الصنع')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('vin_number', models.CharField(blank=True, help_text='رقم تعريف السيارة (VIN)', max_length=17, null=True, verbose_name='رقم الشاسيه')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'بنزين'), ('diesel', 'ديزل'), ('hybrid', 'هجين'), ('electric', 'كهربائي'), ('lpg', 'غاز'), ('cng', 'غاز طبيعي')], max_length=20, verbose_name='نوع الوقود')),
                ('engine_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='حجم المحرك')),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'يدوي'), ('automatic', 'أوتوماتيك'), ('cvt', 'CVT'), ('semi_automatic', 'نصف أوتوماتيك')], max_length=20, null=True, verbose_name='نوع ناقل الحركة')),
                ('doors_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)], verbose_name='عدد الأبواب')),
                ('seats_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)], verbose_name='عدد المقاعد')),
                ('assigned_date', models.DateField(verbose_name='تاريخ التخصيص')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع')),
                ('assignment_reason', models.TextField(blank=True, null=True, verbose_name='سبب التخصيص')),
                ('monthly_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='البدل الشهري')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الشراء')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='القيمة الحالية')),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='معدل الاستهلاك السنوي (%)')),
                ('insurance_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='شركة التأمين')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم بوليصة التأمين')),
                ('insurance_expiry', models.DateField(verbose_name='تاريخ انتهاء التأمين')),
                ('insurance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ التأمين')),
                ('registration_expiry', models.DateField(verbose_name='تاريخ انتهاء الاستمارة')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الرخصة')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر صيانة')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصيانة القادمة')),
                ('maintenance_interval_km', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(50000)], verbose_name='فترة الصيانة (كم)')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2000000)], verbose_name='عدد الكيلومترات')),
                ('last_mileage_update', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر تحديث للكيلومترات')),
                ('fuel_consumption_per_100km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='استهلاك الوقود لكل 100 كم')),
                ('condition', models.CharField(blank=True, choices=[('excellent', 'ممتازة'), ('very_good', 'جيدة جداً'), ('good', 'جيدة'), ('fair', 'مقبولة'), ('poor', 'سيئة')], max_length=20, null=True, verbose_name='حالة السيارة')),
                ('status', models.CharField(choices=[('assigned', 'مخصصة'), ('available', 'متاحة'), ('maintenance', 'في الصيانة'), ('retired', 'خارج الخدمة'), ('sold', 'مباعة'), ('accident', 'في حادث'), ('repair', 'في الإصلاح')], default='assigned', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('has_gps', models.BooleanField(default=False, verbose_name='يحتوي على GPS')),
                ('gps_device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف جهاز GPS')),
                ('features', models.TextField(blank=True, help_text='مكيف، راديو، نظام ملاحة، إلخ', null=True, verbose_name='المميزات الإضافية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='vehicles/registration/', verbose_name='وثيقة التسجيل')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='vehicles/insurance/', verbose_name='وثيقة التأمين')),
                ('vehicle_photos', models.FileField(blank=True, null=True, upload_to='vehicles/photos/', verbose_name='صور السيارة')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vehicle_records', to='accounts.users_login_new', verbose_name='تم الاعتماد بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_vehicle_records', to='accounts.users_login_new', verbose_name='تم الإنشاء بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_records_enhanced', to='Hr.employeeenhanced', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سيارة موظف محسنة',
                'verbose_name_plural': 'سيارات الموظفين المحسنة',
                'ordering': ['employee', '-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeInsuranceEnhanced',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insurance_type', models.CharField(choices=[('social', 'تأمين اجتماعي'), ('medical', 'تأمين صحي'), ('life', 'تأمين على الحياة'), ('disability', 'تأمين ضد العجز'), ('unemployment', 'تأمين ضد البطالة'), ('professional', 'تأمين مهني'), ('travel', 'تأمين سفر'), ('dental', 'تأمين أسنان'), ('vision', 'تأمين نظر'), ('maternity', 'تأمين أمومة')], max_length=20, verbose_name='نوع التأمين')),
                ('policy_number', models.CharField(max_length=100, unique=True, verbose_name='رقم البوليصة')),
                ('provider', models.CharField(max_length=200, verbose_name='مقدم التأمين')),
                ('provider_contact', models.CharField(blank=True, max_length=200, null=True, verbose_name='جهة الاتصال')),
                ('provider_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف مقدم التأمين')),
                ('provider_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد مقدم التأمين')),
                ('coverage_type', models.CharField(choices=[('individual', 'فردي'), ('family', 'عائلي'), ('spouse', 'الزوج/الزوجة'), ('children', 'الأطفال'), ('parents', 'الوالدين')], default='individual', max_length=20, verbose_name='نوع التغطية')),
                ('coverage_description', models.TextField(blank=True, null=True, verbose_name='وصف التغطية')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التجديد')),
                ('last_renewal_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر تجديد')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='قسط التأمين')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='مبلغ التغطية')),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مساهمة الموظف')),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مساهمة صاحب العمل')),
                ('deductible', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المقتطع')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], default='monthly', max_length=20, verbose_name='تكرار الدفع')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'موقوف'), ('expired', 'منتهي'), ('cancelled', 'ملغى'), ('pending', 'في الانتظار')], default='active', max_length=20, verbose_name='الحالة')),
                ('beneficiaries', models.TextField(blank=True, null=True, verbose_name='المستفيدون')),
                ('spouse_covered', models.BooleanField(default=False, verbose_name='يشمل الزوج/الزوجة')),
                ('children_covered', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='عدد الأطفال المشمولين')),
                ('parents_covered', models.BooleanField(default=False, verbose_name='يشمل الوالدين')),
                ('total_claims_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='إجمالي المطالبات')),
                ('claims_count', models.PositiveIntegerField(default=0, verbose_name='عدد المطالبات')),
                ('last_claim_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر مطالبة')),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='insurance/policies/', verbose_name='وثيقة التأمين')),
                ('terms_document', models.FileField(blank=True, null=True, upload_to='insurance/terms/', verbose_name='شروط وأحكام التأمين')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('special_conditions', models.TextField(blank=True, null=True, verbose_name='شروط خاصة')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_insurance_records', to='accounts.users_login_new', verbose_name='تم الاعتماد بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_insurance_records', to='accounts.users_login_new', verbose_name='تم الإنشاء بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records_enhanced', to='Hr.employeeenhanced', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تأمين موظف محسن',
                'verbose_name_plural': 'تأمينات الموظفين المحسنة',
                'ordering': ['employee', 'insurance_type', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducationEnhanced',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree_type', models.CharField(choices=[('elementary', 'ابتدائية'), ('intermediate', 'متوسطة'), ('high_school', 'ثانوية عامة'), ('vocational', 'مهني'), ('diploma', 'دبلوم'), ('associate', 'دبلوم عالي'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه'), ('certificate', 'شهادة مهنية'), ('training', 'دورة تدريبية'), ('professional', 'شهادة احترافية')], max_length=20, verbose_name='نوع الشهادة')),
                ('major', models.CharField(max_length=200, verbose_name='التخصص الرئيسي')),
                ('minor', models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص الفرعي')),
                ('institution', models.CharField(max_length=200, verbose_name='الجامعة/المؤسسة')),
                ('institution_english', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المؤسسة بالإنجليزية')),
                ('graduation_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2035)], verbose_name='سنة التخرج')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2035)], verbose_name='سنة البداية')),
                ('study_duration_years', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='مدة الدراسة بالسنوات')),
                ('study_mode', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('distance', 'تعليم عن بُعد'), ('evening', 'مسائي'), ('weekend', 'نهاية الأسبوع')], default='full_time', max_length=20, verbose_name='نظام الدراسة')),
                ('grade_system', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('gpa_4', 'GPA من 4'), ('gpa_5', 'GPA من 5'), ('letter', 'حروف (A, B, C)'), ('pass_fail', 'نجح/راسب'), ('honors', 'مرتبة الشرف')], default='percentage', max_length=20, verbose_name='نظام الدرجات')),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='المعدل/الدرجة')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('verification_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('verification_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات التحقق')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='education/certificates/', verbose_name='ملف الشهادة')),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to='education/transcripts/', verbose_name='كشف الدرجات')),
                ('honors', models.CharField(blank=True, max_length=200, null=True, verbose_name='مرتبة الشرف')),
                ('thesis_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان الرسالة/المشروع')),
                ('thesis_title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان الرسالة بالإنجليزية')),
                ('supervisor_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المشرف')),
                ('class_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='الترتيب على الدفعة')),
                ('class_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد طلاب الدفعة')),
                ('awards', models.TextField(blank=True, null=True, verbose_name='الجوائز والتكريمات')),
                ('is_relevant_to_job', models.BooleanField(default=True, verbose_name='مرتبط بالوظيفة')),
                ('relevance_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الصلة بالوظيفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_education_records', to='accounts.users_login_new', verbose_name='تم الإنشاء بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records_enhanced', to='Hr.employeeenhanced', verbose_name='الموظف')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_education_records', to='accounts.users_login_new', verbose_name='تم التحقق بواسطة')),
            ],
            options={
                'verbose_name': 'مؤهل دراسي محسن',
                'verbose_name_plural': 'المؤهلات الدراسية المحسنة',
                'ordering': ['-graduation_year', 'degree_type'],
            },
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='employeeenhanced',
            index=models.Index(fields=['company', 'status'], name='Hr_employee_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeenhanced',
            index=models.Index(fields=['employee_id'], name='Hr_employee_id_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeenhanced',
            index=models.Index(fields=['national_id'], name='Hr_employee_national_id_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeenhanced',
            index=models.Index(fields=['department'], name='Hr_employee_department_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeenhanced',
            index=models.Index(fields=['position'], name='Hr_employee_position_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeenhanced',
            index=models.Index(fields=['join_date'], name='Hr_employee_join_date_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeenhanced',
            index=models.Index(fields=['status'], name='Hr_employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeenhanced',
            index=models.Index(fields=['employment_type'], name='Hr_employee_employment_type_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeenhanced',
            index=models.Index(fields=['direct_manager'], name='Hr_employee_direct_manager_idx'),
        ),
        # Add constraints
        migrations.AddConstraint(
            model_name='employeeenhanced',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lt', models.F('join_date'))), name='birth_before_join'),
        ),
        migrations.AddConstraint(
            model_name='employeeenhanced',
            constraint=models.CheckConstraint(check=models.Q(('base_salary__gte', 0)), name='positive_salary'),
        ),
        migrations.AddConstraint(
            model_name='employeevehicleenhanced',
            constraint=models.CheckConstraint(check=models.Q(('return_date__gte', models.F('assigned_date'))), name='return_after_assignment'),
        ),
        migrations.AddConstraint(
            model_name='employeevehicleenhanced',
            constraint=models.CheckConstraint(check=models.Q(('current_value__lte', models.F('purchase_price'))), name='current_value_realistic'),
        ),
        migrations.AddConstraint(
            model_name='employeeinsuranceenhanced',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='end_after_start_insurance'),
        ),
        migrations.AddConstraint(
            model_name='employeeinsuranceenhanced',
            constraint=models.CheckConstraint(check=models.Q(('employee_contribution__lte', models.F('premium_amount'))), name='employee_contribution_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeeinsuranceenhanced',
            constraint=models.CheckConstraint(check=models.Q(('employer_contribution__lte', models.F('premium_amount'))), name='employer_contribution_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeeeducationenhanced',
            constraint=models.CheckConstraint(check=models.Q(('start_year__lte', models.F('graduation_year'))), name='start_before_graduation'),
        ),
        migrations.AddConstraint(
            model_name='employeeeducationenhanced',
            constraint=models.CheckConstraint(check=models.Q(('class_rank__lte', models.F('class_size'))), name='rank_within_class_size'),
        ),
    ]