# Generated by Django 4.2.7 on 2025-08-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0031_create_employee_extended_models'),
        ('Hr', '0034_fix_shift_assignment_related_names'),
    ]

    operations = [
    ]
