# Generated by Django 4.2.7 on 2025-08-10 14:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hr', '0037_branch_name_english_company_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEmergencyContactEnhanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('relationship', models.CharField(choices=[('spouse', 'زوج/زوجة'), ('father', 'والد'), ('mother', 'والدة'), ('son', 'ابن'), ('daughter', 'ابنة'), ('brother', 'أخ'), ('sister', 'أخت'), ('grandfather', 'جد'), ('grandmother', 'جدة'), ('uncle', 'عم/خال'), ('aunt', 'عمة/خالة'), ('cousin', 'ابن عم/خال'), ('friend', 'صديق'), ('colleague', 'زميل عمل'), ('neighbor', 'جار'), ('guardian', 'ولي أمر'), ('other', 'أخرى')], max_length=20, verbose_name='صلة القرابة')),
                ('relationship_other', models.CharField(blank=True, help_text="حدد صلة القرابة إذا اخترت 'أخرى'", max_length=100, null=True, verbose_name='صلة القرابة (أخرى)')),
                ('primary_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح', regex='^\\+?[\\d\\s\\-\\(\\)]+$')], verbose_name='رقم الهاتف الأساسي')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح', regex='^\\+?[\\d\\s\\-\\(\\)]+$')], verbose_name='رقم الهاتف الثانوي')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='الدولة')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة')),
                ('workplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='مكان العمل')),
                ('priority', models.PositiveIntegerField(choices=[(1, 'الأولوية الأولى'), (2, 'الأولوية الثانية'), (3, 'الأولوية الثالثة'), (4, 'الأولوية الرابعة'), (5, 'الأولوية الخامسة')], default=1, help_text='أولوية الاتصال في حالات الطوارئ', verbose_name='الأولوية')),
                ('is_primary', models.BooleanField(default=False, help_text='هل هذه جهة الاتصال الأساسية؟', verbose_name='جهة الاتصال الأساسية')),
                ('best_time_to_call', models.CharField(blank=True, max_length=100, null=True, verbose_name='أفضل وقت للاتصال')),
                ('availability_notes', models.TextField(blank=True, help_text='معلومات إضافية حول أوقات التوفر', null=True, verbose_name='ملاحظات التوفر')),
                ('can_make_medical_decisions', models.BooleanField(default=False, help_text='هل يمكن لهذا الشخص اتخاذ قرارات طبية نيابة عن الموظف؟', verbose_name='يمكنه اتخاذ قرارات طبية')),
                ('can_receive_salary', models.BooleanField(default=False, help_text='هل يمكن لهذا الشخص استلام راتب الموظف في حالات الطوارئ؟', verbose_name='يمكنه استلام الراتب')),
                ('has_power_of_attorney', models.BooleanField(default=False, help_text='هل لدى هذا الشخص توكيل قانوني من الموظف؟', verbose_name='لديه توكيل قانوني')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'الإنجليزية'), ('fr', 'الفرنسية'), ('other', 'أخرى')], default='ar', max_length=50, verbose_name='اللغة المفضلة')),
                ('is_verified', models.BooleanField(default=False, help_text='هل تم التحقق من صحة معلومات الاتصال؟', verbose_name='تم التحقق')),
                ('verified_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'جهة اتصال طوارئ',
                'verbose_name_plural': 'جهات اتصال الطوارئ',
                'db_table': 'hrms_employee_emergency_contact',
                'ordering': ['employee', 'priority'],
            },
        ),
        migrations.RemoveIndex(
            model_name='employeefileaccesslog',
            name='hrms_employee_file_access_log_file_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeefileaccesslog',
            name='hrms_employee_file_access_log_user_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeefileaccesslog',
            name='hrms_employee_file_access_log_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeefileenhanced',
            name='hrms_employee_file_enhanced_employee_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeefileenhanced',
            name='hrms_employee_file_enhanced_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeefileenhanced',
            name='hrms_employee_file_enhanced_access_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeefileenhanced',
            name='hrms_employee_file_enhanced_expiry_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeefileenhanced',
            name='hrms_employee_file_enhanced_file_hash_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeefileenhanced',
            name='hrms_employee_file_enhanced_created_at_idx',
        ),
        migrations.AlterField(
            model_name='employeeinsuranceenhanced',
            name='coverage_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ التغطية'),
        ),
        migrations.AlterField(
            model_name='employeeinsuranceenhanced',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قسط التأمين'),
        ),
        migrations.AddField(
            model_name='employeeemergencycontactenhanced',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emergency_contacts', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='employeeemergencycontactenhanced',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='Hr.employeeenhanced', verbose_name='الموظف'),
        ),
        migrations.AddIndex(
            model_name='employeeemergencycontactenhanced',
            index=models.Index(fields=['employee', 'priority'], name='hrms_employ_employe_0e6341_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeemergencycontactenhanced',
            index=models.Index(fields=['is_primary'], name='hrms_employ_is_prim_a3d5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeemergencycontactenhanced',
            index=models.Index(fields=['is_active'], name='hrms_employ_is_acti_eaf2a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeemergencycontactenhanced',
            unique_together={('employee', 'priority')},
        ),
    ]
