# Generated by Django 5.0.14 on 2025-04-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_login_new',
            name='UserPassword',
        ),
    ]
