# Generated by Django 5.0.14 on 2025-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_users_login_new_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_login_new',
            name='Role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20),
        ),
    ]
