# Generated by Django 4.2.7 on 2025-08-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProvider',
            fields=[
                ('provider_id', models.AutoField(db_column='ProviderID', primary_key=True, serialize=False)),
                ('provider_name', models.CharField(db_column='ProviderName', max_length=150)),
                ('contact_person', models.CharField(blank=True, db_column='ContactPerson', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'مزود تدريب',
                'verbose_name_plural': 'مزودو التدريب',
                'db_table': 'TrainingProviders',
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('course_id', models.AutoField(db_column='CourseID', primary_key=True, serialize=False)),
                ('course_name', models.CharField(db_column='CourseName', max_length=200)),
                ('duration_hours', models.IntegerField(blank=True, db_column='DurationHours', null=True)),
                ('cost', models.DecimalField(blank=True, db_column='Cost', decimal_places=2, max_digits=18, null=True)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('provider', models.ForeignKey(blank=True, db_column='ProviderID', null=True, on_delete=django.db.models.deletion.PROTECT, to='training.trainingprovider')),
            ],
            options={
                'verbose_name': 'دورة تدريبية',
                'verbose_name_plural': 'الدورات التدريبية',
                'db_table': 'TrainingCourses',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('emp_training_id', models.AutoField(db_column='EmpTrainingID', primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(blank=True, db_column='EnrollmentDate', null=True)),
                ('status', models.CharField(db_column='Status', default='Registered', max_length=30)),
                ('grade', models.CharField(blank=True, db_column='Grade', max_length=10, null=True)),
                ('certificate_path', models.CharField(blank=True, db_column='CertificatePath', max_length=500, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500, null=True)),
                ('course', models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.CASCADE, to='training.trainingcourse')),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'تدريب موظف',
                'verbose_name_plural': 'تدريبات الموظفين',
                'db_table': 'EmployeeTraining',
            },
        ),
    ]
