# Generated by Django 5.0.14 on 2025-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCategories',
            fields=[
                ('cat_id', models.IntegerField(db_column='CAT_ID', primary_key=True, serialize=False)),
                ('cat_name', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='CAT_Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tbl_Categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCustomers',
            fields=[
                ('customer_id', models.IntegerField(db_column='Customer_ID', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Customer_Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tbl_Customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblInvoiceitems',
            fields=[
                ('invoice_code_programing', models.AutoField(db_column='Invoice_Code_Programing', primary_key=True, serialize=False)),
                ('invoice_id', models.IntegerField(blank=True, db_column='Invoice_ID', null=True)),
                ('invoice_number', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Invoice_Number', max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Product_Name', max_length=100, null=True)),
                ('quantity_elwarad', models.DecimalField(blank=True, db_column='Quantity_ElWarad', decimal_places=2, max_digits=18, null=True)),
                ('quantity_elmonsarf', models.DecimalField(blank=True, db_column='Quantity_ElMonsarf', decimal_places=2, max_digits=18, null=True)),
                ('quantity_mortagaaelmawarden', models.DecimalField(blank=True, db_column='Quantity_MortagaaElMawarden', decimal_places=2, max_digits=18, null=True)),
                ('quantity_mortagaaomalaa', models.DecimalField(blank=True, db_column='Quantity_MortagaaOmalaa', decimal_places=2, max_digits=18, null=True)),
                ('unit_id', models.IntegerField(blank=True, db_column='Unit_ID', null=True)),
                ('unit_price', models.DecimalField(blank=True, db_column='Unit_Price', decimal_places=2, max_digits=18, null=True)),
                ('invoice_date', models.DateField(blank=True, db_column='Invoice_Date', null=True)),
                ('invoice_type', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Invoice_Type', max_length=100, null=True)),
                ('recipient', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Recipient', max_length=100, null=True)),
                ('received_machine', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Received_Machine', max_length=100, null=True)),
                ('machine_unit', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Machine_Unit', max_length=100, null=True)),
                ('returninvoicenumber', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='ReturnInvoiceNumber', max_length=100, null=True)),
                ('total_invoice_value', models.DecimalField(blank=True, db_column='Total_Invoice_Value', decimal_places=2, max_digits=18, null=True)),
                ('balance_time_entry', models.DecimalField(blank=True, db_column='Balance_Time_Entry', decimal_places=2, max_digits=18, null=True)),
                ('data_entry_date', models.DateField(blank=True, db_column='Data_Entry_Date', null=True)),
                ('data_entry_by', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Data_Entry_By', max_length=100, null=True)),
                ('notes', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Notes', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tbl_InvoiceItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblInvoices',
            fields=[
                ('invoice_id', models.IntegerField(db_column='Invoice_ID')),
                ('invoice_number', models.CharField(db_collation='Arabic_CI_AS', db_column='Invoice_Number', max_length=255, primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(blank=True, db_column='Invoice_Date', null=True)),
                ('invoice_type', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Invoice_Type', max_length=100, null=True)),
                ('numberofitems', models.IntegerField(blank=True, db_column='NumberOfItems', null=True)),
                ('recipient', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Recipient', max_length=100, null=True)),
                ('supplier_id', models.IntegerField(blank=True, db_column='Supplier_ID', null=True)),
                ('customer_id', models.IntegerField(blank=True, db_column='Customer_ID', null=True)),
                ('customer_invoice_number', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Customer_Invoice_Number', max_length=255, null=True)),
                ('supplier_invoice_number', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Supplier_Invoice_Number', max_length=255, null=True)),
                ('total_invoice_value', models.DecimalField(blank=True, db_column='Total_Invoice_Value', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Tbl_Invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProducts',
            fields=[
                ('product_id', models.CharField(db_collation='Arabic_CI_AS', db_column='Product_ID', max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Product_Name', max_length=100, null=True)),
                ('initial_balance', models.DecimalField(blank=True, db_column='Initial_Balance', decimal_places=2, max_digits=18, null=True)),
                ('elwarad', models.DecimalField(blank=True, db_column='ElWarad', decimal_places=2, max_digits=18, null=True)),
                ('mortagaaomalaa', models.DecimalField(blank=True, db_column='MortagaaOmalaa', decimal_places=2, max_digits=18, null=True)),
                ('elmonsarf', models.DecimalField(blank=True, db_column='ElMonsarf', decimal_places=2, max_digits=18, null=True)),
                ('mortagaaelmawarden', models.DecimalField(blank=True, db_column='MortagaaElMawarden', decimal_places=2, max_digits=18, null=True)),
                ('qte_in_stock', models.DecimalField(blank=True, db_column='QTE_IN_STOCK', decimal_places=2, max_digits=18, null=True)),
                ('cat_name', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='CAT_Name', max_length=100, null=True)),
                ('unit_name', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Unit_Name', max_length=100, null=True)),
                ('minimum_threshold', models.DecimalField(blank=True, db_column='Minimum_Threshold', decimal_places=2, max_digits=18, null=True)),
                ('maximum_threshold', models.DecimalField(blank=True, db_column='Maximum_Threshold', decimal_places=2, max_digits=18, null=True)),
                ('image_product', models.BinaryField(blank=True, db_column='Image_Product', max_length='max', null=True)),
                ('unit_price', models.DecimalField(blank=True, db_column='Unit_Price', decimal_places=2, max_digits=18, null=True)),
                ('location', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Location', max_length=50, null=True)),
                ('expiry_warning', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Expiry_Warning', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Tbl_Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSuppliers',
            fields=[
                ('supplier_id', models.IntegerField(db_column='Supplier_ID', primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Supplier_Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tbl_Suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUnitsSpareparts',
            fields=[
                ('unit_id', models.IntegerField(db_column='Unit_ID', primary_key=True, serialize=False)),
                ('unit_name', models.CharField(blank=True, db_collation='Arabic_CI_AS', db_column='Unit_Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tbl_Units_SpareParts',
                'managed': False,
            },
        ),
    ]
