# Generated by Django 5.0.14 on 2025-04-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2, verbose_name='لغة النظام')),
                ('font_family', models.CharField(choices=[('cairo', 'Cairo'), ('tajawal', 'Tajawal'), ('almarai', 'Almarai'), ('ibm-plex-sans-arabic', 'IBM Plex Sans Arabic'), ('noto-sans-arabic', 'Noto Sans Arabic')], default='cairo', max_length=50, verbose_name='الخط المستخدم')),
                ('text_direction', models.CharField(choices=[('rtl', 'من اليمين إلى اليسار'), ('ltr', 'من اليسار إلى اليمين')], default='rtl', max_length=3, verbose_name='اتجاه النص')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
