# Generated by Django 4.2.22 on 2025-11-17 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'صنف', 'verbose_name_plural': 'الأصناف'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='approved_date',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=10, verbose_name='الكمية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localsystemsettings',
            name='compact_tables',
            field=models.BooleanField(default=False, verbose_name='جداول مضغوطة'),
        ),
        migrations.AlterField(
            model_name='localsystemsettings',
            name='default_min_stock_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='نسبة الحد الأدنى الافتراضية'),
        ),
        migrations.AlterField(
            model_name='localsystemsettings',
            name='invoice_in_prefix',
            field=models.CharField(default='IN', max_length=10, verbose_name='بادئة فاتورة الوارد'),
        ),
        migrations.AlterField(
            model_name='localsystemsettings',
            name='invoice_out_prefix',
            field=models.CharField(default='OUT', max_length=10, verbose_name='بادئة فاتورة الصادر'),
        ),
        migrations.AlterField(
            model_name='localsystemsettings',
            name='items_per_page',
            field=models.IntegerField(default=10, verbose_name='عدد العناصر في الصفحة'),
        ),
        migrations.AlterField(
            model_name='localsystemsettings',
            name='primary_color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='اللون الأساسي'),
        ),
        migrations.AlterField(
            model_name='localsystemsettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='اللون الثانوي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الصنف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية الحالية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.unit', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='الرمز'),
            preserve_default=False,
        ),
    ]
