# Generated by Django 5.0.14 on 2025-04-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_unit_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='تمت الموافقة بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='inventory.product', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'طلب شراء',
                'verbose_name_plural': 'طلبات الشراء',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_number', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='رقم الإذن')),
                ('voucher_type', models.CharField(choices=[('إذن اضافة', 'إذن اضافة'), ('إذن صرف', 'إذن صرف'), ('اذن مرتجع عميل', 'اذن مرتجع عميل'), ('إذن مرتجع مورد', 'إذن مرتجع مورد')], max_length=20, verbose_name='نوع الإذن')),
                ('date', models.DateField(verbose_name='تاريخ الإذن')),
                ('supplier_voucher_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم إذن المورد')),
                ('recipient', models.CharField(blank=True, max_length=100, null=True, verbose_name='المستلم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='inventory.customer', verbose_name='العميل')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='inventory.department', verbose_name='القسم')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='inventory.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'إذن',
                'verbose_name_plural': 'الأذونات',
            },
        ),
        migrations.CreateModel(
            name='VoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الكمية المضافة')),
                ('quantity_disbursed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الكمية المنصرفة')),
                ('machine', models.CharField(blank=True, max_length=100, null=True, verbose_name='الماكينة')),
                ('machine_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='وحدة الماكينة')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الوحدة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_items', to='inventory.product', verbose_name='الصنف')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.voucher', verbose_name='الإذن')),
            ],
            options={
                'verbose_name': 'عنصر الإذن',
                'verbose_name_plural': 'عناصر الإذن',
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
