# Generated by Django 5.0.14 on 2025-04-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_department_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد الافتتاحي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد الحالي'),
        ),
    ]
