# Generated by Django 5.0.14 on 2025-05-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_department_fields'),
        ('inventory', '0006_product_initial_quantity_alter_product_quantity'),
    ]

    operations = [
    ]
