# Generated by Django 5.0.14 on 2025-05-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_merge_20250502_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='department',
            name='notes',
        ),
    ]
