# Generated by Django 5.0.14 on 2025-05-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_department_code_remove_department_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcategories',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblcustomers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblinvoiceitems',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblinvoices',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblproducts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblsuppliers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblunitsspareparts',
            options={'managed': True},
        ),
    ]
