# Generated by Django 5.0.14 on 2025-05-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_tblcategories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoiceitems',
            name='product',
            field=models.ForeignKey(blank=True, db_column='Product_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tblproducts'),
        ),
        migrations.AddField(
            model_name='tblproducts',
            name='cat',
            field=models.ForeignKey(blank=True, db_column='CAT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tblcategories'),
        ),
        migrations.AddField(
            model_name='tblproducts',
            name='unit',
            field=models.ForeignKey(blank=True, db_column='Unit_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tblunitsspareparts'),
        ),
        migrations.AlterField(
            model_name='tblproducts',
            name='image_product',
            field=models.BinaryField(blank=True, db_column='Image_Product', null=True),
        ),
    ]
