# Generated by Django 5.0.14 on 2025-05-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'permissions': [('view_meetingtask', 'Can view meeting tasks'), ('add_meetingtask', 'Can add meeting tasks'), ('change_meetingtask', 'Can change meeting tasks'), ('delete_meetingtask', 'Can delete meeting tasks'), ('view_meetingreport', 'Can view meeting reports'), ('export_meetingreport', 'Can export meeting reports')], 'verbose_name': 'اجتماع', 'verbose_name_plural': 'الاجتماعات'},
        ),
    ]
