# Generated by Django 4.2.26 on 2025-12-16 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Rule Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "late_grace_period",
                    models.IntegerField(
                        default=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Late Grace Period (minutes)",
                    ),
                ),
                (
                    "early_leave_grace_period",
                    models.IntegerField(
                        default=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Early Leave Grace Period (minutes)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Attendance Rule",
                "verbose_name_plural": "Attendance Rules",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRules",
            fields=[
                (
                    "rule_id",
                    models.AutoField(
                        db_column="RuleID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        blank=True,
                        db_column="RuleName",
                        max_length=100,
                        null=True,
                        verbose_name="اسم القاعدة",
                    ),
                ),
                (
                    "shift_start",
                    models.TimeField(
                        blank=True,
                        db_column="ShiftStart",
                        null=True,
                        verbose_name="بداية الوردية",
                    ),
                ),
                (
                    "shift_end",
                    models.TimeField(
                        blank=True,
                        db_column="ShiftEnd",
                        null=True,
                        verbose_name="نهاية الوردية",
                    ),
                ),
                (
                    "late_threshold",
                    models.IntegerField(
                        blank=True,
                        db_column="LateThreshold",
                        null=True,
                        verbose_name="حد التأخير (دقائق)",
                    ),
                ),
                (
                    "early_threshold",
                    models.IntegerField(
                        blank=True,
                        db_column="EarlyThreshold",
                        null=True,
                        verbose_name="حد المغادرة المبكرة (دقائق)",
                    ),
                ),
                (
                    "overtime_start_after",
                    models.TimeField(
                        blank=True,
                        db_column="OvertimeStartAfter",
                        null=True,
                        verbose_name="بداية الوقت الإضافي",
                    ),
                ),
                (
                    "week_end_days",
                    models.CharField(
                        blank=True,
                        db_column="WeekEndDays",
                        max_length=20,
                        null=True,
                        verbose_name="أيام نهاية الأسبوع",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_column="IsDefault", default=False, verbose_name="افتراضية"
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعدة حضور",
                "verbose_name_plural": "قواعد الحضور",
                "db_table": "AttendanceRules",
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Leave Type")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=True, verbose_name="Is Paid Leave"),
                ),
                (
                    "max_days_per_year",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Maximum Days Per Year",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=True, verbose_name="Requires Approval"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
            },
        ),
        migrations.CreateModel(
            name="ZKDevice",
            fields=[
                (
                    "device_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="معرف الجهاز"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="اسم الجهاز"),
                ),
                (
                    "device_serial",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="الرقم التسلسلي"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "port",
                    models.PositiveIntegerField(default=4370, verbose_name="المنفذ"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="الموقع"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("inactive", "غير نشط"),
                            ("maintenance", "صيانة"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        default="Asia/Riyadh",
                        max_length=50,
                        verbose_name="المنطقة الزمنية",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر مزامنة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "جهاز ZK",
                "verbose_name_plural": "أجهزة ZK",
            },
        ),
        migrations.CreateModel(
            name="EmployeeAttendanceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_hours_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                        verbose_name="Work Hours Per Day",
                    ),
                ),
                (
                    "salary_status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=20,
                        verbose_name="Salary Status",
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=20,
                        verbose_name="Attendance Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "attendance_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_profiles",
                        to="attendance.attendancerule",
                        verbose_name="Attendance Rule",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_profile",
                        to="employees.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Attendance Profile",
                "verbose_name_plural": "Employee Attendance Profiles",
            },
        ),
        migrations.CreateModel(
            name="AttendanceProcessingLog",
            fields=[
                (
                    "log_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="معرف السجل"
                    ),
                ),
                ("process_date", models.DateField(verbose_name="تاريخ المعالجة")),
                (
                    "records_fetched",
                    models.PositiveIntegerField(
                        default=0, verbose_name="السجلات المجلبة"
                    ),
                ),
                (
                    "records_processed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="السجلات المعالجة"
                    ),
                ),
                (
                    "records_failed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="السجلات الفاشلة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "نجح"),
                            ("failed", "فشل"),
                            ("partial", "جزئي"),
                        ],
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "processing_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="وقت المعالجة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.zkdevice",
                        verbose_name="الجهاز",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل معالجة الحضور",
                "verbose_name_plural": "سجلات معالجة الحضور",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ZKAttendanceRaw",
            fields=[
                (
                    "raw_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="معرف السجل"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=20, verbose_name="معرف المستخدم في الجهاز"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="الوقت والتاريخ")),
                (
                    "punch_type",
                    models.CharField(
                        choices=[
                            ("0", "Check In"),
                            ("1", "Check Out"),
                            ("2", "Break Out"),
                            ("3", "Break In"),
                            ("4", "Overtime In"),
                            ("5", "Overtime Out"),
                        ],
                        default="0",
                        max_length=2,
                        verbose_name="نوع البصمة",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="نوع التحقق"
                    ),
                ),
                (
                    "work_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="كود العمل"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="تم المعالجة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.zkdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "بيانات ZK خام",
                "verbose_name_plural": "البيانات الخام من ZK",
                "ordering": ["-timestamp"],
                "unique_together": {("device", "user_id", "timestamp", "punch_type")},
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "break_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Break Start Time"
                    ),
                ),
                (
                    "break_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Break End Time"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="attendance.attendancerule",
                        verbose_name="Attendance Rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Schedule",
                "verbose_name_plural": "Work Schedules",
                "unique_together": {("rule", "day_of_week")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Holiday Day",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="attendance.attendancerule",
                        verbose_name="Attendance Rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Holiday",
                "verbose_name_plural": "Weekly Holidays",
                "unique_together": {("rule", "day")},
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
                (
                    "allocated_days",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Allocated Days",
                    ),
                ),
                (
                    "used_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Used Days",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_leave_balances",
                        to="employees.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_balances",
                        to="attendance.leavetype",
                        verbose_name="Leave Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance",
                "verbose_name_plural": "Leave Balances",
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeDeviceMapping",
            fields=[
                (
                    "mapping_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="معرف الربط"
                    ),
                ),
                (
                    "device_user_id",
                    models.CharField(
                        max_length=20, verbose_name="معرف المستخدم في الجهاز"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "enrollment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر استخدام"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.zkdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "ربط موظف بجهاز",
                "verbose_name_plural": "ربط الموظفين بالأجهزة",
                "unique_together": {("device", "device_user_id")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeAttendance",
            fields=[
                (
                    "att_id",
                    models.BigAutoField(
                        db_column="AttID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "att_date",
                    models.DateField(
                        blank=True,
                        db_column="AttDate",
                        null=True,
                        verbose_name="التاريخ",
                    ),
                ),
                (
                    "check_in",
                    models.DateTimeField(
                        blank=True,
                        db_column="CheckIn",
                        null=True,
                        verbose_name="وقت الدخول",
                    ),
                ),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True,
                        db_column="CheckOut",
                        null=True,
                        verbose_name="وقت الخروج",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        db_column="Status",
                        max_length=20,
                        null=True,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="EmpID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        db_column="RuleID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attendance.attendancerules",
                        verbose_name="قاعدة الحضور",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حضور",
                "verbose_name_plural": "سجلات الحضور",
                "db_table": "EmployeeAttendance",
                "unique_together": {("emp", "att_date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "summary_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="معرف الملخص"
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="السنة")),
                ("month", models.PositiveIntegerField(verbose_name="الشهر")),
                (
                    "total_work_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي أيام العمل"
                    ),
                ),
                (
                    "present_days",
                    models.PositiveIntegerField(default=0, verbose_name="أيام الحضور"),
                ),
                (
                    "absent_days",
                    models.PositiveIntegerField(default=0, verbose_name="أيام الغياب"),
                ),
                (
                    "leave_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="أيام الإجازة",
                    ),
                ),
                (
                    "late_days",
                    models.PositiveIntegerField(default=0, verbose_name="أيام التأخير"),
                ),
                (
                    "early_leave_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="أيام المغادرة المبكرة"
                    ),
                ),
                (
                    "total_work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="إجمالي ساعات العمل",
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="ساعات إضافية",
                    ),
                ),
                (
                    "late_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي دقائق التأخير"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملخص حضور",
                "verbose_name_plural": "ملخصات الحضور",
                "ordering": ["-year", "-month", "employee__emp_code"],
                "unique_together": {("employee", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "check_in",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check In Time"
                    ),
                ),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check Out Time"
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("leave", "Leave"),
                            ("holiday", "Holiday"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="Record Type",
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(default=0, verbose_name="Late Minutes"),
                ),
                (
                    "early_leave_minutes",
                    models.IntegerField(default=0, verbose_name="Early Leave Minutes"),
                ),
                (
                    "overtime_minutes",
                    models.IntegerField(default=0, verbose_name="Overtime Minutes"),
                ),
                (
                    "break_minutes",
                    models.IntegerField(default=0, verbose_name="Break Minutes"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_attendance_records",
                        to="employees.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "unique_together": {("employee", "date")},
            },
        ),
    ]
