# Generated by Django 4.2.7 on 2025-08-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employeebankaccount_bank_id_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerules',
            name='early_threshold',
            field=models.IntegerField(blank=True, db_column='EarlyThreshold', null=True, verbose_name='حد المغادرة المبكرة (دقائق)'),
        ),
        migrations.AlterField(
            model_name='attendancerules',
            name='is_default',
            field=models.BooleanField(db_column='IsDefault', default=False, verbose_name='افتراضية'),
        ),
        migrations.AlterField(
            model_name='attendancerules',
            name='late_threshold',
            field=models.IntegerField(blank=True, db_column='LateThreshold', null=True, verbose_name='حد التأخير (دقائق)'),
        ),
        migrations.AlterField(
            model_name='attendancerules',
            name='overtime_start_after',
            field=models.TimeField(blank=True, db_column='OvertimeStartAfter', null=True, verbose_name='بداية الوقت الإضافي'),
        ),
        migrations.AlterField(
            model_name='attendancerules',
            name='rule_name',
            field=models.CharField(blank=True, db_column='RuleName', max_length=100, null=True, verbose_name='اسم القاعدة'),
        ),
        migrations.AlterField(
            model_name='attendancerules',
            name='shift_end',
            field=models.TimeField(blank=True, db_column='ShiftEnd', null=True, verbose_name='نهاية الوردية'),
        ),
        migrations.AlterField(
            model_name='attendancerules',
            name='shift_start',
            field=models.TimeField(blank=True, db_column='ShiftStart', null=True, verbose_name='بداية الوردية'),
        ),
        migrations.AlterField(
            model_name='attendancerules',
            name='week_end_days',
            field=models.CharField(blank=True, db_column='WeekEndDays', max_length=20, null=True, verbose_name='أيام نهاية الأسبوع'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='att_date',
            field=models.DateField(blank=True, db_column='AttDate', null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='check_in',
            field=models.DateTimeField(blank=True, db_column='CheckIn', null=True, verbose_name='وقت الدخول'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='check_out',
            field=models.DateTimeField(blank=True, db_column='CheckOut', null=True, verbose_name='وقت الخروج'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='emp',
            field=models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='rule',
            field=models.ForeignKey(blank=True, db_column='RuleID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancerules', verbose_name='قاعدة الحضور'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(blank=True, db_column='Status', max_length=20, null=True, verbose_name='الحالة'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('emp', 'att_date')},
        ),
    ]
