# Generated by Django 4.2.26 on 2025-12-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "branch_id",
                    models.AutoField(
                        db_column="BranchID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(db_column="BranchName", max_length=150),
                ),
                (
                    "branch_address",
                    models.CharField(
                        blank=True, db_column="BranchAddress", max_length=500, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_column="Phone", max_length=50, null=True
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_column="ManagerID", null=True),
                ),
                ("is_active", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_column="CompanyID",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "الفرع",
                "verbose_name_plural": "الأفرع",
                "db_table": "Branches",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "job_id",
                    models.AutoField(
                        db_column="JobID", primary_key=True, serialize=False
                    ),
                ),
                ("job_title", models.CharField(db_column="JobTitle", max_length=150)),
                (
                    "job_level",
                    models.IntegerField(blank=True, db_column="JobLevel", null=True),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        blank=True,
                        db_column="BasicSalary",
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=500, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_column="IsActive", default=True)),
            ],
            options={
                "verbose_name": "الوظيفة",
                "verbose_name_plural": "الوظائف",
                "db_table": "Jobs",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.AutoField(
                        db_column="DeptID", primary_key=True, serialize=False
                    ),
                ),
                ("dept_name", models.CharField(db_column="DeptName", max_length=150)),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_column="ManagerID", null=True),
                ),
                ("is_active", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        db_column="BranchID",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="org.branch",
                    ),
                ),
                (
                    "parent_dept",
                    models.ForeignKey(
                        blank=True,
                        db_column="ParentDeptID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="org.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "القسم",
                "verbose_name_plural": "الأقسام",
                "db_table": "Departments",
            },
        ),
    ]
