# Generated by Django 4.2.7 on 2025-08-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(blank=True, db_column='CompanyID', null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
    ]
