# Generated by Django 4.2.30 on 2026-04-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0002_alter_leavepolicy_department"),
        ("employees", "0003_alter_employee_dept"),
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
    ]
