# Generated by Django 5.2.8 on 2025-12-17 15:15
# Modified to remove SQL Server specific collation for SQLite compatibility

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_tblcategories_cat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinvoices',
            name='invoice_type',
            field=models.CharField(blank=True, db_column='Invoice_Type', max_length=100, null=True),
        ),
    ]
