# Generated by Django 5.2.8 on 2025-12-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_tblinvoices_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcategories',
            name='cat_name',
            field=models.CharField(blank=True, db_column='CAT_Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblcustomers',
            name='customer_name',
            field=models.CharField(blank=True, db_column='Customer_Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoices',
            name='invoice_number',
            field=models.CharField(db_column='Invoice_Number', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblinvoices',
            name='invoice_type',
            field=models.CharField(blank=True, db_column='Invoice_Type', max_length=100, null=True),
        ),
    ]
