# Generated by Django 5.2.8 on 2025-12-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_tblcategories_cat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinvoiceitems',
            name='data_entry_by',
            field=models.CharField(blank=True, db_column='Data_Entry_By', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoiceitems',
            name='invoice_number',
            field=models.CharField(blank=True, db_column='Invoice_Number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoiceitems',
            name='invoice_type',
            field=models.CharField(blank=True, db_column='Invoice_Type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoiceitems',
            name='machine_unit',
            field=models.CharField(blank=True, db_column='Machine_Unit', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoiceitems',
            name='notes',
            field=models.CharField(blank=True, db_column='Notes', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoiceitems',
            name='product_name',
            field=models.CharField(blank=True, db_column='Product_Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoiceitems',
            name='received_machine',
            field=models.CharField(blank=True, db_column='Received_Machine', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoiceitems',
            name='recipient',
            field=models.CharField(blank=True, db_column='Recipient', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoiceitems',
            name='returninvoicenumber',
            field=models.CharField(blank=True, db_column='ReturnInvoiceNumber', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoices',
            name='customer_invoice_number',
            field=models.CharField(blank=True, db_column='Customer_Invoice_Number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoices',
            name='recipient',
            field=models.CharField(blank=True, db_column='Recipient', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblinvoices',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, db_column='Supplier_Invoice_Number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tblproducts',
            name='cat_name',
            field=models.CharField(blank=True, db_column='CAT_Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblproducts',
            name='expiry_warning',
            field=models.CharField(blank=True, db_column='Expiry_Warning', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tblproducts',
            name='location',
            field=models.CharField(blank=True, db_column='Location', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblproducts',
            name='product_id',
            field=models.CharField(db_column='Product_ID', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblproducts',
            name='product_name',
            field=models.CharField(blank=True, db_column='Product_Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblproducts',
            name='unit_name',
            field=models.CharField(blank=True, db_column='Unit_Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblsuppliers',
            name='supplier_name',
            field=models.CharField(blank=True, db_column='Supplier_Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblunitsspareparts',
            name='unit_name',
            field=models.CharField(blank=True, db_column='Unit_Name', max_length=100, null=True),
        ),
    ]
