# Generated by Django 4.2.30 on 2026-04-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0003_rename_tasks_status_031d4c_idx_core_tasks_status_db8e28_idx_and_more",
        ),
        ("inventory", "0006_alter_tblinvoiceitems_data_entry_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
        migrations.AlterField(
            model_name="voucher",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_vouchers",
                to="core.department",
                verbose_name="القسم",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.supplier",),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.productcategory",),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.product",),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.unit",),
        ),
    ]
