# Generated by Django 4.2.26 on 2025-12-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القسم")),
                (
                    "icon",
                    models.CharField(
                        help_text="اسم الأيقونة من Font Awesome مثال: fa-user",
                        max_length=50,
                        verbose_name="أيقونة القسم",
                    ),
                ),
                (
                    "url_name",
                    models.CharField(
                        help_text="الاسم المستخدم في الروابط",
                        max_length=100,
                        verbose_name="اسم الرابط",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="وصف القسم"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "require_admin",
                    models.BooleanField(
                        default=False, verbose_name="يتطلب صلاحيات المدير"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="allowed_departments",
                        to="auth.group",
                        verbose_name="المجموعات المسموح لها",
                    ),
                ),
            ],
            options={
                "verbose_name": "القسم",
                "verbose_name_plural": "الأقسام",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "db_host",
                    models.CharField(
                        default="localhost",
                        max_length=255,
                        verbose_name="مضيف قاعدة البيانات",
                    ),
                ),
                (
                    "db_name",
                    models.CharField(
                        default="eldawliya_db",
                        max_length=255,
                        verbose_name="اسم قاعدة البيانات",
                    ),
                ),
                (
                    "db_user",
                    models.CharField(
                        default="root",
                        max_length=255,
                        verbose_name="مستخدم قاعدة البيانات",
                    ),
                ),
                (
                    "db_password",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="كلمة مرور قاعدة البيانات",
                    ),
                ),
                (
                    "db_port",
                    models.CharField(
                        default="3306",
                        max_length=10,
                        verbose_name="منفذ قاعدة البيانات",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="الشركة الدولية",
                        max_length=255,
                        verbose_name="اسم الشركة",
                    ),
                ),
                (
                    "company_address",
                    models.TextField(blank=True, verbose_name="عنوان الشركة"),
                ),
                (
                    "company_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="هاتف الشركة"
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="البريد الإلكتروني للشركة",
                    ),
                ),
                (
                    "company_website",
                    models.URLField(blank=True, verbose_name="موقع الشركة"),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        upload_to="company_logos/",
                        verbose_name="شعار الشركة",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        default="نظام الدولية",
                        max_length=255,
                        verbose_name="اسم النظام",
                    ),
                ),
                (
                    "enable_debugging",
                    models.BooleanField(
                        default=False, verbose_name="تفعيل وضع التصحيح"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="وضع الصيانة"),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("Asia/Riyadh", "الرياض (Asia/Riyadh)"),
                            ("Asia/Dubai", "دبي (Asia/Dubai)"),
                            ("Asia/Kuwait", "الكويت (Asia/Kuwait)"),
                            ("Asia/Qatar", "قطر (Asia/Qatar)"),
                            ("Asia/Bahrain", "البحرين (Asia/Bahrain)"),
                            ("Africa/Cairo", "القاهرة (Africa/Cairo)"),
                            ("UTC", "التوقيت العالمي (UTC)"),
                        ],
                        default="Asia/Riyadh",
                        max_length=50,
                        verbose_name="المنطقة الزمنية",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("Y-m-d", "YYYY-MM-DD (2024-01-15)"),
                            ("d/m/Y", "DD/MM/YYYY (15/01/2024)"),
                            ("m/d/Y", "MM/DD/YYYY (01/15/2024)"),
                            ("d-m-Y", "DD-MM-YYYY (15-01-2024)"),
                        ],
                        default="Y-m-d",
                        max_length=50,
                        verbose_name="تنسيق التاريخ",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "English")],
                        default="ar",
                        max_length=2,
                        verbose_name="لغة النظام",
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        choices=[
                            ("cairo", "Cairo"),
                            ("tajawal", "Tajawal"),
                            ("almarai", "Almarai"),
                            ("ibm-plex-sans-arabic", "IBM Plex Sans Arabic"),
                            ("noto-sans-arabic", "Noto Sans Arabic"),
                        ],
                        default="cairo",
                        max_length=50,
                        verbose_name="الخط المستخدم",
                    ),
                ),
                (
                    "text_direction",
                    models.CharField(
                        choices=[
                            ("rtl", "من اليمين إلى اليسار"),
                            ("ltr", "من اليسار إلى اليمين"),
                        ],
                        default="rtl",
                        max_length=3,
                        verbose_name="اتجاه النص",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات النظام",
                "verbose_name_plural": "إعدادات النظام",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الوحدة")),
                ("icon", models.CharField(max_length=50, verbose_name="أيقونة الوحدة")),
                ("url", models.CharField(max_length=200, verbose_name="رابط الوحدة")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="وصف الوحدة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "bg_color",
                    models.CharField(
                        default="#3498db", max_length=20, verbose_name="لون الخلفية"
                    ),
                ),
                (
                    "require_admin",
                    models.BooleanField(
                        default=False, verbose_name="يتطلب صلاحيات المدير"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="administrator.department",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="allowed_modules",
                        to="auth.group",
                        verbose_name="المجموعات المسموح لها",
                    ),
                ),
            ],
            options={
                "verbose_name": "الوحدة",
                "verbose_name_plural": "الوحدات",
                "ordering": ["department__order", "order"],
            },
        ),
    ]
