# Generated by Django 5.0.14 on 2025-04-17 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('icon', models.CharField(help_text='اسم الأيقونة من Font Awesome مثال: fa-user', max_length=50, verbose_name='أيقونة القسم')),
                ('url_name', models.CharField(help_text='الاسم المستخدم في الروابط', max_length=100, verbose_name='اسم الرابط')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف القسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'القسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_host', models.CharField(max_length=255, verbose_name='قاعدة البيانات - المضيف')),
                ('db_name', models.CharField(max_length=255, verbose_name='قاعدة البيانات - الاسم')),
                ('db_user', models.CharField(max_length=255, verbose_name='قاعدة البيانات - اسم المستخدم')),
                ('db_password', models.CharField(max_length=255, verbose_name='قاعدة البيانات - كلمة المرور')),
                ('db_port', models.CharField(default='1433', max_length=10, verbose_name='قاعدة البيانات - المنفذ')),
                ('company_name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('company_address', models.TextField(blank=True, verbose_name='عنوان الشركة')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='هاتف الشركة')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني للشركة')),
                ('company_website', models.URLField(blank=True, verbose_name='موقع الشركة الإلكتروني')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='شعار الشركة')),
                ('system_name', models.CharField(default='نظام الدولية', max_length=255, verbose_name='اسم النظام')),
                ('enable_debugging', models.BooleanField(default=False, verbose_name='تفعيل وضع التصحيح')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50, verbose_name='المنطقة الزمنية')),
                ('date_format', models.CharField(default='Y-m-d', max_length=50, verbose_name='تنسيق التاريخ')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوحدة')),
                ('icon', models.CharField(max_length=50, verbose_name='أيقونة الوحدة')),
                ('url', models.CharField(max_length=255, verbose_name='رابط الوحدة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف الوحدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('bg_color', models.CharField(default='#3498db', max_length=20, verbose_name='لون الخلفية')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='administrator.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'الوحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['department__order', 'order'],
            },
        ),
    ]
