# Generated by Django 5.0.14 on 2025-04-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='font_family',
            field=models.CharField(choices=[('cairo', 'Cairo'), ('tajawal', 'Tajawal'), ('almarai', 'Almarai'), ('ibm-plex-sans-arabic', 'IBM Plex Sans Arabic'), ('noto-sans-arabic', 'Noto Sans Arabic')], default='cairo', max_length=50, verbose_name='الخط المستخدم'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2, verbose_name='لغة النظام'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='text_direction',
            field=models.CharField(choices=[('rtl', 'من اليمين إلى اليسار'), ('ltr', 'من اليسار إلى اليمين')], default='rtl', max_length=3, verbose_name='اتجاه النص'),
        ),
    ]
