# Generated by Django 5.0.14 on 2025-04-17 13:53

from django.db import migrations

def create_default_system_settings(apps, schema_editor):
    SystemSettings = apps.get_model('administrator', 'SystemSettings')
    if not SystemSettings.objects.exists():
        SystemSettings.objects.create(
            language='ar',
            font_family='cairo',
            text_direction='rtl'
        )

def reverse_default_system_settings(apps, schema_editor):
    SystemSettings = apps.get_model('administrator', 'SystemSettings')
    SystemSettings.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_systemsettings_font_family_systemsettings_language_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_system_settings, reverse_default_system_settings),
    ]
