# Generated by Django 5.0.14 on 2025-04-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_create_default_system_settings'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_departments', to='auth.group', verbose_name='المجموعات المسموح لها'),
        ),
        migrations.AddField(
            model_name='department',
            name='require_admin',
            field=models.BooleanField(default=False, verbose_name='يتطلب صلاحيات المدير'),
        ),
        migrations.AddField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_modules', to='auth.group', verbose_name='المجموعات المسموح لها'),
        ),
        migrations.AddField(
            model_name='module',
            name='require_admin',
            field=models.BooleanField(default=False, verbose_name='يتطلب صلاحيات المدير'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'عرض'), ('add', 'إضافة'), ('change', 'تعديل'), ('delete', 'حذف'), ('print', 'طباعة')], max_length=10, verbose_name='نوع الصلاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_permissions', to='auth.group', verbose_name='المجموعات المسموح لها')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='administrator.module', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'الصلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'unique_together': {('module', 'permission_type')},
            },
        ),
    ]
