# Generated by Django 5.0.14 on 2025-05-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_systemsettings_date_format_and_more'),
        ('administrator', '0004_update_systemsettings_choices'),
    ]

    operations = [
    ]
