# Generated by Django 5.0.14 on 2025-04-20 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_department_groups_department_require_admin_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمين المسموح لهم'),
        ),
        migrations.CreateModel(
            name='TemplatePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('app_name', models.CharField(max_length=50, verbose_name='اسم التطبيق')),
                ('template_path', models.CharField(max_length=255, verbose_name='مسار القالب')),
                ('url_pattern', models.CharField(blank=True, max_length=255, verbose_name='نمط URL')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('groups', models.ManyToManyField(blank=True, related_name='template_permissions', to='auth.group', verbose_name='المجموعات المسموح لها')),
                ('users', models.ManyToManyField(blank=True, related_name='template_permissions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمين المسموح لهم')),
            ],
            options={
                'verbose_name': 'صلاحية قالب',
                'verbose_name_plural': 'صلاحيات القوالب',
                'ordering': ['app_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='auth.group', verbose_name='المجموعة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عضوية مجموعة',
                'verbose_name_plural': 'عضويات المجموعات',
            },
        ),
    ]
