# Generated by Django 5.0.14 on 2025-04-21 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_permission_users_templatepermission_usergroup'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together={('user', 'group')},
        ),
        migrations.CreateModel(
            name='UserDepartmentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='عرض')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.department', verbose_name='القسم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_permissions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية قسم',
                'verbose_name_plural': 'صلاحيات الأقسام',
                'unique_together': {('user', 'department')},
            },
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='عرض')),
                ('can_add', models.BooleanField(default=False, verbose_name='إضافة')),
                ('can_edit', models.BooleanField(default=False, verbose_name='تعديل')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('can_print', models.BooleanField(default=False, verbose_name='طباعة')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.module', verbose_name='الوحدة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية وحدة',
                'verbose_name_plural': 'صلاحيات الوحدات',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
