# Generated by Django 5.0.14 on 2025-04-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_alter_usergroup_unique_together_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='وصف المجموعة')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group', verbose_name='المجموعة')),
            ],
            options={
                'verbose_name': 'ملف المجموعة',
                'verbose_name_plural': 'ملفات المجموعات',
            },
        ),
    ]
