# Generated by Django 5.0.14 on 2025-04-21 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_groupprofile'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التغيير')),
                ('action', models.CharField(choices=[('add', 'إضافة'), ('remove', 'إزالة'), ('modify', 'تعديل')], max_length=10, verbose_name='الإجراء')),
                ('object_type', models.CharField(choices=[('user', 'مستخدم'), ('group', 'مجموعة'), ('permission', 'صلاحية'), ('module', 'وحدة'), ('department', 'قسم'), ('template', 'قالب')], max_length=20, verbose_name='نوع الكائن')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف الكائن')),
                ('description', models.TextField(verbose_name='وصف التغيير')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق الصلاحيات',
                'verbose_name_plural': 'سجلات تدقيق الصلاحيات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='administrat_user_id_610edc_idx'), models.Index(fields=['action'], name='administrat_action_04c8da_idx'), models.Index(fields=['object_type'], name='administrat_object__bafb01_idx'), models.Index(fields=['content_type', 'object_id'], name='administrat_content_c3afb0_idx'), models.Index(fields=['timestamp'], name='administrat_timesta_af25c2_idx')],
            },
        ),
    ]
