# Generated by Django 4.2.7 on 2025-08-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('step_id', models.AutoField(db_column='StepID', primary_key=True, serialize=False)),
                ('step_name', models.CharField(db_column='StepName', max_length=100)),
                ('sequence_no', models.IntegerField(db_column='SequenceNo')),
                ('role_id', models.IntegerField(blank=True, db_column='RoleID', null=True)),
            ],
            options={
                'verbose_name': 'خطوة سير عمل',
                'verbose_name_plural': 'خطوات سير العمل',
                'db_table': 'WorkflowSteps',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('instance_id', models.AutoField(db_column='InstanceID', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='Status', max_length=30)),
                ('action_date', models.DateTimeField(blank=True, db_column='ActionDate', null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500, null=True)),
                ('emp', models.ForeignKey(blank=True, db_column='EmpID', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('step', models.ForeignKey(blank=True, db_column='StepID', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowstep')),
            ],
            options={
                'verbose_name': 'حالة سير عمل',
                'verbose_name_plural': 'حالات سير العمل',
                'db_table': 'WorkflowInstances',
            },
        ),
    ]
