# Generated by Django 4.2.7 on 2025-08-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsuranceProvider',
            fields=[
                ('provider_id', models.AutoField(db_column='ProviderID', primary_key=True, serialize=False)),
                ('provider_name', models.CharField(db_column='ProviderName', max_length=150)),
                ('contact_no', models.CharField(blank=True, db_column='ContactNo', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'مزود تأمين صحي',
                'verbose_name_plural': 'مزودو التأمين الصحي',
                'db_table': 'HealthInsuranceProviders',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSocialInsurance',
            fields=[
                ('social_id', models.AutoField(db_column='SocialID', primary_key=True, serialize=False)),
                ('gosi_no', models.CharField(blank=True, db_column='GosiNo', max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('contribution', models.DecimalField(blank=True, db_column='Contribution', decimal_places=2, max_digits=18, null=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'تأمين اجتماعي (GOSI)',
                'verbose_name_plural': 'تأمينات اجتماعية للموظفين',
                'db_table': 'EmployeeSocialInsurance',
            },
        ),
        migrations.CreateModel(
            name='EmployeeHealthInsurance',
            fields=[
                ('ins_id', models.AutoField(db_column='InsID', primary_key=True, serialize=False)),
                ('policy_no', models.CharField(blank=True, db_column='PolicyNo', max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('premium', models.DecimalField(blank=True, db_column='Premium', decimal_places=2, max_digits=18, null=True)),
                ('dependents', models.IntegerField(db_column='Dependents', default=0)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('provider', models.ForeignKey(blank=True, db_column='ProviderID', null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.healthinsuranceprovider')),
            ],
            options={
                'verbose_name': 'تأمين صحي للموظف',
                'verbose_name_plural': 'تأمينات صحية للموظفين',
                'db_table': 'EmployeeHealthInsurance',
            },
        ),
    ]
