# Generated by Django 4.2.26 on 2025-12-16 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeLoan",
            fields=[
                (
                    "loan_id",
                    models.AutoField(
                        db_column="LoanID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "request_amount",
                    models.DecimalField(
                        blank=True,
                        db_column="RequestAmount",
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        db_column="ApprovedAmount",
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "installment_amt",
                    models.DecimalField(
                        blank=True,
                        db_column="InstallmentAmt",
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, db_column="StartDate", null=True),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, db_column="EndDate", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="Status", default="Pending", max_length=30
                    ),
                ),
                (
                    "approved_by",
                    models.IntegerField(blank=True, db_column="ApprovedBy", null=True),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="EmpID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "سلفة موظف",
                "verbose_name_plural": "سلف الموظفين",
                "db_table": "EmployeeLoans",
            },
        ),
        migrations.CreateModel(
            name="HRSystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المفتاح"
                    ),
                ),
                ("value", models.TextField(verbose_name="القيمة")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعداد النظام",
                "verbose_name_plural": "إعدادات النظام",
                "db_table": "hr_system_config",
            },
        ),
        migrations.CreateModel(
            name="LoanType",
            fields=[
                (
                    "loan_type_id",
                    models.AutoField(
                        db_column="LoanTypeID", primary_key=True, serialize=False
                    ),
                ),
                ("type_name", models.CharField(db_column="TypeName", max_length=100)),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        db_column="MaxAmount",
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "max_installments",
                    models.IntegerField(
                        blank=True, db_column="MaxInstallments", null=True
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True,
                        db_column="InterestRate",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع سلفة",
                "verbose_name_plural": "أنواع السلف",
                "db_table": "LoanTypes",
            },
        ),
        migrations.CreateModel(
            name="LoanInstallment",
            fields=[
                (
                    "installment_id",
                    models.AutoField(
                        db_column="InstallmentID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, db_column="DueDate", null=True),
                ),
                (
                    "paid_date",
                    models.DateField(blank=True, db_column="PaidDate", null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        db_column="Amount",
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "penalty",
                    models.DecimalField(
                        db_column="Penalty", decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="Status", default="Pending", max_length=20
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        db_column="LoanID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.employeeloan",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسط سلفة",
                "verbose_name_plural": "أقساط السلف",
                "db_table": "LoanInstallments",
            },
        ),
        migrations.CreateModel(
            name="HRSystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إنشاء"),
                            ("update", "تحديث"),
                            ("delete", "حذف"),
                            ("view", "عرض"),
                            ("export", "تصدير"),
                            ("import", "استيراد"),
                        ],
                        max_length=20,
                        verbose_name="الإجراء",
                    ),
                ),
                ("module", models.CharField(max_length=50, verbose_name="الوحدة")),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="معرف الكائن",
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الحدث"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل النظام",
                "verbose_name_plural": "سجلات النظام",
                "db_table": "hr_system_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="employeeloan",
            name="loan_type",
            field=models.ForeignKey(
                blank=True,
                db_column="LoanTypeID",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.loantype",
            ),
        ),
    ]
