# Generated by Django 5.0.14 on 2025-05-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0002_initial'),
        ('cars', '0003_employee_alter_car_car_status_alter_car_car_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='car_route_points', to='Hr.employee', verbose_name='الموظفين'),
        ),
    ]
