# Generated by Django 4.2.7 on 2025-08-11 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0004_delete_employee_alter_routepoint_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepoint',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='car_route_points', to=settings.AUTH_USER_MODEL, verbose_name='الموظفون'),
        ),
    ]
