# Generated by Django 5.0.14 on 2025-05-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('view_dashboard', 'Can view tasks dashboard'), ('view_mytask', 'Can view my tasks'), ('view_report', 'Can view task reports'), ('export_report', 'Can export task reports')]},
        ),
    ]
