# Generated by Django 5.0.14 on 2025-04-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_by_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'يجرى العمل عليها'), ('completed', 'مكتملة'), ('canceled', 'ملغاة')], default='pending', max_length=20),
        ),
    ]
