# Generated by Django 4.2.22 on 2025-08-29 02:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employeebankaccount_bank_id_and_more'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeevaluation',
            options={'ordering': ['-eval_date', '-created_at'], 'verbose_name': 'تقييم موظف', 'verbose_name_plural': 'تقييمات الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='evaluationperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'فترة تقييم', 'verbose_name_plural': 'فترات التقييم'},
        ),
        migrations.AddField(
            model_name='employeeevaluation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeevaluation',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_column='Status', default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='employeeevaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='evaluationperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationperiod',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='employeeevaluation',
            name='emp',
            field=models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeeevaluation',
            name='eval_date',
            field=models.DateField(blank=True, db_column='EvalDate', null=True, verbose_name='تاريخ التقييم'),
        ),
        migrations.AlterField(
            model_name='employeeevaluation',
            name='manager_id',
            field=models.IntegerField(blank=True, db_column='ManagerID', null=True, verbose_name='المدير المقيم'),
        ),
        migrations.AlterField(
            model_name='employeeevaluation',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='employeeevaluation',
            name='period',
            field=models.ForeignKey(db_column='PeriodID', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.evaluationperiod', verbose_name='فترة التقييم'),
        ),
        migrations.AlterField(
            model_name='employeeevaluation',
            name='score',
            field=models.DecimalField(blank=True, db_column='Score', decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='evaluationperiod',
            name='end_date',
            field=models.DateField(db_column='EndDate', verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='evaluationperiod',
            name='period_name',
            field=models.CharField(db_column='PeriodName', max_length=100, verbose_name='اسم الفترة'),
        ),
        migrations.AlterField(
            model_name='evaluationperiod',
            name='start_date',
            field=models.DateField(db_column='StartDate', verbose_name='تاريخ البداية'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeevaluation',
            unique_together={('emp', 'period')},
        ),
    ]
