# Generated by Django 5.0.14 on 2025-07-23 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_login_new_groups_and_more'),
        ('tasks', '0006_alter_task_assigned_to_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='accounts.users_login_new', verbose_name='المكلف بالمهمة'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='accounts.users_login_new', verbose_name='منشئ المهمة'),
        ),
    ]
