# Generated by Django 4.2.7 on 2025-08-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_type_id', models.AutoField(db_column='LeaveTypeID', primary_key=True, serialize=False)),
                ('leave_name', models.CharField(db_column='LeaveName', max_length=100)),
                ('max_days_per_year', models.IntegerField(blank=True, db_column='MaxDaysPerYear', null=True)),
                ('is_paid', models.BooleanField(db_column='IsPaid', default=False)),
            ],
            options={
                'verbose_name': 'نوع إجازة',
                'verbose_name_plural': 'أنواع الإجازات',
                'db_table': 'LeaveTypes',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('leave_id', models.AutoField(db_column='LeaveID', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='StartDate')),
                ('end_date', models.DateField(db_column='EndDate')),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=500, null=True)),
                ('status', models.CharField(db_column='Status', default='Pending', max_length=30)),
                ('approved_by', models.IntegerField(blank=True, db_column='ApprovedBy', null=True)),
                ('approved_date', models.DateTimeField(blank=True, db_column='ApprovedDate', null=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('leave_type', models.ForeignKey(db_column='LeaveTypeID', on_delete=django.db.models.deletion.PROTECT, to='leaves.leavetype')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'إجازات الموظفين',
                'db_table': 'EmployeeLeaves',
            },
        ),
    ]
