# Generated by Django 4.2.7 on 2025-08-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(db_column='CompanyID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CompanyName', max_length=200)),
                ('name_en', models.CharField(blank=True, db_column='CompanyNameEN', max_length=200, null=True)),
                ('tax_number', models.CharField(blank=True, db_column='TaxNumber', max_length=50, null=True)),
                ('commercial_register', models.CharField(blank=True, db_column='CommercialRegister', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=100, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=500, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='PostalCode', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'db_table': 'Companies',
            },
        ),
    ]
