# Generated by Django 5.2.8 on 2026-02-07 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف التصنيف')),
                ('color', models.CharField(default='#3498db', max_length=20, verbose_name='اللون')),
                ('icon', models.CharField(default='fas fa-tasks', max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تصنيف المهام',
                'verbose_name_plural': 'تصنيفات المهام',
                'db_table': 'task_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='عنوان مختصر للمهمة (اختياري)', max_length=200, null=True, verbose_name='عنوان المهمة')),
                ('is_private', models.BooleanField(default=False, help_text='إذا كان خاصًا، فلن يراه إلا المنشئ والمكلف', verbose_name='خاص')),
                ('progress', models.PositiveIntegerField(default=0, help_text='من 0 إلى 100', verbose_name='نسبة الإنجاز (%)')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('description', models.TextField(help_text='وصف تفصيلي للمهمة والمطلوب إنجازه', verbose_name='وصف المهمة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'يجرى العمل عليها'), ('completed', 'مكتملة'), ('canceled', 'ملغاة'), ('deferred', 'مؤجلة'), ('failed', 'فشلت')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='المكلف بالمهمة')),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='منشئ المهمة')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='meetings.meeting', verbose_name='الاجتماع المرتبط')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
                'permissions': [('view_dashboard', 'Can view tasks dashboard'), ('view_mytask', 'Can view my tasks'), ('view_report', 'Can view task reports'), ('export_report', 'Can export task reports'), ('bulk_update', 'Can perform bulk updates on tasks')],
            },
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField(verbose_name='تاريخ التذكير')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'تذكير المهمة',
                'verbose_name_plural': 'تذكيرات المهام',
                'db_table': 'task_reminders',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='وصف تفصيلي للخطوة المتخذة', verbose_name='وصف الخطوة')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية حول هذه الخطوة', null=True, verbose_name='ملاحظات')),
                ('completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks_steps', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.task', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'خطوة مهمة',
                'verbose_name_plural': 'خطوات المهام',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_status_031d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='tasks_assigne_00feb5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='tasks_created_816ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['end_date'], name='tasks_end_dat_78c269_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_priorit_a9efa1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'assigned_to'], name='tasks_status_a6382a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'end_date'], name='tasks_status_41b087_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category', 'status'], name='tasks_categor_273e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['meeting', 'status'], name='tasks_meeting_925719_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_private', 'assigned_to'], name='tasks_is_priv_d08d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstep',
            index=models.Index(fields=['task'], name='tasks_tasks_task_id_279296_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstep',
            index=models.Index(fields=['completed'], name='tasks_tasks_complet_f2effc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstep',
            index=models.Index(fields=['date'], name='tasks_tasks_date_8f75dc_idx'),
        ),
    ]
