# Generated by Django 4.2.7 on 2025-08-11 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('action_id', models.AutoField(db_column='ActionID', primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_column='ActionType', max_length=50)),
                ('action_date', models.DateField(db_column='ActionDate')),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=500, null=True)),
                ('severity_level', models.IntegerField(blank=True, db_column='SeverityLevel', null=True)),
                ('decision_by', models.IntegerField(blank=True, db_column='DecisionBy', null=True)),
                ('valid_until', models.DateField(blank=True, db_column='ValidUntil', null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500, null=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'إجراء انضباطي',
                'verbose_name_plural': 'الإجراءات الانضباطية',
                'db_table': 'DisciplinaryActions',
            },
        ),
    ]
