# Generated by Django 5.0.14 on 2025-05-07 05:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', 'إضافة'), ('modify', 'تعديل'), ('remove', 'حذف')], max_length=10, verbose_name='نوع الإجراء')),
                ('department', models.CharField(max_length=100, verbose_name='القسم')),
                ('module', models.CharField(max_length=100, verbose_name='الوحدة')),
                ('permission_type', models.CharField(max_length=20, verbose_name='نوع الصلاحية')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ والوقت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('affected_groups', models.ManyToManyField(blank=True, related_name='admin_audit_logs', to='auth.group', verbose_name='المجموعات المتأثرة')),
                ('affected_users', models.ManyToManyField(blank=True, related_name='admin_affected_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمين المتأثرين')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_permission_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق الصلاحيات',
                'verbose_name_plural': 'سجلات تدقيق الصلاحيات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPermissionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('has_access', models.BooleanField(default=False, verbose_name='لديه صلاحية الوصول')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_permission_cache', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ذاكرة التخزين المؤقت لصلاحيات الأقسام',
                'verbose_name_plural': 'ذاكرة التخزين المؤقت لصلاحيات الأقسام',
                'unique_together': {('user', 'department_name')},
            },
        ),
        migrations.CreateModel(
            name='ModulePermissionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('module_name', models.CharField(max_length=100, verbose_name='اسم الوحدة')),
                ('permission_type', models.CharField(max_length=20, verbose_name='نوع الصلاحية')),
                ('has_permission', models.BooleanField(default=False, verbose_name='لديه صلاحية')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permission_cache', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ذاكرة التخزين المؤقت لصلاحيات الوحدات',
                'verbose_name_plural': 'ذاكرة التخزين المؤقت لصلاحيات الوحدات',
                'unique_together': {('user', 'department_name', 'module_name', 'permission_type')},
            },
        ),
    ]
