# Generated by Django 4.2.7 on 2025-08-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(db_column='PermissionID', primary_key=True, serialize=False)),
                ('permission_key', models.CharField(db_column='PermissionKey', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='RoleName', max_length=100)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='UserID')),
                ('role', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.CASCADE, to='rbac.role')),
            ],
            options={
                'verbose_name': 'دور المستخدم',
                'verbose_name_plural': 'أدوار المستخدمين',
                'db_table': 'UserRoles',
                'unique_together': {('user_id', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(db_column='PermissionID', on_delete=django.db.models.deletion.CASCADE, to='rbac.permission')),
                ('role', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.CASCADE, to='rbac.role')),
            ],
            options={
                'verbose_name': 'صلاحية الدور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'db_table': 'RolePermissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
