# Generated by Django 4.2.7 on 2025-08-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('loan_id', models.AutoField(db_column='LoanID', primary_key=True, serialize=False)),
                ('request_amount', models.DecimalField(blank=True, db_column='RequestAmount', decimal_places=2, max_digits=18, null=True)),
                ('approved_amount', models.DecimalField(blank=True, db_column='ApprovedAmount', decimal_places=2, max_digits=18, null=True)),
                ('installment_amt', models.DecimalField(blank=True, db_column='InstallmentAmt', decimal_places=2, max_digits=18, null=True)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('status', models.CharField(db_column='Status', default='Pending', max_length=30)),
                ('approved_by', models.IntegerField(blank=True, db_column='ApprovedBy', null=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'سلفة موظف',
                'verbose_name_plural': 'سلف الموظفين',
                'db_table': 'EmployeeLoans',
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('loan_type_id', models.AutoField(db_column='LoanTypeID', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='TypeName', max_length=100)),
                ('max_amount', models.DecimalField(blank=True, db_column='MaxAmount', decimal_places=2, max_digits=18, null=True)),
                ('max_installments', models.IntegerField(blank=True, db_column='MaxInstallments', null=True)),
                ('interest_rate', models.DecimalField(blank=True, db_column='InterestRate', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'نوع سلفة',
                'verbose_name_plural': 'أنواع السلف',
                'db_table': 'LoanTypes',
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('installment_id', models.AutoField(db_column='InstallmentID', primary_key=True, serialize=False)),
                ('due_date', models.DateField(blank=True, db_column='DueDate', null=True)),
                ('paid_date', models.DateField(blank=True, db_column='PaidDate', null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=18, null=True)),
                ('penalty', models.DecimalField(db_column='Penalty', decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(db_column='Status', default='Pending', max_length=20)),
                ('loan', models.ForeignKey(db_column='LoanID', on_delete=django.db.models.deletion.CASCADE, to='loans.employeeloan')),
            ],
            options={
                'verbose_name': 'قسط سلفة',
                'verbose_name_plural': 'أقساط السلف',
                'db_table': 'LoanInstallments',
            },
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='loan_type',
            field=models.ForeignKey(blank=True, db_column='LoanTypeID', null=True, on_delete=django.db.models.deletion.PROTECT, to='loans.loantype'),
        ),
    ]
