# Generated by Django 5.0.14 on 2025-07-23 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_login_new_groups_and_more'),
        ('employee_tasks', '0002_alter_employeetask_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employee_tasks', to='accounts.users_login_new', verbose_name='تم التكليف إلى'),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_employee_tasks', to='accounts.users_login_new', verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_task_steps', to='accounts.users_login_new', verbose_name='تم الإنشاء بواسطة'),
        ),
    ]
