# Generated by Django 4.2.22 on 2025-09-08 14:10

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0004_add_extended_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocumentCategory',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('category_code', models.CharField(max_length=20, unique=True, verbose_name='رمز الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_required', models.BooleanField(default=False, verbose_name='مطلوب')),
                ('max_file_size_mb', models.IntegerField(default=10, verbose_name='الحد الأقصى لحجم الملف (ميجابايت)')),
                ('allowed_extensions', models.CharField(default='pdf,doc,docx,jpg,jpeg,png', max_length=200, verbose_name='الامتدادات المسموحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فئة وثائق الموظف',
                'verbose_name_plural': 'فئات وثائق الموظفين',
                'db_table': 'EmployeeDocumentCategories',
                'ordering': ['sort_order', 'category_name'],
            },
        ),
        migrations.AddField(
            model_name='extendedemployeesocialinsurance',
            name='deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.0'), max_digits=5, verbose_name='نسبة الخصم'),
        ),
        migrations.AddField(
            model_name='extendedemployeesocialinsurance',
            name='incoming_document_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الوثيقة الواردة'),
        ),
        migrations.AddField(
            model_name='extendedemployeesocialinsurance',
            name='incoming_document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الوثيقة الواردة'),
        ),
        migrations.AddField(
            model_name='extendedemployeesocialinsurance',
            name='s1_field',
            field=models.BooleanField(default=False, verbose_name='حقل S1'),
        ),
        migrations.AlterField(
            model_name='extendedemployeesocialinsurance',
            name='insurance_status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق'), ('pending', 'في الانتظار')], default='active', max_length=20, verbose_name='حالة التأمين'),
        ),
        migrations.CreateModel(
            name='ExtendedEmployeeDocument',
            fields=[
                ('document_id', models.AutoField(db_column='DocumentID', primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=200, verbose_name='اسم الوثيقة')),
                ('document_file', models.FileField(upload_to='employee_documents/%Y/%m/', verbose_name='ملف الوثيقة')),
                ('file_size', models.BigIntegerField(verbose_name='حجم الملف (بايت)')),
                ('file_extension', models.CharField(max_length=10, verbose_name='امتداد الملف')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الوثيقة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employeedocumentcategory', verbose_name='فئة الوثيقة')),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='الموظف')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='تم التحقق بواسطة')),
            ],
            options={
                'verbose_name': 'وثيقة الموظف الموسعة',
                'verbose_name_plural': 'وثائق الموظفين الموسعة',
                'db_table': 'ExtendedEmployeeDocuments',
                'ordering': ['-created_at'],
            },
        ),
    ]
