# Generated by Django 4.2.7 on 2025-08-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticket_type_id', models.AutoField(db_column='TicketTypeID', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='TypeName', max_length=100)),
                ('max_tickets_per_year', models.IntegerField(blank=True, db_column='MaxTicketsPerYear', null=True)),
            ],
            options={
                'verbose_name': 'نوع تذكرة',
                'verbose_name_plural': 'أنواع التذاكر',
                'db_table': 'TicketTypes',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTicket',
            fields=[
                ('ticket_id', models.AutoField(db_column='TicketID', primary_key=True, serialize=False)),
                ('destination', models.CharField(blank=True, db_column='Destination', max_length=100, null=True)),
                ('travel_date', models.DateField(blank=True, db_column='TravelDate', null=True)),
                ('return_date', models.DateField(blank=True, db_column='ReturnDate', null=True)),
                ('status', models.CharField(db_column='Status', default='Requested', max_length=30)),
                ('approved_by', models.IntegerField(blank=True, db_column='ApprovedBy', null=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('ticket_type', models.ForeignKey(blank=True, db_column='TicketTypeID', null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.tickettype')),
            ],
            options={
                'verbose_name': 'تذكرة موظف',
                'verbose_name_plural': 'تذاكر الموظفين',
                'db_table': 'EmployeeTickets',
            },
        ),
    ]
