# Generated by Django 5.0.14 on 2025-06-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase_orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='Purchase_orders.vendor', verbose_name='المورد'),
        ),
    ]
