# Generated by Django 4.2.22 on 2025-08-29 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employeebankaccount_bank_id_and_more'),
        ('attendance', '0002_alter_attendancerules_early_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKDevice',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False, verbose_name='معرف الجهاز')),
                ('device_name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('device_serial', models.CharField(max_length=50, unique=True, verbose_name='الرقم التسلسلي')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('port', models.PositiveIntegerField(default=4370, verbose_name='المنفذ')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='الموقع')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('maintenance', 'صيانة')], default='active', max_length=20, verbose_name='الحالة')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50, verbose_name='المنطقة الزمنية')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'جهاز ZK',
                'verbose_name_plural': 'أجهزة ZK',
            },
        ),
        migrations.CreateModel(
            name='AttendanceProcessingLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='معرف السجل')),
                ('process_date', models.DateField(verbose_name='تاريخ المعالجة')),
                ('records_fetched', models.PositiveIntegerField(default=0, verbose_name='السجلات المجلبة')),
                ('records_processed', models.PositiveIntegerField(default=0, verbose_name='السجلات المعالجة')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='السجلات الفاشلة')),
                ('status', models.CharField(choices=[('success', 'نجح'), ('failed', 'فشل'), ('partial', 'جزئي')], max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='وقت المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.zkdevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'سجل معالجة الحضور',
                'verbose_name_plural': 'سجلات معالجة الحضور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZKAttendanceRaw',
            fields=[
                ('raw_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='معرف السجل')),
                ('user_id', models.CharField(max_length=20, verbose_name='معرف المستخدم في الجهاز')),
                ('timestamp', models.DateTimeField(verbose_name='الوقت والتاريخ')),
                ('punch_type', models.CharField(choices=[('0', 'Check In'), ('1', 'Check Out'), ('2', 'Break Out'), ('3', 'Break In'), ('4', 'Overtime In'), ('5', 'Overtime Out')], default='0', max_length=2, verbose_name='نوع البصمة')),
                ('verification_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='نوع التحقق')),
                ('work_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='كود العمل')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تم المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.zkdevice', verbose_name='الجهاز')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'بيانات ZK خام',
                'verbose_name_plural': 'البيانات الخام من ZK',
                'ordering': ['-timestamp'],
                'unique_together': {('device', 'user_id', 'timestamp', 'punch_type')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeDeviceMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False, verbose_name='معرف الربط')),
                ('device_user_id', models.CharField(max_length=20, verbose_name='معرف المستخدم في الجهاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.zkdevice', verbose_name='الجهاز')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'ربط موظف بجهاز',
                'verbose_name_plural': 'ربط الموظفين بالأجهزة',
                'unique_together': {('device', 'device_user_id')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='معرف الملخص')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('total_work_days', models.PositiveIntegerField(default=0, verbose_name='إجمالي أيام العمل')),
                ('present_days', models.PositiveIntegerField(default=0, verbose_name='أيام الحضور')),
                ('absent_days', models.PositiveIntegerField(default=0, verbose_name='أيام الغياب')),
                ('leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='أيام الإجازة')),
                ('late_days', models.PositiveIntegerField(default=0, verbose_name='أيام التأخير')),
                ('early_leave_days', models.PositiveIntegerField(default=0, verbose_name='أيام المغادرة المبكرة')),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='إجمالي ساعات العمل')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ساعات إضافية')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='إجمالي دقائق التأخير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'ملخص حضور',
                'verbose_name_plural': 'ملخصات الحضور',
                'ordering': ['-year', '-month', 'employee__emp_code'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
