# Generated by Django 5.0.14 on 2025-07-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0007_alter_department_created_at_and_more'),
        ('attendance', '0003_auto_20250708_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_leave_balances', to='Hr.employee', verbose_name='Employee'),
        ),
    ]
