# Generated by Django 4.2.7 on 2025-08-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_add_fullname_computed_column'),
        ('attendance', '0005_alter_attendancerecord_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRules',
            fields=[
                ('rule_id', models.AutoField(db_column='RuleID', primary_key=True, serialize=False)),
                ('rule_name', models.CharField(blank=True, db_column='RuleName', max_length=100, null=True)),
                ('shift_start', models.TimeField(blank=True, db_column='ShiftStart', null=True)),
                ('shift_end', models.TimeField(blank=True, db_column='ShiftEnd', null=True)),
                ('late_threshold', models.IntegerField(blank=True, db_column='LateThreshold', null=True)),
                ('early_threshold', models.IntegerField(blank=True, db_column='EarlyThreshold', null=True)),
                ('overtime_start_after', models.TimeField(blank=True, db_column='OvertimeStartAfter', null=True)),
                ('week_end_days', models.CharField(blank=True, db_column='WeekEndDays', max_length=20, null=True)),
                ('is_default', models.BooleanField(db_column='IsDefault', default=False)),
            ],
            options={
                'verbose_name': 'قاعدة حضور',
                'verbose_name_plural': 'قواعد الحضور',
                'db_table': 'AttendanceRules',
            },
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_attendance_records', to='employees.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeeattendanceprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_profile', to='employees.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_leave_balances', to='employees.employee', verbose_name='Employee'),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('att_id', models.BigAutoField(db_column='AttID', primary_key=True, serialize=False)),
                ('att_date', models.DateField(blank=True, db_column='AttDate', null=True)),
                ('check_in', models.DateTimeField(blank=True, db_column='CheckIn', null=True)),
                ('check_out', models.DateTimeField(blank=True, db_column='CheckOut', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('emp', models.ForeignKey(db_column='EmpID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('rule', models.ForeignKey(blank=True, db_column='RuleID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancerules')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'db_table': 'EmployeeAttendance',
            },
        ),
    ]
